// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns shell/runtime/i18n implementation. This file is deterministic bootstrap glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import { KGW_TABS } from "./src/tabs/tab-registry.js";
import initShellWasm, {
  shellAuxInstall as wasmShellAuxInstall,
  shellDisplayInstall as wasmShellDisplayInstall,
  shellI18nInstall as wasmShellI18nInstall,
  shellRuntimeActivateTab as wasmShellActivateTab,
  shellRuntimeApplyTheme as wasmShellApplyTheme,
  shellRuntimeInstall as wasmShellInstall,
  shellRuntimeOpenTab as wasmShellOpenTab,
} from "./generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await initShellWasm();
wasmShellInstall(KGW_TABS);
wasmShellAuxInstall();
wasmShellDisplayInstall();
wasmShellI18nInstall();

export async function openTab(tabId, options = {}) {
  return await wasmShellOpenTab(String(tabId || ""), options || {});
}
export function activateTab(tabId) {
  return wasmShellActivateTab(String(tabId || ""));
}
export function applyTheme(theme) {
  return wasmShellApplyTheme(String(theme || ""));
}
window.kgwOpenTab = openTab;
window.kgwActivateTab = activateTab;
window.kgwApplyTheme = applyTheme;
import("./src/core/header-live-metrics.js");
