// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Settings UI behavior, persistence, profiles, paths, diagnostics, database, addresses, and layout.
// This module is deterministic ABI/bootstrap glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  settingsAddressesInstallAll as wasmAddressesInstallAll,
  settingsAddressesOpenExplorer as wasmAddressesOpenExplorer,
  settingsAddressesRefresh as wasmAddressesRefresh,
  settingsDatabaseInstall as wasmDatabaseInstall,
  settingsDatabaseInstallMaintenance as wasmDatabaseInstallMaintenance,
  settingsDatabaseRefresh as wasmDatabaseRefresh,
  settingsLayoutInstallGlobal as wasmLayoutInstallGlobal,
  settingsLayoutInstallManageAddressesClean as wasmLayoutInstallManageAddressesClean,
  settingsLayoutInstallSettingsI18nBindings as wasmLayoutInstallSettingsI18nBindings,
  settingsUiInitTab as wasmSettingsUiInitTab,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export async function initSettingsTab() {
  return wasmSettingsUiInitTab();
}

async function kgwRefreshSettingsDatabaseStatus() {
  return await wasmDatabaseRefresh();
}

function kgwInstallSettingsDatabaseStatus() {
  return wasmDatabaseInstall();
}

async function kgwRefreshSettingsAddresses() {
  return await wasmAddressesRefresh();
}

function kgwOpenKaspaAddressInBrowser(address) {
  return wasmAddressesOpenExplorer(address);
}

function kgwInstallSettingsManageAddressesCleanLayout() {
  return wasmLayoutInstallManageAddressesClean();
}

function kgwInstallSettingsDbMaintenanceActions() {
  return wasmDatabaseInstallMaintenance();
}

window.kgwRefreshSettingsDatabaseStatus = kgwRefreshSettingsDatabaseStatus;
window.kgwInstallSettingsDatabaseStatus = kgwInstallSettingsDatabaseStatus;
window.kgwRefreshSettingsAddresses = kgwRefreshSettingsAddresses;
window.kgwOpenKaspaAddressInBrowser = kgwOpenKaspaAddressInBrowser;
window.kgwInstallSettingsManageAddressesCleanLayout = kgwInstallSettingsManageAddressesCleanLayout;
window.kgwInstallSettingsDbMaintenanceActions = kgwInstallSettingsDbMaintenanceActions;

kgwInstallSettingsDatabaseStatus();
wasmAddressesInstallAll();
kgwInstallSettingsManageAddressesCleanLayout();
wasmLayoutInstallSettingsI18nBindings();
kgwInstallSettingsDbMaintenanceActions();

const settingsRoot = document.getElementById("settings");
if (settingsRoot) {
  wasmLayoutInstallGlobal(settingsRoot);
} else {
  document.addEventListener("DOMContentLoaded", () => {
    const root = document.getElementById("settings");
    if (root) wasmLayoutInstallGlobal(root);
  }, { once: true });
}
