version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/apps/kaspa-gateway-desktop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
