// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Kaspa Bridge tab state, rendering, settings, runtime, logs, actions, and initialization.
// This module is deterministic browser/WASM ABI and compatibility glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  bridgeEffectiveInprocessNodeSettingsOwned,
  bridgeEffectiveSettingsV1,
  bridgeInitKaspaBridgeTab,
  bridgeValidateFormOwned,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export async function initKaspaBridgeTab(root) { return bridgeInitKaspaBridgeTab(root); }
export { bridgeEffectiveInprocessNodeSettingsOwned as kgwBridgeEffectiveInprocessNodeSettings };
export { bridgeEffectiveSettingsV1 as kgwBridgeEffectiveSettingsV1 };
export { bridgeValidateFormOwned as kgwBridgeValidateForm };
export default initKaspaBridgeTab;

window.initKaspaBridgeTab = initKaspaBridgeTab;
