// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  parseHeaderUsdPrice as wasmParseHeaderUsdPrice,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function parseHeaderUsdPrice() {
  return wasmParseHeaderUsdPrice();
}
