// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  explorerApplyFontSize as wasmExplorerApplyFontSize,
  explorerApplyLocalBusyControls as wasmExplorerApplyLocalBusyControls,
  explorerBindFontSpinbox as wasmExplorerBindFontSpinbox,
  explorerDefaultDates as wasmExplorerDefaultDates,
  explorerSetTableFontSize as wasmExplorerSetTableFontSize,
  kgwClean2SafeText as wasmKgwClean2SafeText,
  pick as wasmPick,
  toEnglishDigits as wasmToEnglishDigits,
  toNumber as wasmToNumber,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function toEnglishDigits(value) {
  return wasmToEnglishDigits(value);
}

export function pick(...values) {
  return wasmPick(values);
}

export function toNumber(value, fallback = 0) {
  return wasmToNumber(value, fallback);
}

export function kgwClean2SafeText(value) {
  return wasmKgwClean2SafeText(value);
}

export function setTableFontSize(section) {
  return wasmExplorerSetTableFontSize(section);
}

export function kgwApplyExplorerFontSize(section, rawValue) {
  return wasmExplorerApplyFontSize(section, rawValue);
}

export function kgwBindFontSpinbox(section) {
  return wasmExplorerBindFontSpinbox(section);
}

export function defaultDates(section) {
  return wasmExplorerDefaultDates(section);
}

export function kgwApplyExplorerLocalBusyControls(section, busy) {
  return wasmExplorerApplyLocalBusyControls(section, busy);
}
