// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Explorer tab init/events/fetch/filter/cancel/live-core/diagnostics orchestration.
// This module is deterministic browser/WASM ABI/bootstrap glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  explorerInitTab as wasmInitExplorerTab,
  explorerTabInstall as wasmInstallExplorerTab,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();
wasmInstallExplorerTab();

export async function initExplorerTab() {
  return await wasmInitExplorerTab();
}

window.initExplorerTab = initExplorerTab;
