// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  explorerAddressDiagnosticsSnapshot as wasmExplorerAddressDiagnosticsSnapshot,
  explorerAddressLookupKeys as wasmExplorerAddressLookupKeys,
  explorerApplyFontSize as wasmExplorerApplyFontSize,
  explorerApplyLocalBusyControls as wasmExplorerApplyLocalBusyControls,
  explorerBindFontSpinbox as wasmExplorerBindFontSpinbox,
  explorerCanonicalKaspaAddress as wasmExplorerCanonicalKaspaAddress,
  explorerBuildListRequest as wasmExplorerBuildListRequest,
  explorerDefaultDates as wasmExplorerDefaultDates,
  explorerEnsureFilterOptions as wasmExplorerEnsureFilterOptions,
  explorerFetchBalance as wasmExplorerFetchBalance,
  explorerFilterBuildRequest as wasmExplorerFilterBuildRequest,
  explorerFilterValue as wasmExplorerFilterValue,
  explorerInstallManualAddressSave as wasmExplorerInstallManualAddressSave,
  explorerIsKaspaAddress as wasmExplorerIsKaspaAddress,
  explorerLoadKnownAddressNames as wasmExplorerLoadKnownAddressNames,
  explorerLoadSavedAddresses as wasmExplorerLoadSavedAddresses,
  explorerManualAddressValue as wasmExplorerManualAddressValue,
  explorerNormalizeAddress as wasmExplorerNormalizeAddress,
  explorerReadFilterState as wasmExplorerReadFilterState,
  explorerRefreshAddressName as wasmExplorerRefreshAddressName,
  explorerSaveAddressToDatabase as wasmExplorerSaveAddressToDatabase,
  explorerSaveManualAddress as wasmExplorerSaveManualAddress,
  explorerSetTableFontSize as wasmExplorerSetTableFontSize,
  kgwClean2SafeText as wasmKgwClean2SafeText,
  pick as wasmPick,
  toEnglishDigits as wasmToEnglishDigits,
  toNumber as wasmToNumber,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function toEnglishDigits(value) {
  return wasmToEnglishDigits(value);
}

export function pick(...values) {
  return wasmPick(values);
}

export function toNumber(value, fallback = 0) {
  return wasmToNumber(value, fallback);
}

export function kgwClean2SafeText(value) {
  return wasmKgwClean2SafeText(value);
}

export function setTableFontSize(section) {
  return wasmExplorerSetTableFontSize(section);
}

export function kgwApplyExplorerFontSize(section, rawValue) {
  return wasmExplorerApplyFontSize(section, rawValue);
}

export function kgwBindFontSpinbox(section) {
  return wasmExplorerBindFontSpinbox(section);
}

export function defaultDates(section) {
  return wasmExplorerDefaultDates(section);
}

export function kgwApplyExplorerLocalBusyControls(section, busy) {
  return wasmExplorerApplyLocalBusyControls(section, busy);
}

export function kgwEnsureExplorerFilterOptions(section) {
  return wasmExplorerEnsureFilterOptions(section);
}

export function kgwReadExplorerFilterState(section) {
  return wasmExplorerReadFilterState(section);
}

export function kgwBuildExplorerListRequest(section, address, startTs, endTs, limit = 10000) {
  return wasmExplorerBuildListRequest(section, address, startTs, endTs, limit);
}

export function kgwFilterValue(selector, section, fallback = "ALL") {
  return wasmExplorerFilterValue(selector, section, fallback);
}

export function kgwFilterBuildRequest(section, address, startTs, endTs, limit = 10000) {
  return wasmExplorerFilterBuildRequest(section, address, startTs, endTs, limit);
}

export function normalizeAddress(value) {
  return wasmExplorerNormalizeAddress(value);
}

export function isKaspaAddress(value) {
  return wasmExplorerIsKaspaAddress(value);
}

export function addressLookupKeys(value) {
  return wasmExplorerAddressLookupKeys(value);
}

export async function kgwCanonicalKaspaAddress(value) {
  return await wasmExplorerCanonicalKaspaAddress(value);
}

export async function loadKnownAddressNames() {
  return await wasmExplorerLoadKnownAddressNames();
}

export async function saveAddressToDatabase(address, name = "") {
  return await wasmExplorerSaveAddressToDatabase(address, name);
}

export async function refreshAddressName(section, address) {
  return await wasmExplorerRefreshAddressName(section, address);
}

export async function loadSavedAddresses(section) {
  return await wasmExplorerLoadSavedAddresses(section);
}

export async function fetchBalance(section, address) {
  return await wasmExplorerFetchBalance(section, address);
}

export function explorerAddressDiagnosticsSnapshot(address) {
  return wasmExplorerAddressDiagnosticsSnapshot(address);
}

export function kgwExplorerManualAddressValue(section) {
  return wasmExplorerManualAddressValue(section);
}

export function kgwExplorerIsKaspaAddress(value) {
  return wasmExplorerIsKaspaAddress(value);
}

export async function kgwExplorerSaveManualAddress(section) {
  return await wasmExplorerSaveManualAddress(section);
}

export function kgwInstallExplorerManualAddressSave() {
  return wasmExplorerInstallManualAddressSave();
}
