// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Explorer export DOM/Tauri orchestration, tracing, save/open flow, and export routing.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  explorerBuildRawExportTableV2 as wasmBuildRawExportTableV2,
  explorerExportCsv as wasmExportCsv,
  explorerExportHtml as wasmExportHtml,
  explorerExportInstall as wasmInstall,
  explorerExportPdf as wasmExportPdf,
  explorerOpenBlockExplorer as wasmOpenBlockExplorer,
  explorerRawExportAddressUrlV2 as wasmRawExportAddressUrlV2,
  explorerRawExportJoinAddressesV2 as wasmRawExportJoinAddressesV2,
  explorerRawExportNormalizeRawTxV2 as wasmRawExportNormalizeRawTxV2,
  explorerRawExportNumberV2 as wasmRawExportNumberV2,
  explorerRawExportStringV2 as wasmRawExportStringV2,
  explorerRawExportTxUrlV2 as wasmRawExportTxUrlV2,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();
wasmInstall();

export function kgwExplorerExportStringV2(value) {
  return wasmRawExportStringV2(value);
}

export function kgwExplorerExportNumberV2(value, digits = 8) {
  return wasmRawExportNumberV2(value, digits);
}

export function kgwExplorerExportTxUrlV2(txid) {
  return wasmRawExportTxUrlV2(txid);
}

export function kgwExplorerExportAddressUrlV2(address) {
  return wasmRawExportAddressUrlV2(address);
}

export function kgwExplorerExportJoinAddressesV2(...values) {
  return wasmRawExportJoinAddressesV2(values);
}

export function kgwExplorerExportNormalizeRawTxV2(row) {
  return wasmRawExportNormalizeRawTxV2(row);
}

export async function kgwExplorerBuildRawExportTableV2(section) {
  return await wasmBuildRawExportTableV2(section);
}

export function openBlockExplorer(section) {
  return wasmOpenBlockExplorer(section);
}

export function exportCsv(section = document) {
  return wasmExportCsv(section);
}

export function exportHtml(section = document) {
  return wasmExportHtml(section);
}

export function exportPdf(section = document) {
  return wasmExportPdf(section);
}
