// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  kgwClean2DayToSeconds as wasmKgwClean2DayToSeconds,
  kgwDayToEpochSeconds as wasmKgwDayToEpochSeconds,
  kgwTransactionDateKey as wasmKgwTransactionDateKey,
  kgwTxDayToEpochSeconds as wasmKgwTxDayToEpochSeconds,
  normalizeDateInputValue as wasmNormalizeDateInputValue,
  parseDateSeconds as wasmParseDateSeconds,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function normalizeDateInputValue(value) {
  return wasmNormalizeDateInputValue(value);
}

export function parseDateSeconds(dateText, endOfDay = false) {
  return wasmParseDateSeconds(dateText, endOfDay);
}

export function kgwDayToEpochSeconds(day, endOfDay = false) {
  return wasmKgwDayToEpochSeconds(day, endOfDay);
}

export function kgwTxDayToEpochSeconds(day, endOfDay = false) {
  return wasmKgwTxDayToEpochSeconds(day, endOfDay);
}

export function kgwClean2DayToSeconds(day, endOfDay = false) {
  return wasmKgwClean2DayToSeconds(day, endOfDay);
}

export function kgwTransactionDateKey(row) {
  return wasmKgwTransactionDateKey(row);
}
