// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Explorer export DOM/Tauri orchestration, tracing, save/open flow, and export routing.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  explorerExportCsv as wasmExportCsv,
  explorerExportHtml as wasmExportHtml,
  explorerExportInstall as wasmInstall,
  explorerExportPdf as wasmExportPdf,
  explorerOpenBlockExplorer as wasmOpenBlockExplorer,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();
wasmInstall();

export function openBlockExplorer(section) {
  return wasmOpenBlockExplorer(section);
}

export function exportCsv(section = document) {
  return wasmExportCsv(section);
}

export function exportHtml(section = document) {
  return wasmExportHtml(section);
}

export function exportPdf(section = document) {
  return wasmExportPdf(section);
}
