// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns frontend log buffering, fatal rendering, global error capture, and Tauri forwarding.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  shellLoggerClearBufferedLogs as wasmClearBufferedLogs,
  shellLoggerFatal as wasmKgwFatal,
  shellLoggerGetBufferedLogs as wasmGetBufferedLogs,
  shellLoggerInstall as wasmInstallShellLogger,
  shellLoggerLog as wasmKgwLog,
} from "../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function kgwLog(level, message, details = "", source = "frontend") {
  return wasmKgwLog(level, message, details, source);
}

export function createLogger(source) {
  return {
    log: (message, details = "") => kgwLog("log", message, details, source),
    warn: (message, details = "") => kgwLog("warn", message, details, source),
    error: (message, details = "") => kgwLog("error", message, details, source),
  };
}

export function kgwFatal(error, source = "shell") {
  return wasmKgwFatal(error, source);
}

export function getBufferedLogs() {
  return wasmGetBufferedLogs();
}

export function clearBufferedLogs() {
  return wasmClearBufferedLogs();
}

if (!window.__KGW_LOGGER_INSTALLED) {
  window.kgwLog = kgwLog;
  window.kgwFatal = kgwFatal;
  window.kgwCreateLogger = createLogger;
  window.kgwGetBufferedLogs = getBufferedLogs;
  window.kgwClearBufferedLogs = clearBufferedLogs;
  wasmInstallShellLogger();
}
