// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Settings V2 help metadata, rendering, DOM orchestration, accessibility, and layout behavior.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  settingsLayoutDecorateFields as wasmDecorateFields,
  settingsLayoutDecorateGlobal as wasmDecorateGlobal,
  settingsLayoutFieldKind as wasmFieldKind,
  settingsLayoutGlobalHelpIds as wasmGlobalHelpIds,
  settingsLayoutHelpI18nKeys as wasmHelpKeys,
  settingsLayoutInstall as wasmInstall,
  settingsLayoutInstallGlobal as wasmInstallGlobal,
  settingsLayoutInstallManageAddressesClean as wasmInstallManageAddressesClean,
  settingsLayoutRenderTabs as wasmRenderTabs,
  settingsLayoutRevealField as wasmRevealField,
  settingsLayoutSetFieldState as wasmSetFieldState,
} from "../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export const SETTING_HELP_I18N_KEYS = Object.freeze(wasmHelpKeys());
export const GLOBAL_SETTING_HELP_IDS = Object.freeze(Array.from(wasmGlobalHelpIds()));

export function settingFieldKind(field) {
  return wasmFieldKind(field);
}

export function renderSettingsTabs(scope, net, groups) {
  return wasmRenderTabs(scope, net, groups);
}

export function decorateSettingsFields(root) {
  return wasmDecorateFields(root);
}

export function setSettingFieldState(field, message = "") {
  return wasmSetFieldState(field, String(message || ""));
}

export function revealSettingsField(field) {
  return wasmRevealField(field);
}

export function installSettingsLayout(root) {
  return wasmInstall(root);
}

export function decorateGlobalSettings(root) {
  return wasmDecorateGlobal(root);
}

export function installGlobalSettingsLayout(root) {
  return wasmInstallGlobal(root);
}

export function installManageAddressesCleanLayout() {
  return wasmInstallManageAddressesClean();
}
