// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  applyStatusTone as wasmApplyStatusTone,
  renderStatusSummary as wasmRenderStatusSummary,
  statusTone as wasmStatusTone,
} from "../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function statusTone(state) {
  return wasmStatusTone(state);
}

export function applyStatusTone(element, state) {
  return wasmApplyStatusTone(element, state);
}

export function renderStatusSummary(element, text) {
  return wasmRenderStatusSummary(element, text);
}
