// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Kaspa Node tab rendering, settings, runtime, logs, tracing, and action orchestration.
// This module is deterministic browser/WASM ABI and compatibility glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  nodeEffectiveNodeSettings,
  nodeFinalIsolatedAdapterStartV1,
  nodeFinalIsolatedAdapterStatusV1,
  nodeFinalIsolatedAdapterStopV1,
  nodeInitKaspaNodeTab,
  nodeSuperMegaIsolatedAdapterStatusPreviewV1,
  nodeV66IsolatedAdapterStartV1,
  nodeV66IsolatedAdapterStatusV1,
  nodeV66IsolatedAdapterStopV1,
  nodeV66RuntimeFeaturePolicyV1,
  nodeV67RuntimeFeaturePolicy,
  nodeV67StartRuntime,
  nodeV67StatusRuntime,
  nodeV67StopRuntime,
  nodeValidateForm,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export async function initKaspaNodeTab(root) { return nodeInitKaspaNodeTab(root); }
export { nodeEffectiveNodeSettings as kgwNodeEffectiveNodeSettings };
export { nodeValidateForm as kgwNodeValidateForm };
export default initKaspaNodeTab;

window.initKaspaNodeTab = initKaspaNodeTab;
window.kgwSuperMegaIsolatedAdapterStatusPreviewV1 = nodeSuperMegaIsolatedAdapterStatusPreviewV1;
window.kgwFinalIsolatedAdapterStartV1 = nodeFinalIsolatedAdapterStartV1;
window.kgwFinalIsolatedAdapterStatusV1 = nodeFinalIsolatedAdapterStatusV1;
window.kgwFinalIsolatedAdapterStopV1 = nodeFinalIsolatedAdapterStopV1;
window.kgwV66RuntimeFeaturePolicyV1 = nodeV66RuntimeFeaturePolicyV1;
window.kgwV66IsolatedAdapterStartV1 = nodeV66IsolatedAdapterStartV1;
window.kgwV66IsolatedAdapterStatusV1 = nodeV66IsolatedAdapterStatusV1;
window.kgwV66IsolatedAdapterStopV1 = nodeV66IsolatedAdapterStopV1;
window.kgwV67StartRuntime = nodeV67StartRuntime;
window.kgwV67StatusRuntime = nodeV67StatusRuntime;
window.kgwV67StopRuntime = nodeV67StopRuntime;
window.kgwV67RuntimeFeaturePolicy = nodeV67RuntimeFeaturePolicy;
