// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the Analysis tab filter/init/hook/calendar/export implementation.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  analysisInitTab as wasmAnalysisInitTab,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export async function initAnalysisTab() {
  return wasmAnalysisInitTab();
}
