// ============================================================================
// KGW_FINAL_TRANSACTION_SYNC_OWNER
// This file is the single official owner of transaction fetch/list orchestration.
// Rules:
// - API pagination belongs here or in lower API crate helpers called from here.
// - DB writes/deletes for transaction sync belong here or lower DB repositories.
// - Tauri commands must only validate IPC input and delegate to this runtime.
// - Frontend code must never implement transaction API loops or DB writes.
// ============================================================================

// ============================================================================
// KGW_OWNERSHIP_RUNTIME_TRANSACTION_SYNC_OWNER
// Official owner of transaction fetch/sync orchestration.
// Owns normal fetch, forced fetch, API pagination/retry orchestration,
// persistence orchestration through repository interfaces, and progress/log events.
// No Tauri command adapter or frontend file may duplicate this ownership.
// ============================================================================

// ============================================================================
// KGW ARCHITECTURE OWNER MAP
// Generated by automated light cleanup script.
// Role: Official transaction fetch/sync orchestration owner
// Owner status: AUTHORITATIVE
//
// Rules:
// - crates/kaspa-gateway-runtime/src/transaction_sync.rs is the official owner
//   of transaction fetch/sync orchestration.
// - Tauri command files must only validate/translate IPC inputs and call the
//   runtime service. They must not duplicate pagination, DB write, or API fetch
//   loops.
// - Explorer facade files may preserve compatibility, but they must not become
//   a second fetch implementation.
// - Do not delete legacy code in this phase. Mark, route, document, then remove
//   only after parity tests pass.
// ============================================================================
use kaspa_gateway_api::transactions::{
    TransactionFetchConfig, TransactionPage, block_time_seconds, fetch_transactions_page_accepted,
    transaction_id,
};
use kaspa_gateway_core::KaspaAddress;
use kaspa_gateway_db::{TransactionFilter, TransactionRecord, TransactionsRepository};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::{BTreeMap, HashSet};
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};

const PAGE_LIMIT: usize = 500;
const MAX_PAGES: usize = 10_000;
const TX_VERBOSE_ITEM_LOGS: bool = false;
static TRANSACTION_SYNC_ACTIVE: AtomicBool = AtomicBool::new(false);

/* KGW_TRANSACTION_SYNC_BACKEND_CANCEL_R57D4
Backend-owned cancellation registry for Explorer transaction sync.
This stays inside the authoritative transaction_sync owner. */
static TRANSACTION_SYNC_CANCEL_REQUESTS: OnceLock<Mutex<HashSet<String>>> = OnceLock::new();

fn transaction_sync_cancel_requests() -> &'static Mutex<HashSet<String>> {
    TRANSACTION_SYNC_CANCEL_REQUESTS.get_or_init(|| Mutex::new(HashSet::new()))
}

pub fn request_transaction_sync_cancel(request_id: &str) -> bool {
    let trimmed = request_id.trim();

    if trimmed.is_empty() {
        return false;
    }

    let mut guard = transaction_sync_cancel_requests()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());

    guard.insert(trimmed.to_string())
}

fn transaction_sync_cancel_requested(request_id: Option<&str>) -> bool {
    let Some(request_id) = request_id else {
        return false;
    };

    let trimmed = request_id.trim();

    if trimmed.is_empty() {
        return false;
    }

    let guard = transaction_sync_cancel_requests()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());

    guard.contains(trimmed)
}

fn transaction_sync_clear_cancel_request(request_id: Option<&str>) {
    let Some(request_id) = request_id else {
        return;
    };

    let trimmed = request_id.trim();

    if trimmed.is_empty() {
        return;
    }

    let mut guard = transaction_sync_cancel_requests()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());

    guard.remove(trimmed);
}

fn transaction_sync_cancel_error(
    request_id: Option<&str>,
    address: &str,
    stage: &str,
) -> Option<String> {
    if !transaction_sync_cancel_requested(request_id) {
        return None;
    }

    eprintln!(
        "[KGW][transactions][FetchWorker][CANCELLED] address={} request_id={:?} stage={}",
        address, request_id, stage
    );

    Some(format!(
        "transaction sync cancelled address={} request_id={:?} stage={}",
        address, request_id, stage
    ))
}

struct TransactionSyncCancelGuard {
    request_id: Option<String>,
}

impl TransactionSyncCancelGuard {
    fn new(request_id: Option<String>) -> Self {
        Self { request_id }
    }
}

impl Drop for TransactionSyncCancelGuard {
    fn drop(&mut self) {
        transaction_sync_clear_cancel_request(self.request_id.as_deref());
    }
}

struct TransactionSyncGuard {
    address: String,
    mode: &'static str,
}

impl TransactionSyncGuard {
    fn enter(address: &str, force: bool) -> Result<Self, String> {
        let mode = if force { "force" } else { "normal" };

        if TRANSACTION_SYNC_ACTIVE
            .compare_exchange(false, true, Ordering::SeqCst, Ordering::SeqCst)
            .is_err()
        {
            eprintln!(
                "[KGW][transactions][FetchWorker][WARN] Fetch rejected because another fetch is already running address={} mode={}",
                address, mode
            );

            return Err(
                "Another transaction fetch is already running. Wait until it finishes.".to_string(),
            );
        }

        eprintln!(
            "[KGW][transactions][FetchWorker] Fetch lock acquired address={} mode={}",
            address, mode
        );

        Ok(Self {
            address: address.to_string(),
            mode,
        })
    }
}

impl Drop for TransactionSyncGuard {
    fn drop(&mut self) {
        TRANSACTION_SYNC_ACTIVE.store(false, Ordering::SeqCst);

        eprintln!(
            "[KGW][transactions][FetchWorker] Fetch lock released address={} mode={}",
            self.address, self.mode
        );
    }
}

/* TX_LIVE_CORE_1_PROGRESS_CALLBACK
   One generic live-update channel for normal and force fetch.
   This is not a second fetch path. It only reports pages already stored by sync_transactions.
*/
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncProgressRecord {
    pub txid: String,
    pub address: String,
    pub tx_type: String,
    pub direction: String,
    pub amount_sompi: i64,
    pub timestamp_ms: i64,
}

/* TX_SPEED_CORE_1_LIGHT_PROGRESS_DAYS
   Lightweight live progress payload.
   Do not send 500 transaction rows through Tauri IPC on every page.
   Send compact day summaries and let final SQLite refresh be authoritative.
*/
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncProgressDay {
    pub day: String,
    pub count: usize,
    pub incoming_sompi: i64,
    pub outgoing_sompi: i64,
}

fn transaction_sync_progress_days(
    records: &[TransactionRecord],
) -> Vec<TransactionSyncProgressDay> {
    let mut days = BTreeMap::<String, TransactionSyncProgressDay>::new();

    for record in records {
        let day = day_key(record.timestamp_ms);

        let entry = days
            .entry(day.clone())
            .or_insert_with(|| TransactionSyncProgressDay {
                day,
                count: 0,
                incoming_sompi: 0,
                outgoing_sompi: 0,
            });

        entry.count += 1;

        if record.direction == "outgoing" {
            entry.outgoing_sompi = entry.outgoing_sompi.saturating_add(record.amount_sompi);
        } else {
            entry.incoming_sompi = entry.incoming_sompi.saturating_add(record.amount_sompi);
        }
    }

    days.into_values().collect()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncProgress {
    pub address: String,
    pub mode: String,
    pub phase: String,
    pub page: usize,
    pub page_stored: usize,
    pub stored_total: usize,
    pub fetched_total: usize,
    pub accepted_total: usize,
    pub days: Vec<TransactionSyncProgressDay>,
    pub records: Vec<TransactionSyncProgressRecord>,
}

type TransactionSyncProgressCallback = Arc<dyn Fn(TransactionSyncProgress) + Send + Sync + 'static>;

static TRANSACTION_SYNC_PROGRESS_CALLBACK: OnceLock<
    Mutex<Option<TransactionSyncProgressCallback>>,
> = OnceLock::new();

pub fn set_transaction_sync_progress_callback(callback: Option<TransactionSyncProgressCallback>) {
    let lock = TRANSACTION_SYNC_PROGRESS_CALLBACK.get_or_init(|| Mutex::new(None));

    if let Ok(mut guard) = lock.lock() {
        *guard = callback;
    }
}

fn emit_transaction_sync_progress(progress: TransactionSyncProgress) {
    let Some(lock) = TRANSACTION_SYNC_PROGRESS_CALLBACK.get() else {
        return;
    };

    let callback = lock
        .lock()
        .ok()
        .and_then(|guard| guard.as_ref().map(Arc::clone));

    if let Some(callback) = callback {
        callback(progress);
    }
}

pub fn transaction_sync_progress_record(
    record: &TransactionRecord,
) -> TransactionSyncProgressRecord {
    TransactionSyncProgressRecord {
        txid: record.txid.clone(),
        address: record.address.clone(),
        tx_type: record.tx_type.clone(),
        direction: record.direction.clone(),
        amount_sompi: record.amount_sompi,
        timestamp_ms: record.timestamp_ms,
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncRequest {
    pub address: String,
    pub start_ts: Option<i64>,
    pub end_ts: Option<i64>,
    pub force: bool,
    pub page_limit: Option<usize>,
    pub max_pages: Option<usize>,

    #[serde(default, alias = "requestId")]
    pub request_id: Option<String>,

    #[serde(default)]
    pub tx_type: Option<String>,

    #[serde(default)]
    pub direction: Option<String>,

    #[serde(default)]
    pub search_query: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncSummary {
    pub address: String,
    pub mode: String,
    pub fetched_from_api: usize,
    pub accepted_for_range: usize,
    pub stored: usize,
    pub pages: usize,
    pub local_loaded: usize,
    pub deleted_before_fetch: i64,
    pub stopped_by_existing_txid: bool,
    pub stopped_by_start_date: bool,
    pub stop_reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionListRequest {
    pub address: String,
    pub start_ts: Option<i64>,
    pub end_ts: Option<i64>,
    pub tx_type: Option<String>,
    pub direction: Option<String>,
    pub search_query: Option<String>,
    pub limit: Option<usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionRowView {
    pub txid: String,
    pub address: String,
    pub tx_type: String,
    pub direction: String,
    pub amount_sompi: i64,
    pub amount_kas: f64,
    pub from_address: Option<String>,
    pub to_address: Option<String>,
    pub counterparty: Option<String>,
    pub block_height: Option<i64>,
    pub timestamp_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionDayGroup {
    pub day: String,
    pub collapsed: bool,
    pub count: usize,
    pub total_incoming_sompi: i64,
    pub total_outgoing_sompi: i64,
    pub transactions: Vec<TransactionRowView>,
}

pub async fn sync_transactions(
    repo: &TransactionsRepository,
    mut request: TransactionSyncRequest,
) -> Result<TransactionSyncSummary, String> {
    let parsed = KaspaAddress::parse(&request.address).map_err(|error| error.to_string())?;
    let address = parsed.as_str().to_ascii_lowercase();
    let requested_force = request.force;

    let request_id_for_cancel = request
        .request_id
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned);

    let _cancel_guard_r57d4 = TransactionSyncCancelGuard::new(request_id_for_cancel.clone());

    let _sync_guard = TransactionSyncGuard::enter(&address, request.force)?;

    if let (Some(start), Some(end)) = (request.start_ts, request.end_ts) {
        if start > end {
            return Err("start date cannot be after end date".to_string());
        }
    }

    let page_limit = request.page_limit.unwrap_or(PAGE_LIMIT).clamp(1, 500);
    let max_pages = request.max_pages.unwrap_or(MAX_PAGES).clamp(1, MAX_PAGES);

    eprintln!(
        "[KGW][transactions][FetchWorker] Fetch diagnostics start address={} mode={} start_ts={:?} end_ts={:?} page_limit={} max_pages={} tx_type={:?} direction={:?} search={:?}",
        address,
        if request.force { "force" } else { "normal" },
        request.start_ts,
        request.end_ts,
        page_limit,
        max_pages,
        request.tx_type,
        request.direction,
        request.search_query
    );

    if let Some(error) = transaction_sync_cancel_error(
        request_id_for_cancel.as_deref(),
        &address,
        "before-local-preload",
    ) {
        return Err(error);
    }

    let local_loaded = if request.force {
        0
    } else {
        let started = Instant::now();

        let rows = repo
            .count_filtered_for_address(TransactionFilter {
                address: &address,
                start_ms: request.start_ts.map(seconds_to_ms),
                end_ms: request.end_ts.map(seconds_to_ms),
                tx_type: request.tx_type.as_deref(),
                direction: request.direction.as_deref(),
                search: request.search_query.as_deref(),
                limit: None,
            })
            .map_err(|error| error.to_string())?;

        eprintln!(
            "[KGW][transactions][FetchWorker] Local DB preload done address={} rows={} elapsed_ms={}",
            address,
            rows,
            started.elapsed().as_millis()
        );

        rows
    };

    if let Some(error) = transaction_sync_cancel_error(
        request_id_for_cancel.as_deref(),
        &address,
        "before-force-delete-or-fetch",
    ) {
        return Err(error);
    }

    let deleted_before_fetch = if request.force {
        let started = Instant::now();

        eprintln!(
            "[KGW][transactions][FetchWorker] Force delete start address={}",
            address
        );

        let deleted = repo
            .delete_for_address(&address)
            .map_err(|error| error.to_string())?;

        eprintln!(
            "[KGW][transactions][FetchWorker] Force delete done address={} deleted={} elapsed_ms={}",
            address,
            deleted,
            started.elapsed().as_millis()
        );

        deleted
    } else {
        0
    };
    if requested_force {
        request.force = false;

        eprintln!(
            "[KGW][transactions][FetchWorker] Force delete completed; continuing with normal fetch loop address={}",
            address
        );
    }
    let mut existing_txids: HashSet<String> = HashSet::new();

    if request.force {
        eprintln!(
            "[KGW][transactions][FetchWorker] Existing txids preload skipped address={} mode=force",
            address
        );
    } else {
        eprintln!(
            "[KGW][transactions][FetchWorker] Existing txids preload skipped address={} mode=normal strategy=page_candidate_lookup",
            address
        );
    }

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(45))
        .build()
        .map_err(|error| format!("failed to build transaction HTTP client: {error}"))?;

    let config = TransactionFetchConfig {
        page_limit,
        max_pages,
        ..TransactionFetchConfig::default()
    };

    let mut fetched_from_api = 0usize;
    let mut accepted_for_range = 0usize;
    let mut stored = 0usize;
    let mut pages = 0usize;
    let stopped_by_existing_txid = false;
    let mut stopped_by_start_date = false;
    let mut stop_reason = "max_pages_reached".to_string();
    let mut before: i64 = 0;
    let mut after: i64 = 0;

    // KGW_TX_SPEED_2_PREFETCH_STATE:
    // Holds one already-started request for the next accepted-only cursor page.
    let mut prefetched_page: Option<tokio::task::JoinHandle<Result<TransactionPage, String>>> =
        None;
    eprintln!(
        "[KGW][transactions][FetchWorker] Accepted-only page fetch enabled address={} mode={} page_limit={} max_pages={} endpoint=full-transactions-page acceptance=accepted",
        address,
        if request.force { "force" } else { "normal" },
        page_limit,
        max_pages
    );

    if let Some(error) = transaction_sync_cancel_error(
        request_id_for_cancel.as_deref(),
        &address,
        "before-page-loop",
    ) {
        return Err(error);
    }

    'sync_page_loop: for page_num in 0..max_pages {
        let page_number = page_num + 1;
        let page_started = Instant::now();

        if let Some(error) = transaction_sync_cancel_error(
            request_id_for_cancel.as_deref(),
            &address,
            "before-page-fetch",
        ) {
            if let Some(handle) = prefetched_page.take() {
                handle.abort();
            }

            return Err(error);
        }

        eprintln!(
            "[KGW][transactions][FetchWorker] Fetch accepted page request address={} mode={} page={} before={} after={} limit={}",
            address,
            if request.force { "force" } else { "normal" },
            page_number,
            before,
            after,
            page_limit
        );

        let page = if let Some(handle) = prefetched_page.take() {
            eprintln!(
                "[KGW][transactions][FetchWorker] Await prefetched accepted page address={} mode={} page={} before={} after={}",
                address,
                if request.force { "force" } else { "normal" },
                page_number,
                before,
                after
            );

            match handle.await {
                Ok(Ok(page)) => page,
                Ok(Err(error)) => {
                    eprintln!(
                        "[KGW][transactions][FetchWorker][ERROR] Prefetched accepted page failed address={} mode={} page={} before={} after={} error={}",
                        address,
                        if request.force { "force" } else { "normal" },
                        page_number,
                        before,
                        after,
                        error
                    );

                    return Err(format!(
                        "prefetched accepted page failed address={} page={} before={} after={} error={}",
                        address, page_number, before, after, error
                    ));
                }
                Err(error) => {
                    eprintln!(
                        "[KGW][transactions][FetchWorker][ERROR] Prefetch task join failed address={} mode={} page={} before={} after={} error={}",
                        address,
                        if request.force { "force" } else { "normal" },
                        page_number,
                        before,
                        after,
                        error
                    );

                    return Err(format!(
                        "accepted page prefetch task join failed address={} page={} before={} after={} error={}",
                        address, page_number, before, after, error
                    ));
                }
            }
        } else {
            fetch_transactions_page_accepted(
                &client, &config, &address, page_limit, before, after, page_num,
            )
            .await?
        };

        pages += 1;

        let raw_count = page.transactions.len();

        if let Some(error) = transaction_sync_cancel_error(
            request_id_for_cancel.as_deref(),
            &address,
            "after-page-fetch",
        ) {
            if let Some(handle) = prefetched_page.take() {
                handle.abort();
            }

            return Err(error);
        }

        eprintln!(
            "[KGW][transactions][FetchWorker] Fetch accepted page received address={} mode={} page={} before={} after={} raw_count={} next_before={:?} next_after={:?} stored_total={} fetched_total={} elapsed_ms={}",
            address,
            if request.force { "force" } else { "normal" },
            page_number,
            before,
            after,
            raw_count,
            page.next_before,
            page.next_after,
            stored,
            fetched_from_api,
            page_started.elapsed().as_millis()
        );

        if raw_count == 0 {
            stop_reason = format!("empty_page:{page_number}");
            break 'sync_page_loop;
        }

        // KGW_TX_SPEED_2_PIPELINE_PREFETCH:
        // Start fetching the next cursor page immediately while current page is transformed/upserted.
        let mut next_prefetch: Option<tokio::task::JoinHandle<Result<TransactionPage, String>>> =
            None;

        if let Some(next_before_for_prefetch) = page.next_before {
            if next_before_for_prefetch > 0
                && next_before_for_prefetch != before
                && page_num + 1 < max_pages
            {
                let client_for_prefetch = client.clone();
                let config_for_prefetch = config.clone();
                let address_for_prefetch = address.clone();
                let next_page_num = page_num + 1;
                let next_page_number = next_page_num + 1;
                let next_after_for_prefetch = 0_i64;

                eprintln!(
                    "[KGW][transactions][FetchWorker] Prefetch accepted page start address={} mode={} next_page={} before={} after={} limit={}",
                    address,
                    if request.force { "force" } else { "normal" },
                    next_page_number,
                    next_before_for_prefetch,
                    next_after_for_prefetch,
                    page_limit
                );

                next_prefetch = Some(tokio::spawn(async move {
                    fetch_transactions_page_accepted(
                        &client_for_prefetch,
                        &config_for_prefetch,
                        &address_for_prefetch,
                        page_limit,
                        next_before_for_prefetch,
                        next_after_for_prefetch,
                        next_page_num,
                    )
                    .await
                }));
            }
        }

        if !request.force {
            let lookup_started = Instant::now();

            let candidate_txids = page
                .transactions
                .iter()
                .filter_map(transaction_id)
                .collect::<Vec<_>>();

            let page_existing_txids = repo
                .existing_txids_for_candidates(&address, &candidate_txids)
                .map_err(|error| error.to_string())?;

            let page_existing_count = page_existing_txids.len();

            existing_txids.extend(page_existing_txids);

            eprintln!(
                "[KGW][transactions][FetchWorker] Page candidate txid lookup done address={} page={} candidates={} existing={} elapsed_ms={}",
                address,
                page_number,
                candidate_txids.len(),
                page_existing_count,
                lookup_started.elapsed().as_millis()
            );
        }

        let mut accepted_timestamps = Vec::<i64>::new();
        let mut page_stored = 0usize;
        let mut page_existing_skipped = 0usize;
        let mut page_unaccepted_skipped = 0usize;
        let mut page_transform_none = 0usize;
        let page_transform_errors = 0usize;
        let page_upsert_errors = 0usize;

        let mut page_records = Vec::<TransactionRecord>::new();
        let mut page_record_timestamps = Vec::<i64>::new();

        for (idx, raw) in page.transactions.iter().enumerate() {
            if let Some(error) = transaction_sync_cancel_error(
                request_id_for_cancel.as_deref(),
                &address,
                "inside-page-transform-loop",
            ) {
                if let Some(handle) = next_prefetch.take() {
                    handle.abort();
                }

                return Err(error);
            }
            let item_no = idx + 1;
            let item_started = Instant::now();
            let txid_for_log = transaction_id(raw).unwrap_or_else(|| "<missing-txid>".to_string());

            fetched_from_api += 1;

            if TX_VERBOSE_ITEM_LOGS && (item_no == 1 || item_no % 50 == 0 || item_no == raw_count) {
                eprintln!(
                    "[KGW][transactions][FetchWorker] Tx item start address={} mode={} page={} item={}/{} txid={} stored_total={} fetched_total={}",
                    address,
                    if request.force { "force" } else { "normal" },
                    page_number,
                    item_no,
                    raw_count,
                    txid_for_log,
                    stored,
                    fetched_from_api
                );
            }

            let accepted = raw
                .get("is_accepted")
                .and_then(Value::as_bool)
                .unwrap_or(false);

            if accepted {
                accepted_timestamps.push(block_time_seconds(raw));
            } else {
                page_unaccepted_skipped += 1;

                eprintln!(
                    "[KGW][transactions][FetchWorker][WARN] Accepted-only endpoint returned unaccepted tx address={} page={} item={}/{} txid={}",
                    address, page_number, item_no, raw_count, txid_for_log
                );

                continue;
            }

            let tx_timestamp = block_time_seconds(raw);

            if request
                .end_ts
                .map(|end| tx_timestamp > end)
                .unwrap_or(false)
            {
                continue;
            }

            if let Some(txid) = transaction_id(raw) {
                if existing_txids.contains(&txid) {
                    page_existing_skipped += 1;
                    continue;
                }
            }

            let transform_started = Instant::now();

            let record = match raw_to_record_python_parity(&address, raw) {
                Ok(Some(record)) => record,
                Ok(None) => {
                    page_transform_none += 1;

                    eprintln!(
                        "[KGW][transactions][FetchWorker] Tx transform none address={} page={} item={}/{} txid={} elapsed_ms={}",
                        address,
                        page_number,
                        item_no,
                        raw_count,
                        txid_for_log,
                        transform_started.elapsed().as_millis()
                    );

                    continue;
                }
                Err(error) => {
                    eprintln!(
                        "[KGW][transactions][FetchWorker][ERROR] Tx transform failed address={} page={} item={}/{} txid={} elapsed_ms={} error={}",
                        address,
                        page_number,
                        item_no,
                        raw_count,
                        txid_for_log,
                        transform_started.elapsed().as_millis(),
                        error
                    );

                    return Err(error);
                }
            };

            page_record_timestamps.push(tx_timestamp);
            page_records.push(record);

            if TX_VERBOSE_ITEM_LOGS && (item_no == 1 || item_no % 50 == 0 || item_no == raw_count) {
                eprintln!(
                    "[KGW][transactions][FetchWorker] Tx item done address={} mode={} page={} item={}/{} txid={} item_elapsed_ms={} totals: stored={} accepted_in_range={} existing_skipped_page={} unaccepted_skipped_page={} transform_none_page={}",
                    address,
                    if request.force { "force" } else { "normal" },
                    page_number,
                    item_no,
                    raw_count,
                    txid_for_log,
                    item_started.elapsed().as_millis(),
                    stored,
                    accepted_for_range,
                    page_existing_skipped,
                    page_unaccepted_skipped,
                    page_transform_none
                );
            }
        }

        if let Some(error) = transaction_sync_cancel_error(
            request_id_for_cancel.as_deref(),
            &address,
            "before-page-upsert",
        ) {
            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }

            return Err(error);
        }

        if !page_records.is_empty() {
            let batch_started = Instant::now();

            eprintln!(
                "[KGW][transactions][FetchWorker] Page batch upsert start address={} mode={} page={} records={}",
                address,
                if request.force { "force" } else { "normal" },
                page_number,
                page_records.len()
            );

            let inserted = match catch_unwind(AssertUnwindSafe(|| repo.upsert_many(&page_records)))
            {
                Ok(Ok(inserted)) => inserted,
                Ok(Err(error)) => {
                    eprintln!(
                        "[KGW][transactions][FetchWorker][ERROR] Page batch upsert failed address={} mode={} page={} records={} elapsed_ms={} error={}",
                        address,
                        if request.force { "force" } else { "normal" },
                        page_number,
                        page_records.len(),
                        batch_started.elapsed().as_millis(),
                        error
                    );

                    return Err(format!(
                        "page batch upsert failed address={} page={} records={} error={}",
                        address,
                        page_number,
                        page_records.len(),
                        error
                    ));
                }
                Err(panic_payload) => {
                    let panic_message = if let Some(text) = panic_payload.downcast_ref::<&str>() {
                        (*text).to_string()
                    } else if let Some(text) = panic_payload.downcast_ref::<String>() {
                        text.clone()
                    } else {
                        "unknown panic payload".to_string()
                    };

                    eprintln!(
                        "[KGW][transactions][FetchWorker][PANIC] Page batch upsert panicked address={} mode={} page={} records={} elapsed_ms={} panic={}",
                        address,
                        if request.force { "force" } else { "normal" },
                        page_number,
                        page_records.len(),
                        batch_started.elapsed().as_millis(),
                        panic_message
                    );

                    return Err(format!(
                        "page batch upsert panicked address={} page={} records={} panic={}",
                        address,
                        page_number,
                        page_records.len(),
                        panic_message
                    ));
                }
            };

            stored += inserted;
            page_stored += inserted;

            for record in &page_records {
                existing_txids.insert(record.txid.clone());
            }

            for ts_seconds in page_record_timestamps.iter().copied() {
                if timestamp_in_requested_range(ts_seconds, request.start_ts, request.end_ts) {
                    accepted_for_range += 1;
                }
            }

            eprintln!(
                "[KGW][transactions][FetchWorker] Page batch upsert done address={} mode={} page={} inserted={} stored_total={} page_stored={} elapsed_ms={}",
                address,
                if request.force { "force" } else { "normal" },
                page_number,
                inserted,
                stored,
                page_stored,
                batch_started.elapsed().as_millis()
            );

            emit_transaction_sync_progress(TransactionSyncProgress {
                address: address.clone(),
                mode: if request.force { "force" } else { "normal" }.to_string(),
                phase: "page_stored".to_string(),
                page: page_number,
                page_stored,
                stored_total: stored,
                fetched_total: fetched_from_api,
                accepted_total: accepted_for_range,
                days: transaction_sync_progress_days(&page_records),
                records: Vec::new(),
            });
        }

        if let Some(error) = transaction_sync_cancel_error(
            request_id_for_cancel.as_deref(),
            &address,
            "after-page-upsert",
        ) {
            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }

            return Err(error);
        }

        if let Some(oldest_ts_on_page) = accepted_timestamps.iter().copied().min() {
            if request
                .start_ts
                .map(|start| oldest_ts_on_page < start)
                .unwrap_or(false)
            {
                stopped_by_start_date = true;
                stop_reason = format!(
                    "before_start_date:page={}:oldest_ts={}",
                    page_number, oldest_ts_on_page
                );

                eprintln!(
                    "[KGW][transactions][FetchWorker] Fetch stop by start date address={} page={} oldest_ts={} start_ts={:?}",
                    address, page_number, oldest_ts_on_page, request.start_ts
                );

                break 'sync_page_loop;
            }
        }

        eprintln!(
            "[KGW][transactions][FetchWorker] Fetch accepted page complete address={} mode={} page={} raw_count={} page_stored={} stored_total={} fetched_total={} accepted_in_range_total={} existing_skipped_page={} unaccepted_skipped_page={} transform_none_page={} transform_errors_page={} upsert_errors_page={} oldest_ts={:?} next_before={:?} next_after={:?} elapsed_ms={}",
            address,
            if request.force { "force" } else { "normal" },
            page_number,
            raw_count,
            page_stored,
            stored,
            fetched_from_api,
            accepted_for_range,
            page_existing_skipped,
            page_unaccepted_skipped,
            page_transform_none,
            page_transform_errors,
            page_upsert_errors,
            accepted_timestamps.iter().copied().min(),
            page.next_before,
            page.next_after,
            page_started.elapsed().as_millis()
        );

        // KGW_TX_DB_FAST_STOP_ALL_EXISTING_NORMAL:
        // In normal fetch, if the accepted-only page contains no new records and every item
        // already exists locally, stop scanning external pages. SQLite already has the data.
        if !request.force && raw_count > 0 && page_stored == 0 && page_existing_skipped == raw_count
        {
            stop_reason = format!("all_existing_page:{page_number}");

            eprintln!(
                "[KGW][transactions][FetchWorker] Normal fetch stop: all transactions on page already exist address={} page={} raw_count={} existing_skipped={} fetched_total={} stored_total={}",
                address, page_number, raw_count, page_existing_skipped, fetched_from_api, stored
            );

            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }

            break 'sync_page_loop;
        }
        if let Some(error) = transaction_sync_cancel_error(
            request_id_for_cancel.as_deref(),
            &address,
            "before-next-page",
        ) {
            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }

            return Err(error);
        }

        if let Some(next_before) = page.next_before {
            if next_before <= 0 {
                stop_reason = format!("invalid_next_before:{page_number}:{next_before}");
                if let Some(handle) = next_prefetch.take() {
                    handle.abort();
                }
                break 'sync_page_loop;
            }

            if next_before == before {
                stop_reason = format!("duplicate_next_before:{page_number}:{next_before}");
                if let Some(handle) = next_prefetch.take() {
                    handle.abort();
                }
                break 'sync_page_loop;
            }

            // Backward pagination to older transactions uses X-Next-Page-Before only.
            // X-Next-Page-After is for the opposite/newer direction and can create
            // an invalid window where before < after.
            before = next_before;
            after = 0;
            prefetched_page = next_prefetch.take();
        } else {
            stop_reason = format!("no_next_page_header:{page_number}");
            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }
            break 'sync_page_loop;
        }
    }
    eprintln!(
        "[KGW][transactions][FetchWorker] Fetch diagnostics done address={} mode={} fetched={} stored={} accepted_in_range={} pages={} local_loaded={} deleted={} stop_reason={}",
        address,
        if request.force { "force" } else { "normal" },
        fetched_from_api,
        stored,
        accepted_for_range,
        pages,
        local_loaded,
        deleted_before_fetch,
        stop_reason
    );

    Ok(TransactionSyncSummary {
        address,
        mode: if requested_force { "force" } else { "normal" }.to_string(),
        fetched_from_api,
        accepted_for_range,
        stored,
        pages,
        local_loaded,
        deleted_before_fetch,
        stopped_by_existing_txid,
        stopped_by_start_date,
        stop_reason,
    })
}

pub fn list_transactions_grouped_by_day(
    repo: &TransactionsRepository,
    request: TransactionListRequest,
) -> Result<Vec<TransactionDayGroup>, String> {
    let parsed = KaspaAddress::parse(&request.address).map_err(|error| error.to_string())?;
    let address = parsed.as_str().to_ascii_lowercase();

    if let (Some(start), Some(end)) = (request.start_ts, request.end_ts) {
        if start > end {
            return Err("start date cannot be after end date".to_string());
        }
    }

    let records = repo
        .filter_for_address(TransactionFilter {
            address: &address,
            start_ms: request.start_ts.map(seconds_to_ms),
            end_ms: request.end_ts.map(seconds_to_ms),
            tx_type: request.tx_type.as_deref(),
            direction: request.direction.as_deref(),
            search: request.search_query.as_deref(),
            limit: request.limit.or(Some(1_000_000)),
        })
        .map_err(|error| error.to_string())?;

    Ok(group_records(records))
}

fn raw_to_record_python_parity(
    address: &str,
    raw: &Value,
) -> Result<Option<TransactionRecord>, String> {
    if !raw
        .get("is_accepted")
        .and_then(Value::as_bool)
        .unwrap_or(false)
    {
        return Ok(None);
    }

    let Some(txid) = transaction_id(raw) else {
        return Ok(None);
    };

    let inputs = raw.get("inputs").and_then(Value::as_array);
    let outputs = raw.get("outputs").and_then(Value::as_array);

    let is_coinbase = inputs.map(|values| values.is_empty()).unwrap_or(true);

    let mut from_addresses = Vec::<String>::new();
    let mut to_addresses = Vec::<String>::new();
    let mut total_in = 0i64;
    let mut total_out = 0i64;

    if let Some(items) = inputs {
        for input in items {
            let from = input
                .get("previous_outpoint_address")
                .or_else(|| input.get("address"))
                .and_then(Value::as_str)
                .unwrap_or("N/A")
                .to_string();

            push_unique_case_insensitive(&mut from_addresses, from.clone());

            if from.eq_ignore_ascii_case(address) {
                total_out = total_out.saturating_add(value_to_i64(
                    input
                        .get("previous_outpoint_amount")
                        .or_else(|| input.get("amount")),
                ));
            }
        }
    }

    if let Some(items) = outputs {
        for output in items {
            let to = output
                .get("script_public_key_address")
                .or_else(|| output.get("address"))
                .and_then(Value::as_str)
                .unwrap_or("N/A")
                .to_string();

            push_unique_case_insensitive(&mut to_addresses, to.clone());

            if to.eq_ignore_ascii_case(address) {
                total_in = total_in.saturating_add(value_to_i64(output.get("amount")));
            }
        }
    }

    let is_sender = from_addresses
        .iter()
        .any(|candidate| candidate.eq_ignore_ascii_case(address));

    let is_recipient = to_addresses
        .iter()
        .any(|candidate| candidate.eq_ignore_ascii_case(address));

    let direction = if is_coinbase || (is_recipient && !is_sender) {
        "incoming"
    } else {
        "outgoing"
    };

    let tx_type = if is_coinbase { "coinbase" } else { "transfer" };
    let amount_sompi = total_in.saturating_sub(total_out).abs();

    let from_text = if from_addresses.is_empty() {
        "N/A (Coinbase)".to_string()
    } else {
        from_addresses.join(", ")
    };

    let to_text = if to_addresses.is_empty() {
        "N/A".to_string()
    } else {
        to_addresses.join(", ")
    };

    let counterparty = if direction == "incoming" {
        from_text.clone()
    } else {
        to_text.clone()
    };

    let timestamp_ms = seconds_to_ms(block_time_seconds(raw));

    let block_height = value_to_i64(
        raw.get("accepting_block_blue_score")
            .or_else(|| raw.get("block_height")),
    );

    let mut record =
        TransactionRecord::new(txid, address.to_string(), tx_type, direction, amount_sompi)
            .map_err(|error| error.to_string())?
            .with_parties(Some(from_text), Some(to_text))
            .with_counterparty(counterparty)
            .with_timestamp_ms(timestamp_ms);

    if block_height >= 0 {
        record = record.with_block_height(block_height);
    }

    record.raw_json = Some(raw.to_string());

    Ok(Some(record))
}

fn group_records(records: Vec<TransactionRecord>) -> Vec<TransactionDayGroup> {
    let mut grouped = BTreeMap::<String, Vec<TransactionRecord>>::new();

    for record in records {
        grouped
            .entry(day_key(record.timestamp_ms))
            .or_default()
            .push(record);
    }

    let mut groups = grouped
        .into_iter()
        .map(|(day, mut records)| {
            records.sort_by_key(|record| std::cmp::Reverse(record.timestamp_ms));

            let mut total_incoming_sompi = 0i64;
            let mut total_outgoing_sompi = 0i64;

            let transactions = records
                .into_iter()
                .map(|record| {
                    if record.direction == "incoming" {
                        total_incoming_sompi =
                            total_incoming_sompi.saturating_add(record.amount_sompi);
                    } else if record.direction == "outgoing" {
                        total_outgoing_sompi =
                            total_outgoing_sompi.saturating_add(record.amount_sompi);
                    }

                    TransactionRowView {
                        amount_kas: record.amount_kas(),
                        txid: record.txid,
                        address: record.address,
                        tx_type: record.tx_type,
                        direction: record.direction,
                        amount_sompi: record.amount_sompi,
                        from_address: record.from_address,
                        to_address: record.to_address,
                        counterparty: record.counterparty,
                        block_height: record.block_height,
                        timestamp_ms: record.timestamp_ms,
                    }
                })
                .collect::<Vec<_>>();

            TransactionDayGroup {
                day,
                collapsed: true,
                count: transactions.len(),
                total_incoming_sompi,
                total_outgoing_sompi,
                transactions,
            }
        })
        .collect::<Vec<_>>();

    groups.sort_by(|left, right| right.day.cmp(&left.day));
    groups
}

fn timestamp_in_requested_range(ts_seconds: i64, start: Option<i64>, end: Option<i64>) -> bool {
    if start.map(|value| ts_seconds < value).unwrap_or(false) {
        return false;
    }

    if end.map(|value| ts_seconds > value).unwrap_or(false) {
        return false;
    }

    true
}

fn push_unique_case_insensitive(values: &mut Vec<String>, value: String) {
    if !values
        .iter()
        .any(|existing| existing.eq_ignore_ascii_case(&value))
    {
        values.push(value);
    }
}

fn value_to_i64(value: Option<&Value>) -> i64 {
    match value {
        Some(Value::Number(number)) => number.as_i64().unwrap_or_default(),
        Some(Value::String(text)) => text.parse::<i64>().unwrap_or_default(),
        _ => 0,
    }
}

fn seconds_to_ms(value: i64) -> i64 {
    value.saturating_mul(1000)
}
fn day_key(timestamp_ms: i64) -> String {
    let seconds = timestamp_ms.div_euclid(1000);
    let days = seconds.div_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    format!("{year:04}-{month:02}-{day:02}")
}

fn civil_from_days(days: i64) -> (i64, i64, i64) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = mp + if mp < 10 { 3 } else { -9 };
    let year = y + if m <= 2 { 1 } else { 0 };
    (year, m, d)
}
