// ============================================================================
// KGW_FINAL_TRANSACTION_SYNC_OWNER
// This file is the single official owner of transaction fetch/list orchestration.
// Rules:
// - API pagination belongs here or in lower API crate helpers called from here.
// - DB writes/deletes for transaction sync belong here or lower DB repositories.
// - Tauri commands must only validate IPC input and delegate to this runtime.
// - Frontend code must never implement transaction API loops or DB writes.
// ============================================================================

// ============================================================================
// KGW_OWNERSHIP_RUNTIME_TRANSACTION_SYNC_OWNER
// Official owner of transaction fetch/sync orchestration.
// Owns normal fetch, forced fetch, API pagination/retry orchestration,
// persistence orchestration through repository interfaces, and progress/log events.
// No Tauri command adapter or frontend file may duplicate this ownership.
// ============================================================================

// ============================================================================
// KGW ARCHITECTURE OWNER MAP
// Generated by automated light cleanup script.
// Role: Official transaction fetch/sync orchestration owner
// Owner status: AUTHORITATIVE
//
// Rules:
// - crates/kaspa-gateway-runtime/src/transaction_sync.rs is the official owner
//   of transaction fetch/sync orchestration.
// - Tauri command files must only validate/translate IPC inputs and call the
//   runtime service. They must not duplicate pagination, DB write, or API fetch
//   loops.
// - Explorer facade files may preserve compatibility, but they must not become
//   a second fetch implementation.
// - Do not delete legacy code in this phase. Mark, route, document, then remove
//   only after parity tests pass.
// ============================================================================
use kaspa_gateway_api::transactions::{
    TransactionFetchConfig, TransactionPage, block_time_seconds, fetch_transactions_page_accepted,
    transaction_id,
};
use kaspa_gateway_core::KaspaAddress;
use kaspa_gateway_db::{TransactionFilter, TransactionRecord, TransactionsRepository};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::{BTreeMap, HashMap, HashSet};
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};
use tokio_util::sync::CancellationToken;

const PAGE_LIMIT: usize = 500;
const MAX_PAGES: usize = 10_000;
const TX_VERBOSE_ITEM_LOGS: bool = false;

// Progress emission is currently a single process-wide callback, so concurrency
// remains deliberately bounded to one active Explorer sync. Ownership is still
// request/address aware, making cancellation exact and preventing a global
// AtomicBool from becoming the task model.
const MAX_CONCURRENT_TRANSACTION_SYNCS: usize = 1;

#[derive(Clone)]
struct TransactionSyncTaskEntry {
    address: String,
    token: CancellationToken,
}

static TRANSACTION_SYNC_TASKS: OnceLock<Mutex<HashMap<String, TransactionSyncTaskEntry>>> =
    OnceLock::new();

fn transaction_sync_tasks() -> &'static Mutex<HashMap<String, TransactionSyncTaskEntry>> {
    TRANSACTION_SYNC_TASKS.get_or_init(|| Mutex::new(HashMap::new()))
}

pub fn request_transaction_sync_cancel(request_id: &str) -> bool {
    let trimmed = request_id.trim();

    if trimmed.is_empty() {
        return false;
    }

    let token = transaction_sync_tasks()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
        .get(trimmed)
        .map(|entry| entry.token.clone());

    if let Some(token) = token {
        token.cancel();
        true
    } else {
        false
    }
}

fn transaction_sync_cancel_error(
    token: &CancellationToken,
    request_id: &str,
    address: &str,
    stage: &str,
) -> Option<String> {
    if !token.is_cancelled() {
        return None;
    }

    eprintln!(
        "[KGW][transactions][FetchWorker][CANCELLED] address={} request_id={} stage={}",
        address, request_id, stage
    );

    Some(format!(
        "transaction sync cancelled address={} request_id={} stage={}",
        address, request_id, stage
    ))
}

struct TransactionSyncGuard {
    request_id: String,
    address: String,
    mode: &'static str,
    token: CancellationToken,
}

impl TransactionSyncGuard {
    fn enter(address: &str, request_id: Option<&str>, force: bool) -> Result<Self, String> {
        let mode = if force { "force" } else { "normal" };
        let request_id = request_id
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(ToOwned::to_owned)
            .unwrap_or_else(|| format!("legacy:{address}"));
        let token = CancellationToken::new();

        let mut tasks = transaction_sync_tasks()
            .lock()
            .map_err(|_| "transaction sync task registry lock poisoned".to_string())?;

        if tasks.contains_key(&request_id) {
            return Err(format!(
                "transaction sync request is already running request_id={request_id}"
            ));
        }

        if tasks
            .values()
            .any(|entry| entry.address.eq_ignore_ascii_case(address))
        {
            return Err(format!(
                "transaction sync is already running for address={address}"
            ));
        }

        if tasks.len() >= MAX_CONCURRENT_TRANSACTION_SYNCS {
            return Err(
                "Another transaction fetch is already running. Wait until it finishes.".to_string(),
            );
        }

        tasks.insert(
            request_id.clone(),
            TransactionSyncTaskEntry {
                address: address.to_string(),
                token: token.clone(),
            },
        );
        drop(tasks);

        eprintln!(
            "[KGW][transactions][FetchWorker] Task registered address={} request_id={} mode={}",
            address, request_id, mode
        );

        Ok(Self {
            request_id,
            address: address.to_string(),
            mode,
            token,
        })
    }

    fn cancellation_token(&self) -> CancellationToken {
        self.token.clone()
    }

    fn request_id(&self) -> &str {
        &self.request_id
    }
}

impl Drop for TransactionSyncGuard {
    fn drop(&mut self) {
        if let Ok(mut tasks) = transaction_sync_tasks().lock() {
            tasks.remove(&self.request_id);
        }

        eprintln!(
            "[KGW][transactions][FetchWorker] Task released address={} request_id={} mode={}",
            self.address, self.request_id, self.mode
        );
    }
}

struct ForceRefreshStageGuard<'a> {
    repo: &'a TransactionsRepository,
    address: String,
    active: bool,
}

impl<'a> ForceRefreshStageGuard<'a> {
    fn begin(repo: &'a TransactionsRepository, address: &str) -> Result<Self, String> {
        repo.begin_force_refresh_stage(address)
            .map_err(|error| error.to_string())?;

        Ok(Self {
            repo,
            address: address.to_string(),
            active: true,
        })
    }

    fn promote(&mut self) -> Result<usize, String> {
        let promoted = self
            .repo
            .promote_force_refresh(&self.address)
            .map_err(|error| error.to_string())?;
        self.active = false;
        Ok(promoted)
    }
}

impl Drop for ForceRefreshStageGuard<'_> {
    fn drop(&mut self) {
        if self.active {
            let _ = self.repo.discard_force_refresh_stage(&self.address);
        }
    }
}

/* TX_LIVE_CORE_1_PROGRESS_CALLBACK
   One generic live-update channel for normal and force fetch.
   This is not a second fetch path. It only reports pages already stored by sync_transactions.
*/
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncProgressRecord {
    pub txid: String,
    pub address: String,
    pub tx_type: String,
    pub direction: String,
    pub amount_sompi: i64,
    pub timestamp_ms: i64,
}

/* TX_SPEED_CORE_1_LIGHT_PROGRESS_DAYS
   Lightweight live progress payload.
   Do not send 500 transaction rows through Tauri IPC on every page.
   Send compact day summaries and let final SQLite refresh be authoritative.
*/
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncProgressDay {
    pub day: String,
    pub count: usize,
    pub incoming_sompi: i64,
    pub outgoing_sompi: i64,
}

fn transaction_sync_progress_days(
    records: &[TransactionRecord],
) -> Vec<TransactionSyncProgressDay> {
    let mut days = BTreeMap::<String, TransactionSyncProgressDay>::new();

    for record in records {
        let day = day_key(record.timestamp_ms);

        let entry = days
            .entry(day.clone())
            .or_insert_with(|| TransactionSyncProgressDay {
                day,
                count: 0,
                incoming_sompi: 0,
                outgoing_sompi: 0,
            });

        entry.count += 1;

        if record.direction == "outgoing" {
            entry.outgoing_sompi = entry.outgoing_sompi.saturating_add(record.amount_sompi);
        } else {
            entry.incoming_sompi = entry.incoming_sompi.saturating_add(record.amount_sompi);
        }
    }

    days.into_values().collect()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncProgress {
    pub address: String,
    pub mode: String,
    pub phase: String,
    pub page: usize,
    pub page_stored: usize,
    pub stored_total: usize,
    pub fetched_total: usize,
    pub accepted_total: usize,
    pub days: Vec<TransactionSyncProgressDay>,
    pub records: Vec<TransactionSyncProgressRecord>,
}

type TransactionSyncProgressCallback = Arc<dyn Fn(TransactionSyncProgress) + Send + Sync + 'static>;

static TRANSACTION_SYNC_PROGRESS_CALLBACK: OnceLock<
    Mutex<Option<TransactionSyncProgressCallback>>,
> = OnceLock::new();

pub fn set_transaction_sync_progress_callback(callback: Option<TransactionSyncProgressCallback>) {
    let lock = TRANSACTION_SYNC_PROGRESS_CALLBACK.get_or_init(|| Mutex::new(None));

    if let Ok(mut guard) = lock.lock() {
        *guard = callback;
    }
}

fn emit_transaction_sync_progress(progress: TransactionSyncProgress) {
    let Some(lock) = TRANSACTION_SYNC_PROGRESS_CALLBACK.get() else {
        return;
    };

    let callback = lock
        .lock()
        .ok()
        .and_then(|guard| guard.as_ref().map(Arc::clone));

    if let Some(callback) = callback {
        callback(progress);
    }
}

pub fn transaction_sync_progress_record(
    record: &TransactionRecord,
) -> TransactionSyncProgressRecord {
    TransactionSyncProgressRecord {
        txid: record.txid.clone(),
        address: record.address.clone(),
        tx_type: record.tx_type.clone(),
        direction: record.direction.clone(),
        amount_sompi: record.amount_sompi,
        timestamp_ms: record.timestamp_ms,
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncRequest {
    pub address: String,
    pub start_ts: Option<i64>,
    pub end_ts: Option<i64>,
    pub force: bool,
    pub page_limit: Option<usize>,
    pub max_pages: Option<usize>,

    #[serde(default, alias = "requestId")]
    pub request_id: Option<String>,

    #[serde(default)]
    pub tx_type: Option<String>,

    #[serde(default)]
    pub direction: Option<String>,

    #[serde(default)]
    pub search_query: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionSyncSummary {
    pub address: String,
    pub mode: String,
    pub fetched_from_api: usize,
    pub accepted_for_range: usize,
    pub stored: usize,
    pub pages: usize,
    pub local_loaded: usize,
    pub deleted_before_fetch: i64,
    pub stopped_by_existing_txid: bool,
    pub stopped_by_start_date: bool,
    pub stop_reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionListRequest {
    pub address: String,
    pub start_ts: Option<i64>,
    pub end_ts: Option<i64>,
    pub tx_type: Option<String>,
    pub direction: Option<String>,
    pub search_query: Option<String>,
    pub limit: Option<usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionRowView {
    pub txid: String,
    pub address: String,
    pub tx_type: String,
    pub direction: String,
    pub amount_sompi: i64,
    pub amount_kas: f64,
    pub from_address: Option<String>,
    pub to_address: Option<String>,
    pub counterparty: Option<String>,
    pub block_height: Option<i64>,
    pub timestamp_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionDayGroup {
    pub day: String,
    pub collapsed: bool,
    pub count: usize,
    pub total_incoming_sompi: i64,
    pub total_outgoing_sompi: i64,
    pub transactions: Vec<TransactionRowView>,
}

pub async fn sync_transactions(
    repo: &TransactionsRepository,
    request: TransactionSyncRequest,
) -> Result<TransactionSyncSummary, String> {
    sync_transactions_with_config(repo, request, TransactionFetchConfig::default()).await
}

async fn sync_transactions_with_config(
    repo: &TransactionsRepository,
    mut request: TransactionSyncRequest,
    mut fetch_config: TransactionFetchConfig,
) -> Result<TransactionSyncSummary, String> {
    let parsed = KaspaAddress::parse(&request.address).map_err(|error| error.to_string())?;
    let address = parsed.as_str().to_ascii_lowercase();
    let requested_force = request.force;

    let sync_guard =
        TransactionSyncGuard::enter(&address, request.request_id.as_deref(), requested_force)?;
    let cancellation_token = sync_guard.cancellation_token();
    let request_id_for_cancel = sync_guard.request_id().to_owned();

    if !requested_force
        && let (Some(start), Some(end)) = (request.start_ts, request.end_ts)
        && start > end
    {
        return Err("start date cannot be after end date".to_string());
    }

    // Force Refresh is a complete address refresh. Display filters remain a
    // frontend/local-query concern and must never replace complete known-good
    // history with a filtered subset.
    if requested_force {
        request.start_ts = None;
        request.end_ts = None;
        request.tx_type = None;
        request.direction = None;
        request.search_query = None;
    }

    let page_limit = request.page_limit.unwrap_or(PAGE_LIMIT).clamp(1, 500);
    let max_pages = request.max_pages.unwrap_or(MAX_PAGES).clamp(1, MAX_PAGES);

    eprintln!(
        "[KGW][transactions][FetchWorker] Fetch diagnostics start address={} request_id={} mode={} start_ts={:?} end_ts={:?} page_limit={} max_pages={} tx_type={:?} direction={:?} search={:?}",
        address,
        request_id_for_cancel,
        if request.force { "force" } else { "normal" },
        request.start_ts,
        request.end_ts,
        page_limit,
        max_pages,
        request.tx_type,
        request.direction,
        request.search_query
    );

    if let Some(error) = transaction_sync_cancel_error(
        &cancellation_token,
        &request_id_for_cancel,
        &address,
        "before-local-preload",
    ) {
        return Err(error);
    }

    let local_loaded = if requested_force {
        usize::try_from(
            repo.count_for_address(&address)
                .map_err(|error| error.to_string())?
                .max(0),
        )
        .unwrap_or(usize::MAX)
    } else {
        let started = Instant::now();

        let rows = repo
            .count_filtered_for_address(TransactionFilter {
                address: &address,
                start_ms: request.start_ts.map(seconds_to_ms),
                end_ms: request.end_ts.map(seconds_to_ms),
                tx_type: request.tx_type.as_deref(),
                direction: request.direction.as_deref(),
                search: request.search_query.as_deref(),
                limit: None,
            })
            .map_err(|error| error.to_string())?;

        eprintln!(
            "[KGW][transactions][FetchWorker] Local DB preload done address={} rows={} elapsed_ms={}",
            address,
            rows,
            started.elapsed().as_millis()
        );

        rows
    };

    if let Some(error) = transaction_sync_cancel_error(
        &cancellation_token,
        &request_id_for_cancel,
        &address,
        "before-force-stage-or-fetch",
    ) {
        return Err(error);
    }

    let mut force_refresh_stage = if requested_force {
        eprintln!(
            "[KGW][transactions][FetchWorker] Force refresh staging started address={} known_good_rows={}",
            address, local_loaded
        );
        Some(ForceRefreshStageGuard::begin(repo, &address)?)
    } else {
        None
    };

    // Kept for backward-compatible response shape. Force Refresh no longer
    // deletes anything before fetch; replacement occurs only on atomic promote.
    let deleted_before_fetch = 0_i64;
    let mut existing_txids: HashSet<String> = HashSet::new();

    if request.force {
        eprintln!(
            "[KGW][transactions][FetchWorker] Existing txids preload skipped address={} mode=force",
            address
        );
    } else {
        eprintln!(
            "[KGW][transactions][FetchWorker] Existing txids preload skipped address={} mode=normal strategy=page_candidate_lookup",
            address
        );
    }

    let client = reqwest::Client::builder()
        .connect_timeout(Duration::from_secs(5))
        .timeout(Duration::from_secs(20))
        .build()
        .map_err(|error| format!("failed to build transaction HTTP client: {error}"))?;

    fetch_config.page_limit = page_limit;
    fetch_config.max_pages = max_pages;
    let config = fetch_config;

    let mut fetched_from_api = 0usize;
    let mut accepted_for_range = 0usize;
    let mut stored = 0usize;
    let mut pages = 0usize;
    let stopped_by_existing_txid = false;
    let mut stopped_by_start_date = false;
    let mut stop_reason = "max_pages_reached".to_string();
    let mut before: i64 = 0;
    let mut after: i64 = 0;
    let mut seen_before_cursors = HashSet::<i64>::new();
    seen_before_cursors.insert(before);

    // KGW_TX_SPEED_2_PREFETCH_STATE:
    // Holds one already-started request for the next accepted-only cursor page.
    let mut prefetched_page: Option<tokio::task::JoinHandle<Result<TransactionPage, String>>> =
        None;
    eprintln!(
        "[KGW][transactions][FetchWorker] Accepted-only page fetch enabled address={} mode={} page_limit={} max_pages={} endpoint=full-transactions-page acceptance=accepted",
        address,
        if request.force { "force" } else { "normal" },
        page_limit,
        max_pages
    );

    if let Some(error) = transaction_sync_cancel_error(
        &cancellation_token,
        &request_id_for_cancel,
        &address,
        "before-page-loop",
    ) {
        return Err(error);
    }

    'sync_page_loop: for page_num in 0..max_pages {
        let page_number = page_num + 1;
        let page_started = Instant::now();

        if let Some(error) = transaction_sync_cancel_error(
            &cancellation_token,
            &request_id_for_cancel,
            &address,
            "before-page-fetch",
        ) {
            if let Some(handle) = prefetched_page.take() {
                handle.abort();
            }

            return Err(error);
        }

        eprintln!(
            "[KGW][transactions][FetchWorker] Fetch accepted page request address={} mode={} page={} before={} after={} limit={}",
            address,
            if request.force { "force" } else { "normal" },
            page_number,
            before,
            after,
            page_limit
        );

        let page = if let Some(mut handle) = prefetched_page.take() {
            eprintln!(
                "[KGW][transactions][FetchWorker] Await prefetched accepted page address={} mode={} page={} before={} after={}",
                address,
                if request.force { "force" } else { "normal" },
                page_number,
                before,
                after
            );

            let result = tokio::select! {
                _ = cancellation_token.cancelled() => {
                    handle.abort();
                    return Err(format!(
                        "transaction sync cancelled address={} request_id={} stage=await-prefetched-page",
                        address, request_id_for_cancel
                    ));
                }
                result = &mut handle => result,
            };

            match result {
                Ok(Ok(page)) => page,
                Ok(Err(error)) => {
                    eprintln!(
                        "[KGW][transactions][FetchWorker][ERROR] Prefetched accepted page failed address={} mode={} page={} before={} after={} error={}",
                        address,
                        if request.force { "force" } else { "normal" },
                        page_number,
                        before,
                        after,
                        error
                    );

                    return Err(format!(
                        "prefetched accepted page failed address={} page={} before={} after={} error={}",
                        address, page_number, before, after, error
                    ));
                }
                Err(error) => {
                    eprintln!(
                        "[KGW][transactions][FetchWorker][ERROR] Prefetch task join failed address={} mode={} page={} before={} after={} error={}",
                        address,
                        if request.force { "force" } else { "normal" },
                        page_number,
                        before,
                        after,
                        error
                    );

                    return Err(format!(
                        "accepted page prefetch task join failed address={} page={} before={} after={} error={}",
                        address, page_number, before, after, error
                    ));
                }
            }
        } else {
            tokio::select! {
                _ = cancellation_token.cancelled() => {
                    return Err(format!(
                        "transaction sync cancelled address={} request_id={} stage=await-page-fetch",
                        address, request_id_for_cancel
                    ));
                }
                result = fetch_transactions_page_accepted(
                    &client, &config, &address, page_limit, before, after, page_num,
                ) => result?,
            }
        };

        pages += 1;

        let raw_count = page.transactions.len();

        if let Some(error) = transaction_sync_cancel_error(
            &cancellation_token,
            &request_id_for_cancel,
            &address,
            "after-page-fetch",
        ) {
            if let Some(handle) = prefetched_page.take() {
                handle.abort();
            }

            return Err(error);
        }

        eprintln!(
            "[KGW][transactions][FetchWorker] Fetch accepted page received address={} mode={} page={} before={} after={} raw_count={} next_before={:?} next_after={:?} stored_total={} fetched_total={} elapsed_ms={}",
            address,
            if request.force { "force" } else { "normal" },
            page_number,
            before,
            after,
            raw_count,
            page.next_before,
            page.next_after,
            stored,
            fetched_from_api,
            page_started.elapsed().as_millis()
        );

        if raw_count == 0 {
            stop_reason = format!("empty_page:{page_number}");
            break 'sync_page_loop;
        }

        // KGW_TX_SPEED_2_PIPELINE_PREFETCH:
        // Start fetching the next cursor page immediately while current page is transformed/upserted.
        let mut next_prefetch: Option<tokio::task::JoinHandle<Result<TransactionPage, String>>> =
            None;

        if let Some(next_before_for_prefetch) = page.next_before
            && next_before_for_prefetch > 0
            && next_before_for_prefetch != before
            && page_num + 1 < max_pages
        {
            let client_for_prefetch = client.clone();
            let config_for_prefetch = config.clone();
            let address_for_prefetch = address.clone();
            let cancellation_for_prefetch = cancellation_token.clone();
            let request_id_for_prefetch = request_id_for_cancel.clone();
            let next_page_num = page_num + 1;
            let next_page_number = next_page_num + 1;
            let next_after_for_prefetch = 0_i64;

            eprintln!(
                "[KGW][transactions][FetchWorker] Prefetch accepted page start address={} mode={} next_page={} before={} after={} limit={}",
                address,
                if request.force { "force" } else { "normal" },
                next_page_number,
                next_before_for_prefetch,
                next_after_for_prefetch,
                page_limit
            );

            next_prefetch = Some(tokio::spawn(async move {
                tokio::select! {
                    _ = cancellation_for_prefetch.cancelled() => Err(format!(
                        "transaction sync cancelled address={} request_id={} stage=prefetch",
                        address_for_prefetch, request_id_for_prefetch
                    )),
                    result = fetch_transactions_page_accepted(
                        &client_for_prefetch,
                        &config_for_prefetch,
                        &address_for_prefetch,
                        page_limit,
                        next_before_for_prefetch,
                        next_after_for_prefetch,
                        next_page_num,
                    ) => result,
                }
            }));
        }

        if !request.force {
            let lookup_started = Instant::now();

            let candidate_txids = page
                .transactions
                .iter()
                .filter_map(transaction_id)
                .collect::<Vec<_>>();

            let page_existing_txids = repo
                .existing_txids_for_candidates(&address, &candidate_txids)
                .map_err(|error| error.to_string())?;

            let page_existing_count = page_existing_txids.len();

            existing_txids.extend(page_existing_txids);

            eprintln!(
                "[KGW][transactions][FetchWorker] Page candidate txid lookup done address={} page={} candidates={} existing={} elapsed_ms={}",
                address,
                page_number,
                candidate_txids.len(),
                page_existing_count,
                lookup_started.elapsed().as_millis()
            );
        }

        let mut accepted_timestamps = Vec::<i64>::new();
        let mut page_stored = 0usize;
        let mut page_existing_skipped = 0usize;
        let mut page_unaccepted_skipped = 0usize;
        let mut page_transform_none = 0usize;
        let page_transform_errors = 0usize;
        let page_upsert_errors = 0usize;

        let mut page_records = Vec::<TransactionRecord>::new();
        let mut page_record_timestamps = Vec::<i64>::new();

        for (idx, raw) in page.transactions.iter().enumerate() {
            if let Some(error) = transaction_sync_cancel_error(
                &cancellation_token,
                &request_id_for_cancel,
                &address,
                "inside-page-transform-loop",
            ) {
                if let Some(handle) = next_prefetch.take() {
                    handle.abort();
                }

                return Err(error);
            }
            let item_no = idx + 1;
            let item_started = Instant::now();
            let txid_for_log = transaction_id(raw).unwrap_or_else(|| "<missing-txid>".to_string());

            fetched_from_api += 1;

            if TX_VERBOSE_ITEM_LOGS && (item_no == 1 || item_no % 50 == 0 || item_no == raw_count) {
                eprintln!(
                    "[KGW][transactions][FetchWorker] Tx item start address={} mode={} page={} item={}/{} txid={} stored_total={} fetched_total={}",
                    address,
                    if request.force { "force" } else { "normal" },
                    page_number,
                    item_no,
                    raw_count,
                    txid_for_log,
                    stored,
                    fetched_from_api
                );
            }

            let accepted = raw
                .get("is_accepted")
                .and_then(Value::as_bool)
                .unwrap_or(false);

            if accepted {
                accepted_timestamps.push(block_time_seconds(raw));
            } else {
                page_unaccepted_skipped += 1;

                eprintln!(
                    "[KGW][transactions][FetchWorker][WARN] Accepted-only endpoint returned unaccepted tx address={} page={} item={}/{} txid={}",
                    address, page_number, item_no, raw_count, txid_for_log
                );

                continue;
            }

            let tx_timestamp = block_time_seconds(raw);

            if request
                .end_ts
                .map(|end| tx_timestamp > end)
                .unwrap_or(false)
            {
                continue;
            }

            if let Some(txid) = transaction_id(raw)
                && existing_txids.contains(&txid)
            {
                page_existing_skipped += 1;
                continue;
            }

            let transform_started = Instant::now();

            let record = match raw_to_record_python_parity(&address, raw) {
                Ok(Some(record)) => record,
                Ok(None) => {
                    page_transform_none += 1;

                    eprintln!(
                        "[KGW][transactions][FetchWorker] Tx transform none address={} page={} item={}/{} txid={} elapsed_ms={}",
                        address,
                        page_number,
                        item_no,
                        raw_count,
                        txid_for_log,
                        transform_started.elapsed().as_millis()
                    );

                    continue;
                }
                Err(error) => {
                    eprintln!(
                        "[KGW][transactions][FetchWorker][ERROR] Tx transform failed address={} page={} item={}/{} txid={} elapsed_ms={} error={}",
                        address,
                        page_number,
                        item_no,
                        raw_count,
                        txid_for_log,
                        transform_started.elapsed().as_millis(),
                        error
                    );

                    return Err(error);
                }
            };

            page_record_timestamps.push(tx_timestamp);
            page_records.push(record);

            if TX_VERBOSE_ITEM_LOGS && (item_no == 1 || item_no % 50 == 0 || item_no == raw_count) {
                eprintln!(
                    "[KGW][transactions][FetchWorker] Tx item done address={} mode={} page={} item={}/{} txid={} item_elapsed_ms={} totals: stored={} accepted_in_range={} existing_skipped_page={} unaccepted_skipped_page={} transform_none_page={}",
                    address,
                    if request.force { "force" } else { "normal" },
                    page_number,
                    item_no,
                    raw_count,
                    txid_for_log,
                    item_started.elapsed().as_millis(),
                    stored,
                    accepted_for_range,
                    page_existing_skipped,
                    page_unaccepted_skipped,
                    page_transform_none
                );
            }
        }

        if let Some(error) = transaction_sync_cancel_error(
            &cancellation_token,
            &request_id_for_cancel,
            &address,
            "before-page-upsert",
        ) {
            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }

            return Err(error);
        }

        if !page_records.is_empty() {
            let batch_started = Instant::now();

            eprintln!(
                "[KGW][transactions][FetchWorker] Page batch upsert start address={} mode={} page={} records={}",
                address,
                if request.force { "force" } else { "normal" },
                page_number,
                page_records.len()
            );

            let inserted = match catch_unwind(AssertUnwindSafe(|| {
                if requested_force {
                    repo.stage_force_refresh_many(&page_records)
                } else {
                    repo.upsert_many(&page_records)
                }
            })) {
                Ok(Ok(inserted)) => inserted,
                Ok(Err(error)) => {
                    eprintln!(
                        "[KGW][transactions][FetchWorker][ERROR] Page batch upsert failed address={} mode={} page={} records={} elapsed_ms={} error={}",
                        address,
                        if request.force { "force" } else { "normal" },
                        page_number,
                        page_records.len(),
                        batch_started.elapsed().as_millis(),
                        error
                    );

                    return Err(format!(
                        "page batch upsert failed address={} page={} records={} error={}",
                        address,
                        page_number,
                        page_records.len(),
                        error
                    ));
                }
                Err(panic_payload) => {
                    let panic_message = if let Some(text) = panic_payload.downcast_ref::<&str>() {
                        (*text).to_string()
                    } else if let Some(text) = panic_payload.downcast_ref::<String>() {
                        text.clone()
                    } else {
                        "unknown panic payload".to_string()
                    };

                    eprintln!(
                        "[KGW][transactions][FetchWorker][PANIC] Page batch upsert panicked address={} mode={} page={} records={} elapsed_ms={} panic={}",
                        address,
                        if request.force { "force" } else { "normal" },
                        page_number,
                        page_records.len(),
                        batch_started.elapsed().as_millis(),
                        panic_message
                    );

                    return Err(format!(
                        "page batch upsert panicked address={} page={} records={} panic={}",
                        address,
                        page_number,
                        page_records.len(),
                        panic_message
                    ));
                }
            };

            stored += inserted;
            page_stored += inserted;

            for record in &page_records {
                existing_txids.insert(record.txid.clone());
            }

            for ts_seconds in page_record_timestamps.iter().copied() {
                if timestamp_in_requested_range(ts_seconds, request.start_ts, request.end_ts) {
                    accepted_for_range += 1;
                }
            }

            eprintln!(
                "[KGW][transactions][FetchWorker] Page batch upsert done address={} mode={} page={} inserted={} stored_total={} page_stored={} elapsed_ms={}",
                address,
                if request.force { "force" } else { "normal" },
                page_number,
                inserted,
                stored,
                page_stored,
                batch_started.elapsed().as_millis()
            );

            emit_transaction_sync_progress(TransactionSyncProgress {
                address: address.clone(),
                mode: if request.force { "force" } else { "normal" }.to_string(),
                phase: "page_stored".to_string(),
                page: page_number,
                page_stored,
                stored_total: stored,
                fetched_total: fetched_from_api,
                accepted_total: accepted_for_range,
                days: transaction_sync_progress_days(&page_records),
                records: Vec::new(),
            });
        }

        if let Some(error) = transaction_sync_cancel_error(
            &cancellation_token,
            &request_id_for_cancel,
            &address,
            "after-page-upsert",
        ) {
            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }

            return Err(error);
        }

        if let Some(oldest_ts_on_page) = accepted_timestamps.iter().copied().min()
            && request
                .start_ts
                .map(|start| oldest_ts_on_page < start)
                .unwrap_or(false)
        {
            stopped_by_start_date = true;
            stop_reason = format!(
                "before_start_date:page={}:oldest_ts={}",
                page_number, oldest_ts_on_page
            );

            eprintln!(
                "[KGW][transactions][FetchWorker] Fetch stop by start date address={} page={} oldest_ts={} start_ts={:?}",
                address, page_number, oldest_ts_on_page, request.start_ts
            );

            break 'sync_page_loop;
        }

        eprintln!(
            "[KGW][transactions][FetchWorker] Fetch accepted page complete address={} mode={} page={} raw_count={} page_stored={} stored_total={} fetched_total={} accepted_in_range_total={} existing_skipped_page={} unaccepted_skipped_page={} transform_none_page={} transform_errors_page={} upsert_errors_page={} oldest_ts={:?} next_before={:?} next_after={:?} elapsed_ms={}",
            address,
            if request.force { "force" } else { "normal" },
            page_number,
            raw_count,
            page_stored,
            stored,
            fetched_from_api,
            accepted_for_range,
            page_existing_skipped,
            page_unaccepted_skipped,
            page_transform_none,
            page_transform_errors,
            page_upsert_errors,
            accepted_timestamps.iter().copied().min(),
            page.next_before,
            page.next_after,
            page_started.elapsed().as_millis()
        );

        // KGW_TX_DB_FAST_STOP_ALL_EXISTING_NORMAL:
        // In normal fetch, if the accepted-only page contains no new records and every item
        // already exists locally, stop scanning external pages. SQLite already has the data.
        if !request.force && raw_count > 0 && page_stored == 0 && page_existing_skipped == raw_count
        {
            stop_reason = format!("all_existing_page:{page_number}");

            eprintln!(
                "[KGW][transactions][FetchWorker] Normal fetch stop: all transactions on page already exist address={} page={} raw_count={} existing_skipped={} fetched_total={} stored_total={}",
                address, page_number, raw_count, page_existing_skipped, fetched_from_api, stored
            );

            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }

            break 'sync_page_loop;
        }
        if let Some(error) = transaction_sync_cancel_error(
            &cancellation_token,
            &request_id_for_cancel,
            &address,
            "before-next-page",
        ) {
            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }

            return Err(error);
        }

        if let Some(next_before) = page.next_before {
            if next_before <= 0 {
                if let Some(handle) = next_prefetch.take() {
                    handle.abort();
                }
                return Err(format!(
                    "invalid transaction pagination cursor address={} page={} next_before={}",
                    address, page_number, next_before
                ));
            }

            if !seen_before_cursors.insert(next_before) {
                if let Some(handle) = next_prefetch.take() {
                    handle.abort();
                }
                return Err(format!(
                    "transaction pagination cursor cycle detected address={} page={} next_before={}",
                    address, page_number, next_before
                ));
            }

            // Backward pagination to older transactions uses X-Next-Page-Before only.
            // X-Next-Page-After is for the opposite/newer direction and can create
            // an invalid window where before < after.
            before = next_before;
            after = 0;
            prefetched_page = next_prefetch.take();
        } else {
            stop_reason = format!("no_next_page_header:{page_number}");
            if let Some(handle) = next_prefetch.take() {
                handle.abort();
            }
            break 'sync_page_loop;
        }
    }

    if requested_force {
        if stop_reason == "max_pages_reached" {
            return Err(format!(
                "force refresh did not prove completeness before max_pages address={} pages={}",
                address, pages
            ));
        }

        let staged_count = repo
            .force_refresh_staged_count(&address)
            .map_err(|error| error.to_string())?;

        if local_loaded > 0 && staged_count == 0 {
            return Err(format!(
                "force refresh refused to replace {} known-good rows with empty staged history address={}",
                local_loaded, address
            ));
        }

        let stage = force_refresh_stage
            .as_mut()
            .ok_or_else(|| "force refresh stage was not initialized".to_string())?;
        stored = stage.promote()?;

        emit_transaction_sync_progress(TransactionSyncProgress {
            address: address.clone(),
            mode: "force".to_string(),
            phase: "force_promoted".to_string(),
            page: pages,
            page_stored: 0,
            stored_total: stored,
            fetched_total: fetched_from_api,
            accepted_total: accepted_for_range,
            days: Vec::new(),
            records: Vec::new(),
        });

        eprintln!(
            "[KGW][transactions][FetchWorker] Force refresh promoted address={} known_good_before={} promoted_rows={} stop_reason={}",
            address, local_loaded, stored, stop_reason
        );
    }

    eprintln!(
        "[KGW][transactions][FetchWorker] Fetch diagnostics done address={} mode={} fetched={} stored={} accepted_in_range={} pages={} local_loaded={} deleted={} stop_reason={}",
        address,
        if request.force { "force" } else { "normal" },
        fetched_from_api,
        stored,
        accepted_for_range,
        pages,
        local_loaded,
        deleted_before_fetch,
        stop_reason
    );

    Ok(TransactionSyncSummary {
        address,
        mode: if requested_force { "force" } else { "normal" }.to_string(),
        fetched_from_api,
        accepted_for_range,
        stored,
        pages,
        local_loaded,
        deleted_before_fetch,
        stopped_by_existing_txid,
        stopped_by_start_date,
        stop_reason,
    })
}

pub fn list_transactions_grouped_by_day(
    repo: &TransactionsRepository,
    request: TransactionListRequest,
) -> Result<Vec<TransactionDayGroup>, String> {
    let parsed = KaspaAddress::parse(&request.address).map_err(|error| error.to_string())?;
    let address = parsed.as_str().to_ascii_lowercase();

    if let (Some(start), Some(end)) = (request.start_ts, request.end_ts)
        && start > end
    {
        return Err("start date cannot be after end date".to_string());
    }

    let records = repo
        .filter_for_address(TransactionFilter {
            address: &address,
            start_ms: request.start_ts.map(seconds_to_ms),
            end_ms: request.end_ts.map(seconds_to_ms),
            tx_type: request.tx_type.as_deref(),
            direction: request.direction.as_deref(),
            search: request.search_query.as_deref(),
            limit: request.limit.or(Some(1_000_000)),
        })
        .map_err(|error| error.to_string())?;

    Ok(group_records(records))
}

fn raw_to_record_python_parity(
    address: &str,
    raw: &Value,
) -> Result<Option<TransactionRecord>, String> {
    if !raw
        .get("is_accepted")
        .and_then(Value::as_bool)
        .unwrap_or(false)
    {
        return Ok(None);
    }

    let Some(txid) = transaction_id(raw) else {
        return Ok(None);
    };

    let inputs = raw
        .get("inputs")
        .and_then(Value::as_array)
        .ok_or_else(|| format!("accepted transaction {txid} is missing inputs array"))?;
    let outputs = raw
        .get("outputs")
        .and_then(Value::as_array)
        .ok_or_else(|| format!("accepted transaction {txid} is missing outputs array"))?;

    let is_coinbase = inputs.is_empty();

    let mut from_addresses = Vec::<String>::new();
    let mut to_addresses = Vec::<String>::new();
    let mut total_in = 0i64;
    let mut total_out = 0i64;

    for input in inputs {
        let from = input
            .get("previous_outpoint_address")
            .or_else(|| input.get("address"))
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .unwrap_or("UNKNOWN")
            .to_string();

        push_unique_case_insensitive(&mut from_addresses, from.clone());

        if from.eq_ignore_ascii_case(address) {
            let amount = required_nonnegative_i64(
                input
                    .get("previous_outpoint_amount")
                    .or_else(|| input.get("amount")),
                "previous_outpoint_amount",
                &txid,
            )?;
            total_out = total_out.checked_add(amount).ok_or_else(|| {
                format!("transaction {txid} input amount overflow for address={address}")
            })?;
        }
    }

    for output in outputs {
        let to = output
            .get("script_public_key_address")
            .or_else(|| output.get("address"))
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .unwrap_or("UNKNOWN")
            .to_string();

        push_unique_case_insensitive(&mut to_addresses, to.clone());

        if to.eq_ignore_ascii_case(address) {
            let amount = required_nonnegative_i64(output.get("amount"), "output.amount", &txid)?;
            total_in = total_in.checked_add(amount).ok_or_else(|| {
                format!("transaction {txid} output amount overflow for address={address}")
            })?;
        }
    }

    let is_sender = from_addresses
        .iter()
        .any(|candidate| candidate.eq_ignore_ascii_case(address));

    let is_recipient = to_addresses
        .iter()
        .any(|candidate| candidate.eq_ignore_ascii_case(address));

    if is_coinbase && !is_recipient {
        return Err(format!(
            "coinbase transaction {txid} does not contain target address={address}"
        ));
    }

    if !is_coinbase && !is_sender && !is_recipient {
        return Err(format!(
            "accepted transaction {txid} cannot prove relation to address={address}"
        ));
    }

    let net_sompi = total_in
        .checked_sub(total_out)
        .ok_or_else(|| format!("transaction {txid} net amount overflow for address={address}"))?;

    let direction = if is_coinbase || net_sompi > 0 {
        "incoming"
    } else {
        "outgoing"
    };

    let tx_type = if is_coinbase { "coinbase" } else { "transfer" };
    let amount_sompi = net_sompi.checked_abs().ok_or_else(|| {
        format!("transaction {txid} absolute amount overflow for address={address}")
    })?;

    let from_text = if from_addresses.is_empty() {
        "N/A (Coinbase)".to_string()
    } else {
        from_addresses.join(", ")
    };

    let to_text = if to_addresses.is_empty() {
        "UNKNOWN".to_string()
    } else {
        to_addresses.join(", ")
    };

    let counterparties = if direction == "incoming" {
        &from_addresses
    } else {
        &to_addresses
    };
    let known_counterparties = counterparties
        .iter()
        .filter(|candidate| !candidate.eq_ignore_ascii_case(address))
        .filter(|candidate| !candidate.eq_ignore_ascii_case("UNKNOWN"))
        .cloned()
        .collect::<Vec<_>>();

    let counterparty = if is_coinbase {
        "N/A (Coinbase)".to_string()
    } else if known_counterparties.is_empty() {
        if is_sender && is_recipient {
            "SELF".to_string()
        } else {
            "UNKNOWN".to_string()
        }
    } else {
        known_counterparties.join(", ")
    };

    let timestamp_ms = seconds_to_ms(block_time_seconds(raw));

    let block_height = value_to_i64(
        raw.get("accepting_block_blue_score")
            .or_else(|| raw.get("block_height")),
    );

    let mut record =
        TransactionRecord::new(txid, address.to_string(), tx_type, direction, amount_sompi)
            .map_err(|error| error.to_string())?
            .with_parties(Some(from_text), Some(to_text))
            .with_counterparty(counterparty)
            .with_timestamp_ms(timestamp_ms);

    if block_height >= 0 {
        record = record.with_block_height(block_height);
    }

    record.raw_json = Some(raw.to_string());

    Ok(Some(record))
}

fn group_records(records: Vec<TransactionRecord>) -> Vec<TransactionDayGroup> {
    let mut grouped = BTreeMap::<String, Vec<TransactionRecord>>::new();

    for record in records {
        grouped
            .entry(day_key(record.timestamp_ms))
            .or_default()
            .push(record);
    }

    let mut groups = grouped
        .into_iter()
        .map(|(day, mut records)| {
            records.sort_by_key(|record| std::cmp::Reverse(record.timestamp_ms));

            let mut total_incoming_sompi = 0i64;
            let mut total_outgoing_sompi = 0i64;

            let transactions = records
                .into_iter()
                .map(|record| {
                    if record.direction == "incoming" {
                        total_incoming_sompi =
                            total_incoming_sompi.saturating_add(record.amount_sompi);
                    } else if record.direction == "outgoing" {
                        total_outgoing_sompi =
                            total_outgoing_sompi.saturating_add(record.amount_sompi);
                    }

                    TransactionRowView {
                        amount_kas: record.amount_kas(),
                        txid: record.txid,
                        address: record.address,
                        tx_type: record.tx_type,
                        direction: record.direction,
                        amount_sompi: record.amount_sompi,
                        from_address: record.from_address,
                        to_address: record.to_address,
                        counterparty: record.counterparty,
                        block_height: record.block_height,
                        timestamp_ms: record.timestamp_ms,
                    }
                })
                .collect::<Vec<_>>();

            TransactionDayGroup {
                day,
                collapsed: true,
                count: transactions.len(),
                total_incoming_sompi,
                total_outgoing_sompi,
                transactions,
            }
        })
        .collect::<Vec<_>>();

    groups.sort_by(|left, right| right.day.cmp(&left.day));
    groups
}

fn timestamp_in_requested_range(ts_seconds: i64, start: Option<i64>, end: Option<i64>) -> bool {
    if start.map(|value| ts_seconds < value).unwrap_or(false) {
        return false;
    }

    if end.map(|value| ts_seconds > value).unwrap_or(false) {
        return false;
    }

    true
}

fn push_unique_case_insensitive(values: &mut Vec<String>, value: String) {
    if !values
        .iter()
        .any(|existing| existing.eq_ignore_ascii_case(&value))
    {
        values.push(value);
    }
}

fn required_nonnegative_i64(value: Option<&Value>, field: &str, txid: &str) -> Result<i64, String> {
    let parsed = match value {
        Some(Value::Number(number)) => number
            .as_i64()
            .ok_or_else(|| format!("transaction {txid} field {field} is outside i64 range"))?,
        Some(Value::String(text)) => text.trim().parse::<i64>().map_err(|error| {
            format!("transaction {txid} field {field} is not a valid i64: {error}")
        })?,
        Some(other) => {
            return Err(format!(
                "transaction {txid} field {field} has unsupported JSON type: {other}"
            ));
        }
        None => {
            return Err(format!(
                "transaction {txid} is missing required field {field}"
            ));
        }
    };

    if parsed < 0 {
        return Err(format!(
            "transaction {txid} field {field} must be non-negative, got {parsed}"
        ));
    }

    Ok(parsed)
}

fn value_to_i64(value: Option<&Value>) -> i64 {
    match value {
        Some(Value::Number(number)) => number.as_i64().unwrap_or_default(),
        Some(Value::String(text)) => text.parse::<i64>().unwrap_or_default(),
        _ => 0,
    }
}

fn seconds_to_ms(value: i64) -> i64 {
    value.saturating_mul(1000)
}
fn day_key(timestamp_ms: i64) -> String {
    let seconds = timestamp_ms.div_euclid(1000);
    let days = seconds.div_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    format!("{year:04}-{month:02}-{day:02}")
}

fn civil_from_days(days: i64) -> (i64, i64, i64) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = mp + if mp < 10 { 3 } else { -9 };
    let year = y + if m <= 2 { 1 } else { 0 };
    (year, m, d)
}

#[cfg(test)]
mod tests {
    use super::*;

    const TARGET: &str = "kaspa:qptarget";
    const OTHER: &str = "kaspa:qpother";
    const SYNC_TARGET: &str = "kaspa:qz0yqq8z3twwgg7lq2mjzg6w4edqys45w2wslz7tym2tc6s84580vvx9zr44g";

    fn test_repository(label: &str) -> (std::path::PathBuf, TransactionsRepository) {
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("clock")
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "kgw-runtime-{label}-{}-{nonce}",
            std::process::id()
        ));
        let paths = kaspa_gateway_db::DatabasePaths::new(&root).expect("database paths");
        let manager = kaspa_gateway_db::DatabaseManager::new(paths);
        let repo = manager
            .transactions_repository()
            .expect("transactions repository");
        (root, repo)
    }

    fn sync_request(request_id: &str, force: bool) -> TransactionSyncRequest {
        TransactionSyncRequest {
            address: SYNC_TARGET.to_string(),
            start_ts: None,
            end_ts: None,
            force,
            page_limit: Some(25),
            max_pages: Some(10),
            request_id: Some(request_id.to_string()),
            tx_type: None,
            direction: None,
            search_query: None,
        }
    }

    fn raw_coinbase(txid: &str, amount: i64, block_time: i64) -> Value {
        serde_json::json!({
            "is_accepted": true,
            "transaction_id": txid,
            "inputs": [],
            "outputs": [
                {"script_public_key_address": SYNC_TARGET, "amount": amount}
            ],
            "block_time": block_time
        })
    }

    fn http_response(headers: &[(&str, &str)], body: &str) -> String {
        let mut value = format!(
            "HTTP/1.1 200 OK\r\nContent-Length: {}\r\nConnection: close\r\n",
            body.len()
        );
        for (name, header_value) in headers {
            value.push_str(name);
            value.push_str(": ");
            value.push_str(header_value);
            value.push_str("\r\n");
        }
        value.push_str("\r\n");
        value.push_str(body);
        value
    }

    fn scripted_sync_server(
        responses: Vec<(std::time::Duration, String)>,
    ) -> (String, std::thread::JoinHandle<()>) {
        use std::io::{Read, Write};
        use std::net::TcpListener;

        let listener = TcpListener::bind("127.0.0.1:0").expect("bind local sync server");
        let address = listener.local_addr().expect("sync server address");
        let handle = std::thread::spawn(move || {
            for (delay, response) in responses {
                let (mut stream, _) = listener.accept().expect("accept sync request");
                let _ = stream.set_read_timeout(Some(std::time::Duration::from_secs(2)));
                let mut request = [0_u8; 8192];
                let _ = stream.read(&mut request);
                if !delay.is_zero() {
                    std::thread::sleep(delay);
                }
                let _ = stream.write_all(response.as_bytes());
                let _ = stream.flush();
            }
        });

        (format!("http://{address}"), handle)
    }

    fn local_sync_config(base_url: String) -> TransactionFetchConfig {
        TransactionFetchConfig {
            base_url,
            max_retries: 0,
            retry_base_delay_ms: 1,
            retry_max_delay_ms: 5,
            ..TransactionFetchConfig::default()
        }
    }

    fn seed_known_good(repo: &TransactionsRepository, txid: &str) {
        let mut record = TransactionRecord::new(txid, SYNC_TARGET, "transfer", "incoming", 7)
            .expect("seed record");
        record.timestamp_ms = 1_600_000_000_000;
        record.raw_json = Some(format!("{{\"transaction_id\":\"{txid}\"}}"));
        repo.upsert(&record).expect("seed known-good");
    }

    static SYNC_TEST_SERIAL: std::sync::atomic::AtomicBool =
        std::sync::atomic::AtomicBool::new(false);

    struct SyncTestSerialGuard;

    impl SyncTestSerialGuard {
        fn acquire() -> Self {
            while SYNC_TEST_SERIAL
                .compare_exchange(
                    false,
                    true,
                    std::sync::atomic::Ordering::SeqCst,
                    std::sync::atomic::Ordering::SeqCst,
                )
                .is_err()
            {
                std::thread::yield_now();
            }
            Self
        }
    }

    impl Drop for SyncTestSerialGuard {
        fn drop(&mut self) {
            SYNC_TEST_SERIAL.store(false, std::sync::atomic::Ordering::SeqCst);
        }
    }

    #[test]
    fn raw_to_record_rejects_missing_mandatory_transaction_shape() {
        let missing_inputs = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "missing-inputs",
            "outputs": []
        });
        let error = raw_to_record_python_parity(TARGET, &missing_inputs)
            .expect_err("missing inputs must fail closed");
        assert!(error.contains("missing inputs array"));

        let missing_outputs = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "missing-outputs",
            "inputs": []
        });
        let error = raw_to_record_python_parity(TARGET, &missing_outputs)
            .expect_err("missing outputs must fail closed");
        assert!(error.contains("missing outputs array"));
    }

    #[test]
    fn raw_to_record_coinbase_is_incoming_with_exact_target_amount() {
        let raw = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "coinbase-1",
            "inputs": [],
            "outputs": [
                {"script_public_key_address": TARGET, "amount": "500"},
                {"script_public_key_address": OTHER, "amount": 25}
            ],
            "block_time": 1_700_000_000
        });

        let record = raw_to_record_python_parity(TARGET, &raw)
            .expect("coinbase transform")
            .expect("accepted record");
        assert_eq!(record.tx_type, "coinbase");
        assert_eq!(record.direction, "incoming");
        assert_eq!(record.amount_sompi, 500);
        assert_eq!(record.counterparty.as_deref(), Some("N/A (Coinbase)"));
    }

    #[test]
    fn raw_to_record_incoming_transfer_counts_only_target_outputs() {
        let raw = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "incoming-1",
            "inputs": [
                {"previous_outpoint_address": OTHER, "previous_outpoint_amount": 100}
            ],
            "outputs": [
                {"script_public_key_address": TARGET, "amount": 60},
                {"script_public_key_address": "kaspa:qpchange", "amount": 40}
            ],
            "block_time": 1_700_000_001
        });

        let record = raw_to_record_python_parity(TARGET, &raw)
            .expect("incoming transform")
            .expect("accepted record");
        assert_eq!(record.tx_type, "transfer");
        assert_eq!(record.direction, "incoming");
        assert_eq!(record.amount_sompi, 60);
        assert_eq!(record.counterparty.as_deref(), Some(OTHER));
    }

    #[test]
    fn raw_to_record_outgoing_with_change_uses_net_delta_and_excludes_self() {
        let raw = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "outgoing-change-1",
            "inputs": [
                {"previous_outpoint_address": TARGET, "previous_outpoint_amount": 100}
            ],
            "outputs": [
                {"script_public_key_address": OTHER, "amount": 70},
                {"script_public_key_address": TARGET, "amount": 29}
            ],
            "block_time": 1_700_000_002
        });

        let record = raw_to_record_python_parity(TARGET, &raw)
            .expect("outgoing transform")
            .expect("accepted record");
        assert_eq!(record.direction, "outgoing");
        assert_eq!(record.amount_sompi, 71);
        assert_eq!(record.counterparty.as_deref(), Some(OTHER));
    }

    #[test]
    fn raw_to_record_self_transfer_reports_only_net_cost() {
        let raw = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "self-1",
            "inputs": [
                {"previous_outpoint_address": TARGET, "previous_outpoint_amount": 100}
            ],
            "outputs": [
                {"script_public_key_address": TARGET, "amount": 99}
            ],
            "block_time": 1_700_000_003
        });

        let record = raw_to_record_python_parity(TARGET, &raw)
            .expect("self transfer transform")
            .expect("accepted record");
        assert_eq!(record.direction, "outgoing");
        assert_eq!(record.amount_sompi, 1);
        assert_eq!(record.counterparty.as_deref(), Some("SELF"));
    }

    #[test]
    fn raw_to_record_mixed_input_output_uses_signed_net_direction() {
        let raw = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "mixed-net-incoming",
            "inputs": [
                {"previous_outpoint_address": TARGET, "previous_outpoint_amount": 10},
                {"previous_outpoint_address": OTHER, "previous_outpoint_amount": 100}
            ],
            "outputs": [
                {"script_public_key_address": TARGET, "amount": 50},
                {"script_public_key_address": "kaspa:qpthird", "amount": 59}
            ],
            "block_time": 1_700_000_004
        });

        let record = raw_to_record_python_parity(TARGET, &raw)
            .expect("mixed transform")
            .expect("accepted record");
        assert_eq!(record.direction, "incoming");
        assert_eq!(record.amount_sompi, 40);
        assert_eq!(record.counterparty.as_deref(), Some(OTHER));
    }

    #[test]
    fn raw_to_record_rejects_missing_or_invalid_target_amount() {
        let missing = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "missing-target-amount",
            "inputs": [
                {"previous_outpoint_address": OTHER, "previous_outpoint_amount": 100}
            ],
            "outputs": [
                {"script_public_key_address": TARGET}
            ]
        });
        let error = raw_to_record_python_parity(TARGET, &missing)
            .expect_err("missing target output amount must fail");
        assert!(error.contains("missing required field output.amount"));

        let negative = serde_json::json!({
            "is_accepted": true,
            "transaction_id": "negative-target-amount",
            "inputs": [
                {"previous_outpoint_address": TARGET, "previous_outpoint_amount": -1}
            ],
            "outputs": [
                {"script_public_key_address": OTHER, "amount": 1}
            ]
        });
        let error = raw_to_record_python_parity(TARGET, &negative)
            .expect_err("negative target input amount must fail");
        assert!(error.contains("must be non-negative"));
    }

    #[tokio::test(flavor = "current_thread")]
    async fn sync_hermetic_fault_matrix_proves_atomic_force_cycle_and_cancel() {
        let _serial = SyncTestSerialGuard::acquire();
        transaction_sync_tasks().lock().expect("registry").clear();

        {
            let (root, repo) = test_repository("force-success");
            seed_known_good(&repo, "old-success");
            let body = serde_json::to_string(&vec![raw_coinbase("new-success", 11, 1_700_000_100)])
                .expect("response body");
            let (base_url, server) =
                scripted_sync_server(vec![(std::time::Duration::ZERO, http_response(&[], &body))]);
            let summary = sync_transactions_with_config(
                &repo,
                sync_request("force-success", true),
                local_sync_config(base_url),
            )
            .await
            .expect("complete force refresh must promote");
            server.join().expect("force success server");

            assert_eq!(summary.stored, 1);
            assert!(summary.stop_reason.starts_with("no_next_page_header:"));
            let rows = repo
                .list_for_address(SYNC_TARGET, 10)
                .expect("post-promote rows");
            assert_eq!(rows.len(), 1);
            assert_eq!(rows[0].txid, "new-success");
            drop(repo);
            let _ = std::fs::remove_dir_all(root);
        }

        {
            let (root, repo) = test_repository("cursor-cycle");
            seed_known_good(&repo, "old-cycle");
            let body_one = serde_json::to_string(&vec![raw_coinbase("cycle-1", 12, 1_700_000_101)])
                .expect("page one");
            let body_two = serde_json::to_string(&vec![raw_coinbase("cycle-2", 13, 1_700_000_102)])
                .expect("page two");
            let (base_url, server) = scripted_sync_server(vec![
                (
                    std::time::Duration::ZERO,
                    http_response(&[("X-Next-Page-Before", "10")], &body_one),
                ),
                (
                    std::time::Duration::ZERO,
                    http_response(&[("X-Next-Page-Before", "10")], &body_two),
                ),
            ]);

            let error = sync_transactions_with_config(
                &repo,
                sync_request("cursor-cycle", true),
                local_sync_config(base_url),
            )
            .await
            .expect_err("repeated cursor must fail closed");
            server.join().expect("cycle server");
            assert!(error.contains("cursor cycle detected"));

            let rows = repo
                .list_for_address(SYNC_TARGET, 10)
                .expect("known-good after cursor cycle");
            assert_eq!(rows.len(), 1);
            assert_eq!(rows[0].txid, "old-cycle");
            drop(repo);
            let _ = std::fs::remove_dir_all(root);
        }

        {
            let (root, repo) = test_repository("max-pages");
            seed_known_good(&repo, "old-max-pages");
            let body = serde_json::to_string(&vec![raw_coinbase("max-page-1", 14, 1_700_000_103)])
                .expect("max page body");
            let (base_url, server) = scripted_sync_server(vec![(
                std::time::Duration::ZERO,
                http_response(&[("X-Next-Page-Before", "10")], &body),
            )]);
            let mut request = sync_request("max-pages", true);
            request.max_pages = Some(1);

            let error = sync_transactions_with_config(&repo, request, local_sync_config(base_url))
                .await
                .expect_err("incomplete force refresh must not promote at max-pages");
            server.join().expect("max-pages server");
            assert!(error.contains("did not prove completeness before max_pages"));

            let rows = repo
                .list_for_address(SYNC_TARGET, 10)
                .expect("known-good after max-pages");
            assert_eq!(rows.len(), 1);
            assert_eq!(rows[0].txid, "old-max-pages");
            drop(repo);
            let _ = std::fs::remove_dir_all(root);
        }

        {
            let (root, repo) = test_repository("cancel-http");
            seed_known_good(&repo, "old-cancel");
            let (base_url, server) = scripted_sync_server(vec![(
                std::time::Duration::from_secs(2),
                http_response(&[], "[]"),
            )]);
            let request_id = "cancel-slow-http";
            let started = Instant::now();
            let sync = sync_transactions_with_config(
                &repo,
                sync_request(request_id, true),
                local_sync_config(base_url),
            );
            let cancel = async {
                tokio::time::sleep(std::time::Duration::from_millis(50)).await;
                assert!(
                    request_transaction_sync_cancel(request_id),
                    "active request must be cancellable by exact request id"
                );
            };

            let (result, ()) = tokio::join!(sync, cancel);
            let cancel_elapsed = started.elapsed();
            let error = result.expect_err("slow HTTP request must cancel");
            assert!(error.contains("cancelled"));
            assert!(
                cancel_elapsed < std::time::Duration::from_secs(1),
                "worker cancellation exceeded hermetic 1s SLO: {cancel_elapsed:?}"
            );

            let rows = repo
                .list_for_address(SYNC_TARGET, 10)
                .expect("known-good after cancellation");
            assert_eq!(rows.len(), 1);
            assert_eq!(rows[0].txid, "old-cancel");
            server.join().expect("cancel server");
            drop(repo);
            let _ = std::fs::remove_dir_all(root);
        }

        assert!(
            transaction_sync_tasks()
                .lock()
                .expect("registry")
                .is_empty()
        );
    }

    #[test]
    fn transaction_sync_registry_cancels_exact_request_and_releases_capacity() {
        let _serial = SyncTestSerialGuard::acquire();
        transaction_sync_tasks().lock().expect("registry").clear();

        let guard = TransactionSyncGuard::enter("kaspa:qptestaddress", Some("request-a"), false)
            .expect("first task");

        assert!(!request_transaction_sync_cancel("request-b"));
        assert!(request_transaction_sync_cancel("request-a"));
        assert!(guard.cancellation_token().is_cancelled());

        assert!(
            TransactionSyncGuard::enter("kaspa:qpotheraddress", Some("request-b"), false,).is_err(),
            "bounded capacity must reject a second concurrent task while the global progress callback is single-owner"
        );

        drop(guard);

        let second = TransactionSyncGuard::enter("kaspa:qpotheraddress", Some("request-b"), false)
            .expect("capacity released after drop");
        assert!(!second.cancellation_token().is_cancelled());
        drop(second);

        transaction_sync_tasks()
            .lock()
            .expect("registry cleanup")
            .clear();
    }
}
