[package]
name = "kaspa-gateway-rk-node"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
kgw-inproc-owner = []

official-kaspa-runtime-mainline = [
    "kgw-inproc-owner",
    "dep:kaspad-lib-mainline",
    "dep:kaspa-core-mainline",
    "dep:kaspa-utils-mainline",
    "kaspa-gateway-rk-bridge/official-kaspa-runtime-mainline"
]

official-kaspa-runtime-tn12 = [
    "kgw-inproc-owner",
    "dep:kaspad-lib-tn12",
    "dep:kaspa-core-tn12",
    "dep:kaspa-utils-tn12",
    "kaspa-gateway-rk-bridge/official-kaspa-runtime-tn12"
]

official-kaspa-runtime-all = [
    "official-kaspa-runtime-mainline",
    "official-kaspa-runtime-tn12"
]

[dependencies]
serde.workspace = true
thiserror.workspace = true
kaspa-gateway-rk-bridge = { path = "../kaspa-gateway-rk-bridge" }

kaspad-lib-mainline = { package = "kaspad", git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "d7f9b1590ca68c95ebe9f7242b822ecdf867de7e", optional = true }
kaspa-core-mainline = { package = "kaspa-core", git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "d7f9b1590ca68c95ebe9f7242b822ecdf867de7e", optional = true }
kaspa-utils-mainline = { package = "kaspa-utils", git = "https://github.com/kaspanet/rusty-kaspa.git", rev = "d7f9b1590ca68c95ebe9f7242b822ecdf867de7e", optional = true }

kaspad-lib-tn12 = { package = "kaspad", git = "https://github.com/LiveLaughLove13/rusty-kaspa.git", rev = "f197b5ca00a92825f9962db1b3ed0f5d00455464", optional = true }
kaspa-core-tn12 = { package = "kaspa-core", git = "https://github.com/LiveLaughLove13/rusty-kaspa.git", rev = "f197b5ca00a92825f9962db1b3ed0f5d00455464", optional = true }
kaspa-utils-tn12 = { package = "kaspa-utils", git = "https://github.com/LiveLaughLove13/rusty-kaspa.git", rev = "f197b5ca00a92825f9962db1b3ed0f5d00455464", optional = true }

