use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const WASM_PACK_VERSION: &str = "wasm-pack 0.15.0";
const CRATE_RELATIVE: &str = "crates/kaspa-gateway-e2e-wasm";
const GENERATED_RELATIVE: &str = "e2e/generated/kgw_e2e_wasm";
const RUNTIME_PORTS_ADAPTER_RELATIVE: &str = "e2e/helpers/runtime-ports.mjs";
const ASSERTIONS_ADAPTER_RELATIVE: &str = "e2e/helpers/assertions.mjs";
const PATHS_ADAPTER_RELATIVE: &str = "e2e/helpers/paths.mjs";
const JS_NAME: &str = "kgw_e2e_wasm.js";
const WASM_NAME: &str = "kgw_e2e_wasm_bg.wasm";
const PACKAGE_NAME: &str = "package.json";

pub fn run_cli(args: &mut impl Iterator<Item = String>, root: &Path) -> Result<String, String> {
    let action = args.next().unwrap_or_else(|| "check".to_owned());
    if args.next().is_some() {
        return Err("e2e-wasm-codegen accepts exactly one action: check or write".to_owned());
    }
    match action.as_str() {
        "check" => check(root),
        "write" => write(root),
        _ => Err(format!(
            "unknown e2e-wasm-codegen action: {action}; expected check or write"
        )),
    }
}

fn runtime_ports_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- e2e-wasm-codegen write
// Rust owns the implementation. This module is deterministic Node ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const wasm = require("../generated/kgw_e2e_wasm/kgw_e2e_wasm.js");

export function runtimePortProfile(env = process.env) {
  return wasm.runtimePortProfile(env);
}
"#
    .to_owned()
}

fn assertions_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- e2e-wasm-codegen write
// Rust owns the implementation. This module is deterministic Node ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const wasm = require("../generated/kgw_e2e_wasm/kgw_e2e_wasm.js");

export const rawLogRejectionMarkers = Object.freeze([...wasm.rawLogRejectionMarkers()]);

export function sha256Hex(text) {
  return wasm.sha256Hex(text);
}

export function normalizeClipboardText(text) {
  return wasm.normalizeClipboardText(text);
}

export function lineCount(text) {
  return wasm.lineCount(text);
}

export function containsTransportWrapper(text) {
  return wasm.containsTransportWrapper(text);
}

export function parseKeyValueLine(text) {
  return wasm.parseKeyValueLine(text);
}

export function pidFromStatus(statusText) {
  return wasm.pidFromStatus(statusText);
}

export function isStoppedOwnerStatus(statusText) {
  return wasm.isStoppedOwnerStatus(statusText);
}

export function assertNoTransportWrappers(text, label) {
  return wasm.assertNoTransportWrappers(text, label);
}

export function assertDirectRawPayload(options) {
  return wasm.assertDirectRawPayload(options);
}

export function assertRuntimeLogReport(report, options) {
  return wasm.assertRuntimeLogReport(report, options);
}
"#
    .to_owned()
}

fn paths_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- e2e-wasm-codegen write
// Rust owns the implementation. This module is deterministic Node ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const wasm = require("../generated/kgw_e2e_wasm/kgw_e2e_wasm.js");
const context = wasm.artifactPathContext(import.meta.url, process.env);

export const e2eDir = context.e2eDir;
export const repository = context.repository;
export const artifactRoot = context.artifactRoot;

export function ensureDir(directory) {
  return wasm.artifactEnsureDir(directory);
}

export function caseDir(slug) {
  return wasm.artifactCaseDir(artifactRoot, slug);
}

export function writeJson(file, value) {
  return wasm.artifactWriteJson(file, value);
}

export function writeText(file, value) {
  return wasm.artifactWriteText(file, value);
}

export function helperScript(name) {
  return wasm.artifactHelperScript(e2eDir, name);
}
"#
    .to_owned()
}

fn package_source() -> &'static str {
    "{\n  \"type\": \"commonjs\"\n}\n"
}

fn temp_output(root: &Path) -> PathBuf {
    root.join("target").join("kgw-e2e-wasm-codegen")
}

fn verify_wasm_pack() -> Result<(), String> {
    let output = Command::new("wasm-pack")
        .arg("--version")
        .output()
        .map_err(|error| format!("wasm-pack is required but could not start: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "wasm-pack --version failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let actual = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    if actual != WASM_PACK_VERSION {
        return Err(format!(
            "E2E WASM codegen requires {WASM_PACK_VERSION}; found {actual}"
        ));
    }
    Ok(())
}

fn normalize_text_artifact(path: &Path) -> Result<(), String> {
    let text = fs::read_to_string(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    let normalized = format!("{}\n", text.trim_end_matches(['\r', '\n']));
    if normalized != text {
        fs::write(path, normalized.as_bytes())
            .map_err(|error| format!("failed to normalize {}: {error}", path.display()))?;
    }
    Ok(())
}

fn build_temp(root: &Path) -> Result<PathBuf, String> {
    verify_wasm_pack()?;
    let output_dir = temp_output(root);
    if output_dir.exists() {
        fs::remove_dir_all(&output_dir)
            .map_err(|error| format!("failed to clear {}: {error}", output_dir.display()))?;
    }

    let output = Command::new("wasm-pack")
        .current_dir(root)
        .env("RUSTUP_TOOLCHAIN", "1.98.1")
        .args([
            "build",
            CRATE_RELATIVE,
            "--target",
            "nodejs",
            "--release",
            "--out-dir",
        ])
        .arg(&output_dir)
        .args([
            "--out-name",
            "kgw_e2e_wasm",
            "--no-typescript",
            "--no-pack",
            "--no-opt",
        ])
        .output()
        .map_err(|error| format!("failed to start wasm-pack build: {error}"))?;

    if !output.status.success() {
        return Err(format!(
            "E2E WASM build failed\nstdout={}\nstderr={}",
            String::from_utf8_lossy(&output.stdout).trim(),
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }

    for name in [JS_NAME, WASM_NAME] {
        if !output_dir.join(name).is_file() {
            return Err(format!(
                "wasm-pack did not produce required artifact: {}",
                output_dir.join(name).display()
            ));
        }
    }
    normalize_text_artifact(&output_dir.join(JS_NAME))?;
    Ok(output_dir)
}

fn same_bytes(left: &Path, right: &Path) -> Result<bool, String> {
    let left_bytes =
        fs::read(left).map_err(|error| format!("failed to read {}: {error}", left.display()))?;
    let right_bytes =
        fs::read(right).map_err(|error| format!("failed to read {}: {error}", right.display()))?;
    Ok(left_bytes == right_bytes)
}

fn check(root: &Path) -> Result<String, String> {
    let built = build_temp(root)?;
    let tracked = root.join(GENERATED_RELATIVE);
    let mut drift = Vec::new();

    for name in [JS_NAME, WASM_NAME] {
        let tracked_file = tracked.join(name);
        if !tracked_file.is_file() || !same_bytes(&built.join(name), &tracked_file)? {
            drift.push(tracked_file.to_string_lossy().into_owned());
        }
    }

    let mut tracked_names = if tracked.is_dir() {
        fs::read_dir(&tracked)
            .map_err(|error| format!("failed to list {}: {error}", tracked.display()))?
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };
    tracked_names.sort();
    let mut expected_names = vec![
        JS_NAME.to_owned(),
        PACKAGE_NAME.to_owned(),
        WASM_NAME.to_owned(),
    ];
    expected_names.sort();
    if tracked_names != expected_names {
        drift.push(format!(
            "{}:unexpected-generated-file-set={}",
            tracked.display(),
            tracked_names.join(",")
        ));
    }

    let package = tracked.join(PACKAGE_NAME);
    let expected_package = package_source();
    let actual_package = fs::read_to_string(&package).unwrap_or_default();
    if actual_package != expected_package {
        drift.push(package.to_string_lossy().into_owned());
    }

    for (relative, expected) in [
        (
            RUNTIME_PORTS_ADAPTER_RELATIVE,
            runtime_ports_adapter_source(),
        ),
        (ASSERTIONS_ADAPTER_RELATIVE, assertions_adapter_source()),
        (PATHS_ADAPTER_RELATIVE, paths_adapter_source()),
    ] {
        let adapter = root.join(relative);
        let actual = fs::read_to_string(&adapter).unwrap_or_default();
        if actual != expected {
            drift.push(adapter.to_string_lossy().into_owned());
        }
    }

    if drift.is_empty() {
        Ok(format!(
            "E2E_WASM_CODEGEN=PASS\nWASM_PACK_VERSION={}\nARTIFACT_COUNT=6",
            WASM_PACK_VERSION.trim_start_matches("wasm-pack ")
        ))
    } else {
        Err(format!("E2E_WASM_CODEGEN=FAIL\nDRIFT={}", drift.join(",")))
    }
}

fn write(root: &Path) -> Result<String, String> {
    let built = build_temp(root)?;
    let tracked = root.join(GENERATED_RELATIVE);
    fs::create_dir_all(&tracked)
        .map_err(|error| format!("failed to create {}: {error}", tracked.display()))?;

    let mut changed = 0_usize;
    for name in [JS_NAME, WASM_NAME] {
        let source = built.join(name);
        let destination = tracked.join(name);
        let differs = !destination.is_file() || !same_bytes(&source, &destination)?;
        if differs {
            fs::copy(&source, &destination).map_err(|error| {
                format!(
                    "failed to copy {} to {}: {error}",
                    source.display(),
                    destination.display()
                )
            })?;
            changed += 1;
        }
    }

    let package = tracked.join(PACKAGE_NAME);
    let expected_package = package_source();
    let actual_package = fs::read_to_string(&package).unwrap_or_default();
    if actual_package != expected_package {
        fs::write(&package, expected_package.as_bytes())
            .map_err(|error| format!("failed to write {}: {error}", package.display()))?;
        changed += 1;
    }

    for (relative, expected) in [
        (
            RUNTIME_PORTS_ADAPTER_RELATIVE,
            runtime_ports_adapter_source(),
        ),
        (ASSERTIONS_ADAPTER_RELATIVE, assertions_adapter_source()),
        (PATHS_ADAPTER_RELATIVE, paths_adapter_source()),
    ] {
        let adapter = root.join(relative);
        let actual = fs::read_to_string(&adapter).unwrap_or_default();
        if actual != expected {
            fs::write(&adapter, expected.as_bytes())
                .map_err(|error| format!("failed to write {}: {error}", adapter.display()))?;
            changed += 1;
        }
    }

    Ok(format!(
        "E2E_WASM_CODEGEN=WRITE_PASS\nWASM_PACK_VERSION={}\nARTIFACT_COUNT=6\nCHANGED={changed}",
        WASM_PACK_VERSION.trim_start_matches("wasm-pack ")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adapters_are_generated_and_delegate_only_to_rust() {
        let runtime_ports = runtime_ports_adapter_source();
        assert!(runtime_ports.contains("@generated"));
        assert!(runtime_ports.contains("createRequire"));
        assert!(runtime_ports.contains("wasm.runtimePortProfile(env)"));
        assert!(!runtime_ports.contains("Number.isInteger"));
        assert!(!runtime_ports.contains("KGW_E2E_MAINNET_RPC_PORT"));

        let assertions = assertions_adapter_source();
        assert!(assertions.contains("@generated"));
        assert!(assertions.contains("createRequire"));
        assert!(assertions.contains("wasm.rawLogRejectionMarkers()"));
        assert!(assertions.contains("wasm.assertDirectRawPayload(options)"));
        assert!(assertions.contains("wasm.assertRuntimeLogReport(report, options)"));
        assert!(!assertions.contains("createHash("));
        assert!(!assertions.contains("assert.equal("));
        let paths = paths_adapter_source();
        assert!(paths.contains("wasm.artifactPathContext(import.meta.url, process.env)"));
        for name in [
            "artifactEnsureDir",
            "artifactCaseDir",
            "artifactWriteJson",
            "artifactWriteText",
            "artifactHelperScript",
        ] {
            assert!(paths.contains(&format!("wasm.{name}(")));
        }
        for forbidden in [
            "fs.mkdir",
            "fs.writeFile",
            "JSON.stringify",
            "path.join",
            "KGW_ZERO_TOUCH_ARTIFACT_DIR",
            "Date.now",
        ] {
            assert!(
                !paths.contains(forbidden),
                "implementation must remain in Rust: {forbidden}"
            );
        }
        assert_eq!(package_source(), "{\n  \"type\": \"commonjs\"\n}\n");
    }

    #[test]
    fn text_artifact_normalization_keeps_exactly_one_trailing_newline() {
        let path = std::env::temp_dir().join(format!(
            "kgw-e2e-wasm-codegen-normalize-{}.js",
            std::process::id()
        ));
        let _ = fs::remove_file(&path);
        fs::write(&path, b"module.exports = {};\n\n").unwrap();
        normalize_text_artifact(&path).unwrap();
        assert_eq!(fs::read(&path).unwrap(), b"module.exports = {};\n");
        normalize_text_artifact(&path).unwrap();
        assert_eq!(fs::read(&path).unwrap(), b"module.exports = {};\n");
        let _ = fs::remove_file(path);
    }

    #[test]
    fn generated_paths_are_inside_e2e_or_target() {
        assert!(GENERATED_RELATIVE.starts_with("e2e/generated/"));
        assert!(RUNTIME_PORTS_ADAPTER_RELATIVE.starts_with("e2e/helpers/"));
        assert!(RUNTIME_PORTS_ADAPTER_RELATIVE.ends_with("runtime-ports.mjs"));
        assert!(ASSERTIONS_ADAPTER_RELATIVE.starts_with("e2e/helpers/"));
        assert!(ASSERTIONS_ADAPTER_RELATIVE.ends_with("assertions.mjs"));
        let root = Path::new("repo");
        assert!(temp_output(root).starts_with(root.join("target")));
    }
}
