pub(crate) fn windows_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- e2e-wasm-codegen write
// Rust owns Windows/process/clipboard policy. This module is deterministic Node platform glue.
// DO NOT EDIT THIS FILE DIRECTLY.
import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import net from "node:net";
import path from "node:path";
import { promisify } from "node:util";
import { repository, writeJson } from "./paths.mjs";

const execFileAsync = promisify(execFile);

async function runRustXtask(args = [], options = {}) {
  try {
    const result = await execFileAsync("cargo", [
      "run", "--quiet", "--locked", "-p", "xtask", "--", ...args,
    ], {
      windowsHide: true,
      maxBuffer: options.maxBuffer || 16 * 1024 * 1024,
      timeout: options.timeout || 60000,
      cwd: repository,
      env: { ...process.env, ...(options.env || {}) },
    });
    const stdout = String(result.stdout || "").trim();
    return stdout ? JSON.parse(stdout) : {};
  } catch (error) {
    const stdout = String(error?.stdout || "").trim();
    const stderr = String(error?.stderr || "").trim();
    const message = [
      error?.message || "Rust xtask command failed",
      stdout ? `stdout=${stdout}` : "",
      stderr ? `stderr=${stderr}` : "",
    ].filter(Boolean).join("\n");
    throw new Error(message, { cause: error });
  }
}

export async function writeClipboardSentinel(value) {
  return await runRustXtask([
    "e2e-clipboard", "write", "--value", String(value),
  ]);
}

export async function readClipboardToFile(outputPath) {
  return await runRustXtask([
    "e2e-clipboard", "read", "--output-path", outputPath,
  ]);
}
export async function waitForClipboardShaToFile({
  outputPath, expectedSha = "", rejectedSha = "", timeoutMs = 30000,
}) {
  const wanted = String(expectedSha || "").toLowerCase();
  const rejected = String(rejectedSha || "").toLowerCase();
  return await waitUntil("Windows clipboard content", timeoutMs, 500, async () => {
    const capture = await readClipboardToFile(outputPath);
    const actual = String(capture?.sha256 || "").toLowerCase();
    if (!actual) return false;
    if (rejected && actual === rejected) return false;
    if (wanted && actual !== wanted) return false;
    return capture;
  });
}

export async function killExactOwnedProcess({
  pid, expectedExecutable, expectedStartTime, outputPath,
}) {
  return await runRustXtask([
    "e2e-owned-process", "kill",
    "--process-id", String(pid),
    "--expected-executable", String(expectedExecutable || ""),
    "--expected-start-time", String(expectedStartTime || ""),
    "--output-path", outputPath,
  ], { timeout: 30000 });
}
export async function waitForExactProcessExit({
  pid, expectedExecutable, expectedStartTime, outputPath, timeoutSeconds = 45,
}) {
  return await runRustXtask([
    "e2e-owned-process", "wait",
    "--process-id", String(pid),
    "--expected-executable", String(expectedExecutable || ""),
    "--expected-start-time", String(expectedStartTime || ""),
    "--output-path", outputPath,
    "--timeout-seconds", String(timeoutSeconds),
  ], { timeout: (Number(timeoutSeconds) + 15) * 1000 });
}

export async function captureWindowsEvidence({
  repository: repositoryPath, outputDirectory, ports = [], desktopPid = "",
}) {
  return await runRustXtask([
    "e2e-windows-evidence",
    "--repository", repositoryPath,
    "--output-directory", outputDirectory,
    "--ports", ports.join(","),
    "--desktop-pid", String(desktopPid || ""),
  ], { timeout: 60000 });
}
export async function waitUntil(label, timeoutMs, intervalMs, probe) {
  const started = Date.now();
  let lastError = null;
  while (Date.now() - started < timeoutMs) {
    try {
      const value = await probe();
      if (value) return value;
    } catch (error) {
      lastError = error;
    }
    await new Promise((resolve) => setTimeout(resolve, intervalMs));
  }
  const suffix = lastError ? ` Last error: ${lastError.message || lastError}` : "";
  throw new Error(`${label} timed out after ${timeoutMs}ms.${suffix}`);
}

async function probePort(host, port, expectFree) {
  return await new Promise((resolve) => {
    const socket = net.createConnection({ host, port });
    let settled = false;
    const finish = (value) => {
      if (settled) return;
      settled = true;
      socket.destroy();
      resolve(value);
    };
    socket.setTimeout(expectFree ? 1000 : 1500);
    socket.once("connect", () => finish(expectFree ? false : {
      host, port, connected: true, observedAt: new Date().toISOString(),
    }));
    socket.once("timeout", () => finish(false));
    socket.once("error", () => finish(expectFree ? {
      host, port, free: true, observedAt: new Date().toISOString(),
    } : false));
  });
}

export async function waitForPort(host, port, timeoutMs = 120000) {
  return await waitUntil(
    `port ${host}:${port}`, timeoutMs, 500,
    async () => await probePort(host, port, false),
  );
}

export async function waitForPortFree(host, port, timeoutMs = 60000) {
  return await waitUntil(
    `port free ${host}:${port}`, timeoutMs, 500,
    async () => await probePort(host, port, true),
  );
}
export async function probeLocalStratum({
  host = "127.0.0.1", port, outputDirectory, label,
}) {
  const payload = JSON.stringify({
    id: 1,
    method: "mining.subscribe",
    params: [`kgw-zero-touch-e2e-${label}`],
  }) + "\n";
  const evidence = {
    host, port, label, payload,
    connected: false, response: "", error: "",
    startedAt: new Date().toISOString(),
  };

  await new Promise((resolve) => {
    const socket = net.createConnection({ host, port });
    const chunks = [];
    let settled = false;
    const finish = (error) => {
      if (settled) return;
      settled = true;
      evidence.endedAt = new Date().toISOString();
      if (error) evidence.error = String(error?.message || error);
      evidence.response = Buffer.concat(chunks).toString("utf8");
      socket.destroy();
      resolve();
    };
    socket.setTimeout(2500);
    socket.once("connect", () => {
      evidence.connected = true;
      socket.write(payload, "utf8");
    });
    socket.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    socket.once("timeout", () => finish());
    socket.once("error", (error) => finish(error));
    socket.once("close", () => finish());
  });

  await fs.mkdir(outputDirectory, { recursive: true });
  await writeJson(path.join(outputDirectory, "stratum-probe.json"), evidence);
  return evidence;
}
"#
    .to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_windows_adapter_delegates_sensitive_actions_to_rust() {
        let source = windows_adapter_source();
        assert!(source.contains(r#""e2e-clipboard", "write""#));
        assert!(source.contains(r#""e2e-clipboard", "read""#));
        assert!(source.contains(r#""e2e-owned-process", "kill""#));
        assert!(source.contains(r#""e2e-owned-process", "wait""#));
        assert!(source.contains(r#""e2e-windows-evidence""#));
        assert!(!source.contains(".ps1"));
        assert!(!source.contains("Set-Clipboard"));
    }
}
