use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const WASM_PACK_VERSION: &str = "wasm-pack 0.15.0";
const CRATE_RELATIVE: &str = "crates/kaspa-gateway-frontend-wasm";
const GENERATED_RELATIVE: &str = "apps/kaspa-gateway-desktop/frontend/generated/kgw_frontend_wasm";
const UTILS_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.utils.js";
const DATE_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.date.js";
const FORMATTING_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.formatting.js";
const HEADER_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.header.js";
const STATUS_ADAPTER_RELATIVE: &str = "apps/kaspa-gateway-desktop/frontend/src/status.js";
const JS_NAME: &str = "kgw_frontend_wasm.js";
const WASM_NAME: &str = "kgw_frontend_wasm_bg.wasm";
type AdapterGenerator = (&'static str, fn() -> String);

pub fn run_cli(args: &mut impl Iterator<Item = String>, root: &Path) -> Result<String, String> {
    let action = args.next().unwrap_or_else(|| "check".to_owned());
    if args.next().is_some() {
        return Err("frontend-wasm-codegen accepts exactly one action: check or write".to_owned());
    }
    match action.as_str() {
        "check" => check(root),
        "write" => write(root),
        _ => Err(format!(
            "unknown frontend-wasm-codegen action: {action}; expected check or write"
        )),
    }
}

fn utils_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  kgwClean2SafeText as wasmKgwClean2SafeText,
  pick as wasmPick,
  toEnglishDigits as wasmToEnglishDigits,
  toNumber as wasmToNumber,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function toEnglishDigits(value) {
  return wasmToEnglishDigits(value);
}

export function pick(...values) {
  return wasmPick(values);
}

export function toNumber(value, fallback = 0) {
  return wasmToNumber(value, fallback);
}

export function kgwClean2SafeText(value) {
  return wasmKgwClean2SafeText(value);
}
"#
    .to_owned()
}

fn date_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  kgwClean2DayToSeconds as wasmKgwClean2DayToSeconds,
  kgwDayToEpochSeconds as wasmKgwDayToEpochSeconds,
  kgwTransactionDateKey as wasmKgwTransactionDateKey,
  kgwTxDayToEpochSeconds as wasmKgwTxDayToEpochSeconds,
  normalizeDateInputValue as wasmNormalizeDateInputValue,
  parseDateSeconds as wasmParseDateSeconds,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function normalizeDateInputValue(value) {
  return wasmNormalizeDateInputValue(value);
}

export function parseDateSeconds(dateText, endOfDay = false) {
  return wasmParseDateSeconds(dateText, endOfDay);
}

export function kgwDayToEpochSeconds(day, endOfDay = false) {
  return wasmKgwDayToEpochSeconds(day, endOfDay);
}

export function kgwTxDayToEpochSeconds(day, endOfDay = false) {
  return wasmKgwTxDayToEpochSeconds(day, endOfDay);
}

export function kgwClean2DayToSeconds(day, endOfDay = false) {
  return wasmKgwClean2DayToSeconds(day, endOfDay);
}

export function kgwTransactionDateKey(row) {
  return wasmKgwTransactionDateKey(row);
}
"#
    .to_owned()
}

fn formatting_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  formatKas as wasmFormatKas,
  formatUsd as wasmFormatUsd,
  kgwClean2Kas as wasmKgwClean2Kas,
  kgwClean2Usd as wasmKgwClean2Usd,
  kgwSummaryFormatKas as wasmKgwSummaryFormatKas,
  kgwSummaryFormatUsd as wasmKgwSummaryFormatUsd,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function formatKas(value) {
  return wasmFormatKas(value);
}

export function formatUsd(value) {
  return wasmFormatUsd(value);
}

export function kgwSummaryFormatKas(value) {
  return wasmKgwSummaryFormatKas(value);
}

export function kgwSummaryFormatUsd(value) {
  return wasmKgwSummaryFormatUsd(value);
}

export function kgwClean2Kas(value) {
  return wasmKgwClean2Kas(value);
}

export function kgwClean2Usd(value) {
  return wasmKgwClean2Usd(value);
}
"#
    .to_owned()
}

fn header_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  parseHeaderUsdPrice as wasmParseHeaderUsdPrice,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function parseHeaderUsdPrice() {
  return wasmParseHeaderUsdPrice();
}
"#
    .to_owned()
}

fn status_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  applyStatusTone as wasmApplyStatusTone,
  renderStatusSummary as wasmRenderStatusSummary,
  statusTone as wasmStatusTone,
} from "../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function statusTone(state) {
  return wasmStatusTone(state);
}

export function applyStatusTone(element, state) {
  return wasmApplyStatusTone(element, state);
}

export function renderStatusSummary(element, text) {
  return wasmRenderStatusSummary(element, text);
}
"#
    .to_owned()
}

fn adapters() -> [AdapterGenerator; 5] {
    [
        (UTILS_ADAPTER_RELATIVE, utils_adapter_source),
        (DATE_ADAPTER_RELATIVE, date_adapter_source),
        (FORMATTING_ADAPTER_RELATIVE, formatting_adapter_source),
        (HEADER_ADAPTER_RELATIVE, header_adapter_source),
        (STATUS_ADAPTER_RELATIVE, status_adapter_source),
    ]
}

fn temp_output(root: &Path) -> PathBuf {
    root.join("target").join("kgw-frontend-wasm-codegen")
}

fn verify_wasm_pack() -> Result<(), String> {
    let output = Command::new("wasm-pack")
        .arg("--version")
        .output()
        .map_err(|error| format!("wasm-pack is required but could not start: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "wasm-pack --version failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let actual = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    if actual != WASM_PACK_VERSION {
        return Err(format!(
            "frontend WASM codegen requires {WASM_PACK_VERSION}; found {actual}"
        ));
    }
    Ok(())
}

fn build_temp(root: &Path) -> Result<PathBuf, String> {
    verify_wasm_pack()?;
    let output_dir = temp_output(root);
    if output_dir.exists() {
        fs::remove_dir_all(&output_dir)
            .map_err(|error| format!("failed to clear {}: {error}", output_dir.display()))?;
    }

    let output = Command::new("wasm-pack")
        .current_dir(root)
        .env("RUSTUP_TOOLCHAIN", "1.98.1")
        .args([
            "build",
            CRATE_RELATIVE,
            "--target",
            "web",
            "--release",
            "--out-dir",
        ])
        .arg(&output_dir)
        .args([
            "--out-name",
            "kgw_frontend_wasm",
            "--no-typescript",
            "--no-pack",
            "--no-opt",
        ])
        .output()
        .map_err(|error| format!("failed to start wasm-pack build: {error}"))?;

    if !output.status.success() {
        return Err(format!(
            "frontend WASM build failed\nstdout={}\nstderr={}",
            String::from_utf8_lossy(&output.stdout).trim(),
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }

    for name in [JS_NAME, WASM_NAME] {
        if !output_dir.join(name).is_file() {
            return Err(format!(
                "wasm-pack did not produce required artifact: {}",
                output_dir.join(name).display()
            ));
        }
    }
    Ok(output_dir)
}

fn same_bytes(left: &Path, right: &Path) -> Result<bool, String> {
    let left_bytes =
        fs::read(left).map_err(|error| format!("failed to read {}: {error}", left.display()))?;
    let right_bytes =
        fs::read(right).map_err(|error| format!("failed to read {}: {error}", right.display()))?;
    Ok(left_bytes == right_bytes)
}

fn check(root: &Path) -> Result<String, String> {
    let built = build_temp(root)?;
    let tracked = root.join(GENERATED_RELATIVE);
    let mut drift = Vec::new();
    for name in [JS_NAME, WASM_NAME] {
        let tracked_file = tracked.join(name);
        if !tracked_file.is_file() || !same_bytes(&built.join(name), &tracked_file)? {
            drift.push(tracked_file.to_string_lossy().into_owned());
        }
    }

    let mut tracked_names = if tracked.is_dir() {
        fs::read_dir(&tracked)
            .map_err(|error| format!("failed to list {}: {error}", tracked.display()))?
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };
    tracked_names.sort();
    let expected_names = vec![JS_NAME.to_owned(), WASM_NAME.to_owned()];
    if tracked_names != expected_names {
        drift.push(format!(
            "{}:unexpected-generated-file-set={}",
            tracked.display(),
            tracked_names.join(",")
        ));
    }

    for (relative, source) in adapters() {
        let adapter = root.join(relative);
        let expected = source();
        let actual = fs::read_to_string(&adapter).unwrap_or_default();
        if actual != expected {
            drift.push(adapter.to_string_lossy().into_owned());
        }
    }

    if drift.is_empty() {
        Ok(format!(
            "FRONTEND_WASM_CODEGEN=PASS\nWASM_PACK_VERSION={}\nARTIFACT_COUNT=7",
            WASM_PACK_VERSION.trim_start_matches("wasm-pack ")
        ))
    } else {
        Err(format!(
            "FRONTEND_WASM_CODEGEN=FAIL\nDRIFT={}",
            drift.join(",")
        ))
    }
}

fn write(root: &Path) -> Result<String, String> {
    let built = build_temp(root)?;
    let tracked = root.join(GENERATED_RELATIVE);
    fs::create_dir_all(&tracked)
        .map_err(|error| format!("failed to create {}: {error}", tracked.display()))?;

    let mut changed = 0_usize;
    for name in [JS_NAME, WASM_NAME] {
        let source = built.join(name);
        let destination = tracked.join(name);
        let differs = !destination.is_file() || !same_bytes(&source, &destination)?;
        if differs {
            fs::copy(&source, &destination).map_err(|error| {
                format!(
                    "failed to copy {} to {}: {error}",
                    source.display(),
                    destination.display()
                )
            })?;
            changed += 1;
        }
    }

    for (relative, source) in adapters() {
        let adapter = root.join(relative);
        let expected = source();
        let actual = fs::read_to_string(&adapter).unwrap_or_default();
        if actual != expected {
            fs::write(&adapter, expected.as_bytes())
                .map_err(|error| format!("failed to write {}: {error}", adapter.display()))?;
            changed += 1;
        }
    }

    Ok(format!(
        "FRONTEND_WASM_CODEGEN=WRITE_PASS\nWASM_PACK_VERSION={}\nARTIFACT_COUNT=7\nCHANGED={changed}",
        WASM_PACK_VERSION.trim_start_matches("wasm-pack ")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adapter_is_generated_and_uses_rust_exports_only() {
        let adapter = utils_adapter_source();
        assert!(adapter.contains("@generated"));
        assert!(adapter.contains("await init();"));
        assert!(adapter.contains("wasmToEnglishDigits(value)"));
        assert!(adapter.contains("wasmPick(values)"));
        assert!(adapter.contains("wasmToNumber(value, fallback)"));
        assert!(adapter.contains("wasmKgwClean2SafeText(value)"));
        assert!(!adapter.contains("replaceAll("));
        assert!(!adapter.contains("Number.isFinite"));
        let date = date_adapter_source();
        assert!(date.contains("wasmNormalizeDateInputValue(value)"));
        assert!(date.contains("wasmKgwTransactionDateKey(row)"));
        let formatting = formatting_adapter_source();
        assert!(formatting.contains("wasmFormatKas(value)"));
        assert!(formatting.contains("wasmKgwClean2Usd(value)"));
        let header = header_adapter_source();
        assert!(header.contains("@generated"));
        assert!(header.contains("wasmParseHeaderUsdPrice()"));
        assert!(!header.contains("__kgwKaspaUsdPrice"));
        assert!(!header.contains("getElementById"));
        let status = status_adapter_source();
        assert!(status.contains("@generated"));
        assert!(status.contains("wasmStatusTone(state)"));
        assert!(status.contains("wasmApplyStatusTone(element, state)"));
        assert!(status.contains("wasmRenderStatusSummary(element, text)"));
        assert!(!status.contains("const GROUPS"));
        assert!(!status.contains("document.createElement"));
    }

    #[test]
    fn generated_paths_are_inside_frontend_or_target() {
        assert!(GENERATED_RELATIVE.starts_with("apps/kaspa-gateway-desktop/frontend/"));
        assert!(UTILS_ADAPTER_RELATIVE.ends_with("explorer.utils.js"));
        assert!(DATE_ADAPTER_RELATIVE.ends_with("explorer.date.js"));
        assert!(FORMATTING_ADAPTER_RELATIVE.ends_with("explorer.formatting.js"));
        assert!(HEADER_ADAPTER_RELATIVE.ends_with("explorer.header.js"));
        assert!(STATUS_ADAPTER_RELATIVE.ends_with("src/status.js"));
        let root = Path::new("repo");
        assert!(temp_output(root).starts_with(root.join("target")));
    }
}
