use std::fs;
use std::path::Path;

const TEMPLATES: [(&str, &str); 7] = [
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/analysis/analysis.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/analysis/analysis.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-bridge/kaspa-bridge.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-bridge/kaspa-bridge.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-node/kaspa-node.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-node/kaspa-node.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/log/log.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/log/log.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/settings/settings.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/settings/settings.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/top-addresses/top-addresses.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/top-addresses/top-addresses.template.js",
    ),
];

pub fn run_cli(args: &mut impl Iterator<Item = String>, root: &Path) -> Result<String, String> {
    let action = args.next().unwrap_or_else(|| "check".to_owned());
    if args.next().is_some() {
        return Err(
            "frontend-template-codegen accepts exactly one action: check or write".to_owned(),
        );
    }
    match action.as_str() {
        "check" => check(root),
        "write" => write(root),
        _ => Err(format!(
            "unknown frontend-template-codegen action: {action}; expected check or write"
        )),
    }
}

fn render_module(source_relative: &str, html: &str) -> Result<String, String> {
    let encoded = serde_json::to_string(html)
        .map_err(|error| format!("template JSON encoding failed for {source_relative}: {error}"))?;
    Ok(format!(
        "// @generated by cargo run --locked -p xtask -- frontend-template-codegen write\n\
// Source: {source_relative}\n\
// DO NOT EDIT THIS FILE DIRECTLY. Edit the declarative HTML source instead.\n\
const html = {encoded};\n\nexport default html;\n"
    ))
}

fn expected(root: &Path, html_relative: &str) -> Result<String, String> {
    let html_path = root.join(html_relative);
    let html = fs::read_to_string(&html_path)
        .map_err(|error| format!("failed to read {}: {error}", html_path.display()))?;
    render_module(html_relative, &html)
}

fn check(root: &Path) -> Result<String, String> {
    let mut drift = Vec::new();
    for (html_relative, js_relative) in TEMPLATES {
        let expected = expected(root, html_relative)?;
        let js_path = root.join(js_relative);
        let actual = fs::read_to_string(&js_path).map_err(|error| {
            format!(
                "failed to read generated wrapper {}: {error}",
                js_path.display()
            )
        })?;
        if actual != expected {
            drift.push(js_relative);
        }
    }

    if drift.is_empty() {
        Ok(format!(
            "FRONTEND_TEMPLATE_CODEGEN=PASS\nTEMPLATE_COUNT={}",
            TEMPLATES.len()
        ))
    } else {
        Err(format!(
            "FRONTEND_TEMPLATE_CODEGEN=FAIL\nDRIFT={}",
            drift.join(",")
        ))
    }
}

fn write(root: &Path) -> Result<String, String> {
    let mut changed = Vec::new();
    for (html_relative, js_relative) in TEMPLATES {
        let expected = expected(root, html_relative)?;
        let js_path = root.join(js_relative);
        let current = fs::read_to_string(&js_path).unwrap_or_default();
        if current != expected {
            fs::write(&js_path, expected.as_bytes())
                .map_err(|error| format!("failed to write {}: {error}", js_path.display()))?;
            changed.push(js_relative);
        }
    }

    Ok(format!(
        "FRONTEND_TEMPLATE_CODEGEN=WRITE_PASS\nTEMPLATE_COUNT={}\nCHANGED={}",
        TEMPLATES.len(),
        changed.len()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renderer_escapes_html_for_es_module_safely() {
        let html = "<div data-value=\"x\">line 1\nline \\ 2 \\u{2028}</div>";
        let rendered = render_module("fixture.template.html", html).unwrap();
        assert!(rendered.contains("@generated"));
        assert!(rendered.contains("const html = "));
        assert!(rendered.contains("\\n"));
        assert!(rendered.contains("\\\\"));
        assert!(rendered.ends_with("\nexport default html;\n"));
    }

    #[test]
    fn template_mapping_is_unique_and_html_backed() {
        let mut html = std::collections::BTreeSet::new();
        let mut js = std::collections::BTreeSet::new();
        for (html_path, js_path) in TEMPLATES {
            assert!(html.insert(html_path));
            assert!(js.insert(js_path));
            assert!(html_path.ends_with(".template.html"));
            assert!(js_path.ends_with(".template.js"));
        }
        assert_eq!(html.len(), 7);
        assert_eq!(js.len(), 7);
    }
}
