use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const WASM_PACK_VERSION: &str = "wasm-pack 0.15.0";
const CRATE_RELATIVE: &str = "crates/kaspa-gateway-frontend-wasm";
const GENERATED_RELATIVE: &str = "apps/kaspa-gateway-desktop/frontend/generated/kgw_frontend_wasm";
const MAIN_ADAPTER_RELATIVE: &str = "apps/kaspa-gateway-desktop/frontend/main.js";
const UTILS_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.utils.js";
const DATE_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.date.js";
const FORMATTING_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.formatting.js";
const HEADER_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.header.js";
const STATUS_ADAPTER_RELATIVE: &str = "apps/kaspa-gateway-desktop/frontend/src/status.js";
const SETTINGS_CONTRACT_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/settings-contract.js";
const SETTINGS_LAYOUT_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/settings-layout.js";
const SETTINGS_TAB_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/settings/settings.js";
const KASPA_NODE_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-node/kaspa-node.js";
const LOG_ADAPTER_RELATIVE: &str = "apps/kaspa-gateway-desktop/frontend/src/tabs/log/log.js";
const SHELL_LOGGER_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/core/shell-logger.js";
const HEADER_LIVE_METRICS_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/core/header-live-metrics.js";
const ANALYSIS_BINDING_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/analysis/analysis-rust-binding.js";
const ANALYSIS_TAB_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/analysis/analysis.js";
const TOP_ADDRESSES_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/top-addresses/top-addresses.js";
const EXPLORER_EXPORT_ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.export.js";
const JS_NAME: &str = "kgw_frontend_wasm.js";
const WASM_NAME: &str = "kgw_frontend_wasm_bg.wasm";
type AdapterGenerator = (&'static str, fn() -> String);

pub fn run_cli(args: &mut impl Iterator<Item = String>, root: &Path) -> Result<String, String> {
    let action = args.next().unwrap_or_else(|| "check".to_owned());
    if args.next().is_some() {
        return Err("frontend-wasm-codegen accepts exactly one action: check or write".to_owned());
    }
    match action.as_str() {
        "check" => check(root),
        "write" => write(root),
        _ => Err(format!(
            "unknown frontend-wasm-codegen action: {action}; expected check or write"
        )),
    }
}

fn utils_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  explorerAddressDiagnosticsSnapshot as wasmExplorerAddressDiagnosticsSnapshot,
  explorerAddressLookupKeys as wasmExplorerAddressLookupKeys,
  explorerApplyFontSize as wasmExplorerApplyFontSize,
  explorerApplyLocalBusyControls as wasmExplorerApplyLocalBusyControls,
  explorerBindFontSpinbox as wasmExplorerBindFontSpinbox,
  explorerCanonicalKaspaAddress as wasmExplorerCanonicalKaspaAddress,
  explorerBuildListRequest as wasmExplorerBuildListRequest,
  explorerClean2Request as wasmExplorerClean2Request,
  explorerDefaultDates as wasmExplorerDefaultDates,
  explorerEnsureFilterOptions as wasmExplorerEnsureFilterOptions,
  explorerFetchBalance as wasmExplorerFetchBalance,
  explorerForceResetDisplayFiltersToAll as wasmExplorerForceResetDisplayFiltersToAll,
  explorerForceSetControlsBusy as wasmExplorerForceSetControlsBusy,
  explorerForceSetTableMessage as wasmExplorerForceSetTableMessage,
  explorerFilterBuildRequest as wasmExplorerFilterBuildRequest,
  explorerFilterValue as wasmExplorerFilterValue,
  explorerInstallFilterSelectRepair as wasmExplorerInstallFilterSelectRepair,
  explorerInstallForceBusyBlocker as wasmExplorerInstallForceBusyBlocker,
  explorerInstallManualAddressSave as wasmExplorerInstallManualAddressSave,
  explorerIsKaspaAddress as wasmExplorerIsKaspaAddress,
  explorerLoadKnownAddressNames as wasmExplorerLoadKnownAddressNames,
  explorerLoadSavedAddresses as wasmExplorerLoadSavedAddresses,
  explorerManualAddressValue as wasmExplorerManualAddressValue,
  explorerNormalizeAddress as wasmExplorerNormalizeAddress,
  explorerNormalizeDirectionFilterValue as wasmExplorerNormalizeDirectionFilterValue,
  explorerNormalizeTxTypeFilterValue as wasmExplorerNormalizeTxTypeFilterValue,
  explorerReadFilterState as wasmExplorerReadFilterState,
  explorerRepairFilterSelects as wasmExplorerRepairFilterSelects,
  explorerLiveCoreAddress as wasmExplorerLiveCoreAddress,
  explorerLiveCoreMergeDays as wasmExplorerLiveCoreMergeDays,
  explorerLiveCoreMergeRecords as wasmExplorerLiveCoreMergeRecords,
  explorerLiveCoreReset as wasmExplorerLiveCoreReset,
  explorerLiveCoreRows as wasmExplorerLiveCoreRows,
  explorerLiveCoreSeedRows as wasmExplorerLiveCoreSeedRows,
  explorerLiveCoreShouldRender as wasmExplorerLiveCoreShouldRender,
  explorerMicroscopeApiShape as wasmExplorerMicroscopeApiShape,
  explorerMicroscopeElementReport as wasmExplorerMicroscopeElementReport,
  explorerMicroscopeError as wasmExplorerMicroscopeError,
  explorerMicroscopeLayoutReport as wasmExplorerMicroscopeLayoutReport,
  explorerMicroscopeLog as wasmExplorerMicroscopeLog,
  explorerMicroscopeStateReport as wasmExplorerMicroscopeStateReport,
  explorerMicroscopeWarn as wasmExplorerMicroscopeWarn,
  explorerClean2Body as wasmExplorerClean2Body,
  explorerClean2LoadDayTransactions as wasmExplorerClean2LoadDayTransactions,
  explorerClean2LoadSummaries as wasmExplorerClean2LoadSummaries,
  explorerClean2Log as wasmExplorerClean2Log,
  explorerClean2Section as wasmExplorerClean2Section,
  explorerExtractRowsFromUnifiedResult as wasmExplorerExtractRowsFromUnifiedResult,
  explorerLegacyListRequest as wasmExplorerLegacyListRequest,
  explorerLoadTransactionDaySummariesFromDb as wasmExplorerLoadTransactionDaySummariesFromDb,
  explorerLoadTransactionsForDay as wasmExplorerLoadTransactionsForDay,
  explorerLoadTransactionsForSingleDayFromDb as wasmExplorerLoadTransactionsForSingleDayFromDb,
  explorerFilterTrace as wasmExplorerFilterTrace,
  explorerInvokeCancelTransactions as wasmExplorerInvokeCancelTransactions,
  explorerInvokeDaySummaries as wasmExplorerInvokeDaySummaries,
  explorerInvokeGroupedTransactions as wasmExplorerInvokeGroupedTransactions,
  explorerInvokeUnifiedFetch as wasmExplorerInvokeUnifiedFetch,
  explorerSetStatus as wasmExplorerSetStatus,
  explorerEnsureState as wasmExplorerEnsureState,
  explorerSyncActionState as wasmExplorerSyncActionState,
  explorerSyncCurrentActionState as wasmExplorerSyncCurrentActionState,
  explorerInstallPriceRerender as wasmExplorerInstallPriceRerender,
  explorerUiTrace as wasmExplorerUiTrace,
  explorerNormalizeUnifiedResult as wasmExplorerNormalizeUnifiedResult,
  explorerDaySummaryRowsFromResult as wasmExplorerDaySummaryRowsFromResult,
  explorerNormalizeDaySummaries as wasmExplorerNormalizeDaySummaries,
  explorerRenderSummaries as wasmExplorerRenderSummaries,
  explorerRenderTable as wasmExplorerRenderTable,
  explorerClearTransactionTable as wasmExplorerClearTransactionTable,
  explorerResetFilters as wasmExplorerResetFilters,
  explorerLoadAndRenderDaySummaries as wasmExplorerLoadAndRenderDaySummaries,
  explorerSummaryCurrentUsdPrice as wasmExplorerSummaryCurrentUsdPrice,
  explorerSummaryUsdForKas as wasmExplorerSummaryUsdForKas,
  explorerSummaryUsdForSummary as wasmExplorerSummaryUsdForSummary,
  explorerRefreshAddressName as wasmExplorerRefreshAddressName,
  explorerSaveAddressToDatabase as wasmExplorerSaveAddressToDatabase,
  explorerSaveManualAddress as wasmExplorerSaveManualAddress,
  explorerSetTableFontSize as wasmExplorerSetTableFontSize,
  kgwClean2SafeText as wasmKgwClean2SafeText,
  pick as wasmPick,
  toEnglishDigits as wasmToEnglishDigits,
  toNumber as wasmToNumber,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();
wasmExplorerInstallFilterSelectRepair();

export function toEnglishDigits(value) {
  return wasmToEnglishDigits(value);
}

export function pick(...values) {
  return wasmPick(values);
}

export function toNumber(value, fallback = 0) {
  return wasmToNumber(value, fallback);
}

export function kgwClean2SafeText(value) {
  return wasmKgwClean2SafeText(value);
}

export function kgwEnsureExplorerState() {
  return wasmExplorerEnsureState();
}

export function kgwSummaryCurrentUsdPrice() {
  return wasmExplorerSummaryCurrentUsdPrice();
}

export function kgwClean2UsdPrice() {
  return wasmExplorerSummaryCurrentUsdPrice();
}

export function kgwSummaryUsdForKas(valueKas) {
  return wasmExplorerSummaryUsdForKas(valueKas);
}

export function kgwNormalizeDaySummaries(result) {
  return wasmExplorerNormalizeDaySummaries(result);
}

export function kgwClean2NormalizeSummaries(result) {
  return wasmExplorerNormalizeDaySummaries(result);
}

export function syncActionState(section) {
  return wasmExplorerSyncCurrentActionState(section);
}

export function kgwInstallExplorerPriceRerenderV1() {
  return wasmExplorerInstallPriceRerender();
}

export async function kgwRenderDaySummaries(section, rows, statusText = "") {
  return wasmExplorerRenderSummaries(section, rows, String(statusText ?? ""));
}

export async function kgwRenderDaySummariesDirect(section, summaries, statusText = "") {
  return wasmExplorerRenderSummaries(section, summaries, String(statusText ?? ""));
}

export async function kgwClean2RenderSummaries(section, rows, statusText = "") {
  return wasmExplorerRenderSummaries(section, rows, String(statusText ?? ""));
}

export function renderTable(section) {
  return wasmExplorerRenderTable(section);
}

export function clearExplorerTransactionTable(section, reason = "cleared", options = {}) {
  return wasmExplorerClearTransactionTable(section, String(reason ?? "cleared"), options ?? {});
}

export function resetFilters(section) {
  return wasmExplorerResetFilters(section);
}

export async function kgwLoadAndRenderDaySummaries(section, address, startTs, endTs, statusText = "") {
  return await wasmExplorerLoadAndRenderDaySummaries(section, address, startTs, endTs, String(statusText ?? ""));
}

export function kgwSummaryUsdForSummary(summary) {
  return wasmExplorerSummaryUsdForSummary(summary);
}

export function kgwLiveCoreAddress() {
  return wasmExplorerLiveCoreAddress();
}

export function kgwLiveCoreReset(address) {
  return wasmExplorerLiveCoreReset(address);
}

export function kgwLiveCoreSeedRows(address, rows) {
  return wasmExplorerLiveCoreSeedRows(address, rows);
}

export function kgwLiveCoreMergeRecords(records) {
  return wasmExplorerLiveCoreMergeRecords(records);
}

export function kgwLiveCoreMergeDays(days) {
  return wasmExplorerLiveCoreMergeDays(days);
}

export function kgwLiveCoreRows() {
  return wasmExplorerLiveCoreRows();
}

export function kgwLiveCoreShouldRender(payload) {
  return wasmExplorerLiveCoreShouldRender(payload);
}

export function kgwNormalizeUnifiedResult(result) {
  return wasmExplorerNormalizeUnifiedResult(result);
}

export function kgwDaySummaryRowsFromResult(result) {
  return wasmExplorerDaySummaryRowsFromResult(result);
}

export function microscopeLog(stage, details = {}) {
  wasmExplorerMicroscopeLog(String(stage ?? ""), details ?? {});
}

export function microscopeWarn(stage, details = {}) {
  wasmExplorerMicroscopeWarn(String(stage ?? ""), details ?? {});
}

export function microscopeError(stage, error, details = {}) {
  wasmExplorerMicroscopeError(String(stage ?? ""), error, details ?? {});
}

export function microscopeElementReport(section) {
  return wasmExplorerMicroscopeElementReport(section);
}

export function microscopeLayoutReport(section) {
  wasmExplorerMicroscopeLayoutReport(section);
}

export function microscopeStateLog(label, snapshot) {
  wasmExplorerMicroscopeStateReport(String(label ?? "STATE REPORT"), snapshot ?? {});
}

export function microscopeApiShape(label, value) {
  wasmExplorerMicroscopeApiShape(String(label ?? ""), value);
}

export async function kgwInvokeExplorerUnifiedFetch(request) {
  return await wasmExplorerInvokeUnifiedFetch(request);
}

export async function kgwInvokeExplorerCancelTransactionsR57D4(requestId) {
  return await wasmExplorerInvokeCancelTransactions(requestId);
}

export async function kgwInvokeExplorerGroupedTransactions(request) {
  return await wasmExplorerInvokeGroupedTransactions(request);
}

export async function kgwInvokeExplorerDaySummaries(request) {
  return await wasmExplorerInvokeDaySummaries(request);
}

export function setStatus(section, message, state = "info") {
  return wasmExplorerSetStatus(section, message, state);
}

export function kgwExplorerSyncActionState(section, busy, rowsCount = 0, filteredRowsCount = 0) {
  return wasmExplorerSyncActionState(section, Boolean(busy), rowsCount, filteredRowsCount);
}

export function extractRowsFromUnifiedResult(result) {
  return wasmExplorerExtractRowsFromUnifiedResult(result);
}

export function kgwExplorerUiTraceR53B3(action, phase, details = {}) {
  return wasmExplorerUiTrace(action, phase, details);
}

export function kgwFilterTrace(label, payload = {}) {
  return wasmExplorerFilterTrace(label, payload);
}

export function kgwExplorerListRequest(section, address, startTs, endTs) {
  return wasmExplorerLegacyListRequest(section, address, startTs, endTs);
}

export async function kgwLoadTransactionDaySummariesFromDb(section, address, startTs, endTs) {
  return await wasmExplorerLoadTransactionDaySummariesFromDb(section, address, startTs, endTs);
}

export async function kgwLoadTransactionsForSingleDayFromDb(section, address, day) {
  return await wasmExplorerLoadTransactionsForSingleDayFromDb(section, address, day);
}

export async function kgwLoadTransactionsForDay(section, address, day) {
  return await wasmExplorerLoadTransactionsForDay(section, address, day);
}

export function kgwClean2Log(label, payload = {}) {
  return wasmExplorerClean2Log(String(label ?? ""), payload ?? {});
}

export function kgwClean2Section(section) {
  return wasmExplorerClean2Section(section);
}

export function kgwClean2Body(section) {
  return wasmExplorerClean2Body(section);
}

export async function kgwClean2LoadSummaries(section, address, startTs, endTs) {
  return await wasmExplorerClean2LoadSummaries(section, address, startTs, endTs);
}

export async function kgwClean2LoadDayTransactions(section, address, day) {
  return await wasmExplorerClean2LoadDayTransactions(section, address, day);
}

export function setTableFontSize(section) {
  return wasmExplorerSetTableFontSize(section);
}

export function kgwApplyExplorerFontSize(section, rawValue) {
  return wasmExplorerApplyFontSize(section, rawValue);
}

export function kgwBindFontSpinbox(section) {
  return wasmExplorerBindFontSpinbox(section);
}

export function defaultDates(section) {
  return wasmExplorerDefaultDates(section);
}

export function kgwApplyExplorerLocalBusyControls(section, busy) {
  return wasmExplorerApplyLocalBusyControls(section, busy);
}

export function kgwForceSetTableMessage(section, message) {
  return wasmExplorerForceSetTableMessage(section, String(message ?? ""));
}

export function kgwForceResetDisplayFiltersToAll(section) {
  return wasmExplorerForceResetDisplayFiltersToAll(section);
}

export function kgwForceSetControlsBusy(section, busy, mode = "normal") {
  return wasmExplorerForceSetControlsBusy(section, Boolean(busy), String(mode ?? "normal"));
}

export function kgwInstallForceBusyBlocker() {
  return wasmExplorerInstallForceBusyBlocker();
}

export function kgwEnsureExplorerFilterOptions(section) {
  return wasmExplorerEnsureFilterOptions(section);
}

export function kgwReadExplorerFilterState(section) {
  return wasmExplorerReadFilterState(section);
}

export function kgwBuildExplorerListRequest(section, address, startTs, endTs, limit = 10000) {
  return wasmExplorerBuildListRequest(section, address, startTs, endTs, limit);
}

export function kgwFilterValue(selector, section, fallback = "ALL") {
  return wasmExplorerFilterValue(selector, section, fallback);
}

export function kgwFilterBuildRequest(section, address, startTs, endTs, limit = 10000) {
  return wasmExplorerFilterBuildRequest(section, address, startTs, endTs, limit);
}

export function kgwNormalizeTxTypeFilterValue(value) {
  return wasmExplorerNormalizeTxTypeFilterValue(value);
}

export function kgwNormalizeDirectionFilterValue(value) {
  return wasmExplorerNormalizeDirectionFilterValue(value);
}

export function kgwRepairExplorerFilterSelects(section) {
  return wasmExplorerRepairFilterSelects(section);
}

export function kgwClean2Request(section, address, startTs, endTs, limit) {
  return wasmExplorerClean2Request(section, address, startTs, endTs, limit);
}

export function normalizeAddress(value) {
  return wasmExplorerNormalizeAddress(value);
}

export function isKaspaAddress(value) {
  return wasmExplorerIsKaspaAddress(value);
}

export function addressLookupKeys(value) {
  return wasmExplorerAddressLookupKeys(value);
}

export async function kgwCanonicalKaspaAddress(value) {
  return await wasmExplorerCanonicalKaspaAddress(value);
}

export async function loadKnownAddressNames() {
  return await wasmExplorerLoadKnownAddressNames();
}

export async function saveAddressToDatabase(address, name = "") {
  return await wasmExplorerSaveAddressToDatabase(address, name);
}

export async function refreshAddressName(section, address) {
  return await wasmExplorerRefreshAddressName(section, address);
}

export async function loadSavedAddresses(section) {
  return await wasmExplorerLoadSavedAddresses(section);
}

export async function fetchBalance(section, address) {
  return await wasmExplorerFetchBalance(section, address);
}

export function explorerAddressDiagnosticsSnapshot(address) {
  return wasmExplorerAddressDiagnosticsSnapshot(address);
}

export function kgwExplorerManualAddressValue(section) {
  return wasmExplorerManualAddressValue(section);
}

export function kgwExplorerIsKaspaAddress(value) {
  return wasmExplorerIsKaspaAddress(value);
}

export async function kgwExplorerSaveManualAddress(section) {
  return await wasmExplorerSaveManualAddress(section);
}

export function kgwInstallExplorerManualAddressSave() {
  return wasmExplorerInstallManualAddressSave();
}
"#
    .to_owned()
}

fn date_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  kgwClean2DayToSeconds as wasmKgwClean2DayToSeconds,
  kgwDayToEpochSeconds as wasmKgwDayToEpochSeconds,
  kgwTransactionDateKey as wasmKgwTransactionDateKey,
  kgwTxDayToEpochSeconds as wasmKgwTxDayToEpochSeconds,
  normalizeDateInputValue as wasmNormalizeDateInputValue,
  parseDateSeconds as wasmParseDateSeconds,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function normalizeDateInputValue(value) {
  return wasmNormalizeDateInputValue(value);
}

export function parseDateSeconds(dateText, endOfDay = false) {
  return wasmParseDateSeconds(dateText, endOfDay);
}

export function kgwDayToEpochSeconds(day, endOfDay = false) {
  return wasmKgwDayToEpochSeconds(day, endOfDay);
}

export function kgwTxDayToEpochSeconds(day, endOfDay = false) {
  return wasmKgwTxDayToEpochSeconds(day, endOfDay);
}

export function kgwClean2DayToSeconds(day, endOfDay = false) {
  return wasmKgwClean2DayToSeconds(day, endOfDay);
}

export function kgwTransactionDateKey(row) {
  return wasmKgwTransactionDateKey(row);
}
"#
    .to_owned()
}

fn formatting_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  formatKas as wasmFormatKas,
  formatUsd as wasmFormatUsd,
  kgwClean2Kas as wasmKgwClean2Kas,
  kgwClean2Usd as wasmKgwClean2Usd,
  kgwSummaryFormatKas as wasmKgwSummaryFormatKas,
  kgwSummaryFormatUsd as wasmKgwSummaryFormatUsd,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function formatKas(value) {
  return wasmFormatKas(value);
}

export function formatUsd(value) {
  return wasmFormatUsd(value);
}

export function kgwSummaryFormatKas(value) {
  return wasmKgwSummaryFormatKas(value);
}

export function kgwSummaryFormatUsd(value) {
  return wasmKgwSummaryFormatUsd(value);
}

export function kgwClean2Kas(value) {
  return wasmKgwClean2Kas(value);
}

export function kgwClean2Usd(value) {
  return wasmKgwClean2Usd(value);
}
"#
    .to_owned()
}

fn header_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  parseHeaderUsdPrice as wasmParseHeaderUsdPrice,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function parseHeaderUsdPrice() {
  return wasmParseHeaderUsdPrice();
}
"#
    .to_owned()
}

fn status_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  applyStatusTone as wasmApplyStatusTone,
  renderStatusSummary as wasmRenderStatusSummary,
  runtimePresentation as wasmRuntimePresentation,
  runtimeObservationSummary as wasmRuntimeObservationSummary,
  statusTone as wasmStatusTone,
} from "../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function statusTone(state) {
  return wasmStatusTone(state);
}

export function applyStatusTone(element, state) {
  return wasmApplyStatusTone(element, state);
}

export function renderStatusSummary(element, text) {
  return wasmRenderStatusSummary(element, text);
}

export function runtimePresentation(state) {
  return wasmRuntimePresentation(state);
}

export function runtimeObservationSummary(fields = {}, running = false, cpuOnly = false) {
  return wasmRuntimeObservationSummary(fields, running, cpuOnly);
}
"#
    .to_owned()
}

fn settings_contract_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns settings schema, validation, DOM error rendering, and confirmation behavior.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
export { runtimePresentation, runtimeObservationSummary } from "./status.js";
import init, {
  settingsBridgeFieldEnabled as wasmBridgeFieldEnabled,
  settingsBridgeManaged as wasmBridgeManaged,
  settingsAddressNormalize as wasmAddressNormalize,
  settingsAddressShort as wasmAddressShort,
  settingsAddressesClearFields as wasmAddressesClearFields,
  settingsAddressesIncrementRestoreEpoch as wasmAddressesIncrementRestoreEpoch,
  settingsAddressesInstallAll as wasmAddressesInstallAll,
  settingsAddressesInstallIo as wasmAddressesInstallIo,
  settingsAddressesNow as wasmAddressesNow,
  settingsAddressesOpenExplorer as wasmAddressesOpenExplorer,
  settingsAddressesRefresh as wasmAddressesRefresh,
  settingsAddressesRenderRows as wasmAddressesRenderRows,
  settingsAddressesRestoreEpoch as wasmAddressesRestoreEpoch,
  settingsAddressesSetStatus as wasmAddressesSetStatus,
  settingsBridgeOptional as wasmBridgeOptional,
  settingsBridgeRequired as wasmBridgeRequired,
  settingsConfirmUserAction as wasmConfirmUserAction,
  settingsDisplayChecksWithDefaults as wasmDisplayChecksWithDefaults,
  settingsDisplayPreferences as wasmDisplayPreferences,
  settingsDisplayStateMissingContract as wasmDisplayStateMissingContract,
  settingsDatabaseInstall as wasmDatabaseInstall,
  settingsDatabaseInstallMaintenance as wasmDatabaseInstallMaintenance,
  settingsDatabaseRefresh as wasmDatabaseRefresh,
  settingsDatabaseRenderRows as wasmDatabaseRenderRows,
  settingsDiagnosticsInstall as wasmDiagnosticsInstall,
  settingsDbKindFromFileName as wasmDbKindFromFileName,
  settingsEndpoint as wasmEndpoint,
  settingsExplorerAddress as wasmExplorerAddress,
  settingsExplorerUrl as wasmExplorerUrl,
  settingsIsHost as wasmIsHost,
  settingsIsKaspaAddress as wasmIsKaspaAddress,
  settingsIsLoopback as wasmIsLoopback,
  settingsIsPort as wasmIsPort,
  settingsListenersOverlap as wasmListenersOverlap,
  settingsNodeDangerous as wasmNodeDangerous,
  settingsNodeEndpoints as wasmNodeEndpoints,
  settingsNodeFieldEnabled as wasmNodeFieldEnabled,
  settingsNodeManaged as wasmNodeManaged,
  settingsNodeOptional as wasmNodeOptional,
  settingsNodeRequired as wasmNodeRequired,
  settingsPathsApply as wasmPathsApply,
  settingsPathsBrowse as wasmPathsBrowse,
  settingsPathsLoadDefaults as wasmPathsLoadDefaults,
  settingsPathsRepairBeforeSave as wasmPathsRepairBeforeSave,
  settingsPersistenceLoadSaved as wasmPersistenceLoadSaved,
  settingsPersistenceResetDefaults as wasmPersistenceResetDefaults,
  settingsPersistenceSave as wasmPersistenceSave,
  settingsProfilesInstall as wasmProfilesInstall,
  settingsProfilesRefresh as wasmProfilesRefresh,
  settingsProfilesSelectEndpoint as wasmProfilesSelectEndpoint,
  settingsDisplayApplyShellFromState as wasmDisplayApplyShellFromState,
  settingsDisplayBindMinimumGuards as wasmDisplayBindMinimumGuards,
  settingsDisplayBuildCanonicalDefaultState as wasmDisplayBuildCanonicalDefaultState,
  settingsDisplayEnsureDefaults as wasmDisplayEnsureDefaults,
  settingsDisplayReapplyState as wasmDisplayReapplyState,
  settingsDisplayStateLooksLegacyAllSelected as wasmDisplayStateLooksLegacyAllSelected,
  settingsDisplayValidateForSave as wasmDisplayValidateForSave,
  settingsRenderFieldErrors as wasmRenderFieldErrors,
  settingsStateActivateInner as wasmStateActivateInner,
  settingsStateActivateOuter as wasmStateActivateOuter,
  settingsStateApply as wasmStateApply,
  settingsStateCollect as wasmStateCollect,
  settingsStateCombineUrl as wasmStateCombineUrl,  settingsSelectedDisplayKeys as wasmSelectedDisplayKeys,
  settingsSplitEndpoint as wasmSplitEndpoint,
  settingsToWesternDigits as wasmToWesternDigits,
  settingsValidateBridgeForm as wasmValidateBridgeForm,
  settingsValidateNodeForm as wasmValidateNodeForm,
} from "../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export const NODE_ENDPOINTS = wasmNodeEndpoints();
export const NODE_MANAGED = wasmNodeManaged();
export const NODE_REQUIRED = wasmNodeRequired();
export const NODE_OPTIONAL = new Set(wasmNodeOptional());
export const NODE_DANGEROUS = wasmNodeDangerous();

export const BRIDGE_MANAGED = wasmBridgeManaged();
export const BRIDGE_REQUIRED = new Set(wasmBridgeRequired());
export const BRIDGE_OPTIONAL = new Set(wasmBridgeOptional());

export function isHost(value) {
  return wasmIsHost(value);
}
export function isPort(value) {
  return wasmIsPort(value);
}
export function endpoint(host, port) {
  return wasmEndpoint(host, port);
}
export function splitEndpoint(value) {
  return wasmSplitEndpoint(value);
}
export function isLoopback(host) {
  return wasmIsLoopback(host);
}
export function listenersOverlap(a, b) {
  return wasmListenersOverlap(a, b);
}
export function nodeFieldEnabled(name, values, options = {}) {
  return wasmNodeFieldEnabled(name, values, options);
}
export function validateNodeForm(values, options, network) {
  return wasmValidateNodeForm(values, options, network);
}
export function renderFieldErrors(root, prefix, errors) {
  return wasmRenderFieldErrors(root, prefix, errors);
}
export function settingsAddressShort(value) {
  return wasmAddressShort(value);
}

export function settingsIsKaspaAddress(value) {
  return wasmIsKaspaAddress(value);
}

export function settingsAddressNormalize(record) {
  return wasmAddressNormalize(record);
}

export function settingsAddressesInstallAll() {
  return wasmAddressesInstallAll();
}

export function settingsAddressesInstallIo() {
  return wasmAddressesInstallIo();
}

export async function settingsAddressesRefresh() {
  return await wasmAddressesRefresh();
}

export async function settingsAddressesRenderRows(records, options = {}) {
  return await wasmAddressesRenderRows(records, options);
}

export function settingsAddressesClearFields() {
  return wasmAddressesClearFields();
}

export function settingsAddressesSetStatus(message, state = "info") {
  return wasmAddressesSetStatus(message, state);
}

export function settingsAddressesNow() {
  return wasmAddressesNow();
}

export function settingsAddressesIncrementRestoreEpoch() {
  return wasmAddressesIncrementRestoreEpoch();
}

export function settingsAddressesRestoreEpoch() {
  return wasmAddressesRestoreEpoch();
}

export function settingsAddressesOpenExplorer(address) {
  return wasmAddressesOpenExplorer(address);
}

export function settingsPathsApply(paths, force = false) {
  return wasmPathsApply(paths, force);
}

export async function settingsPathsBrowse(targetId) {
  return await wasmPathsBrowse(targetId);
}

export async function settingsPathsLoadDefaults(reason = "settings") {
  return await wasmPathsLoadDefaults(reason);
}

export async function settingsPathsRepairBeforeSave() {
  return await wasmPathsRepairBeforeSave();
}

export async function settingsPersistenceSave() {
  return await wasmPersistenceSave();
}

export async function settingsPersistenceResetDefaults(options = {}) {
  return await wasmPersistenceResetDefaults(options);
}

export function settingsPersistenceLoadSaved() {
  return wasmPersistenceLoadSaved();
}

export function settingsProfilesInstall() {
  return wasmProfilesInstall();
}

export async function settingsProfilesRefresh() {
  return await wasmProfilesRefresh();
}

export function settingsProfilesSelectEndpoint(row) {
  return wasmProfilesSelectEndpoint(row);
}

export function settingsDbKindFromFileName(value) {
  return wasmDbKindFromFileName(value);
}

export function settingsDatabaseRenderRows(rows) {
  return wasmDatabaseRenderRows(rows);
}

export async function settingsDatabaseRefresh() {
  return await wasmDatabaseRefresh();
}

export function settingsDatabaseInstall() {
  return wasmDatabaseInstall();
}

export function settingsDatabaseInstallMaintenance() {
  return wasmDatabaseInstallMaintenance();
}

export function settingsDiagnosticsInstall() {
  return wasmDiagnosticsInstall();
}

export function settingsStateActivateOuter(tab) {
  return wasmStateActivateOuter(tab);
}

export function settingsStateActivateInner(tab) {
  return wasmStateActivateInner(tab);
}

export function settingsStateCombineUrl() {
  return wasmStateCombineUrl();
}

export function settingsStateCollect() {
  return wasmStateCollect();
}

export function settingsStateApply(state) {
  return wasmStateApply(state);
}

export function settingsDisplayEnsureDefaults(reason = "default") {
  return wasmDisplayEnsureDefaults(reason);
}

export function settingsDisplayValidateForSave() {
  return wasmDisplayValidateForSave();
}

export function settingsDisplayBindMinimumGuards() {
  return wasmDisplayBindMinimumGuards();
}

export function settingsDisplayBuildCanonicalDefaultState(reason = "display-defaults-r65", persist = false) {
  return wasmDisplayBuildCanonicalDefaultState(reason, persist);
}

export function settingsDisplayReapplyState(state, reason = "display-state-r65") {
  return wasmDisplayReapplyState(state, reason);
}

export function settingsDisplayStateLooksLegacyAllSelected(state) {
  return wasmDisplayStateLooksLegacyAllSelected(state);
}

export function settingsDisplayApplyShellFromState(state, reason = "settings") {
  return wasmDisplayApplyShellFromState(state, reason);
}

export function settingsExplorerAddress(value) {
  return wasmExplorerAddress(value);
}

export function settingsExplorerUrl(value) {
  return wasmExplorerUrl(value);
}

export function bridgeFieldEnabled(name, values, options = {}) {
  return wasmBridgeFieldEnabled(name, values, options);
}
export function validateBridgeForm(values, options, network) {
  return wasmValidateBridgeForm(values, options, network);
}
export function settingsToWesternDigits(value) {
  return wasmToWesternDigits(value);
}

export function settingsDisplayChecksWithDefaults(checks, knownEntries = []) {
  return wasmDisplayChecksWithDefaults(checks, knownEntries);
}

export function settingsSelectedDisplayKeys(checks, prefix) {
  return Array.from(wasmSelectedDisplayKeys(checks, prefix));
}

export function settingsDisplayStateMissingContract(checks) {
  return wasmDisplayStateMissingContract(checks);
}

export function settingsDisplayPreferences(checks) {
  return wasmDisplayPreferences(checks);
}

export async function confirmUserAction(message) {
  return (await wasmConfirmUserAction(message)) === true;
}
"#
    .to_owned()
}

fn settings_layout_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Settings V2 help metadata, rendering, DOM orchestration, accessibility, and layout behavior.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  settingsLayoutDecorateFields as wasmDecorateFields,
  settingsLayoutDecorateGlobal as wasmDecorateGlobal,
  settingsLayoutFieldKind as wasmFieldKind,
  settingsLayoutGlobalHelpIds as wasmGlobalHelpIds,
  settingsLayoutHelpI18nKeys as wasmHelpKeys,
  settingsLayoutInstall as wasmInstall,
  settingsLayoutInstallGlobal as wasmInstallGlobal,
  settingsLayoutInstallManageAddressesClean as wasmInstallManageAddressesClean,
  settingsLayoutInstallSettingsI18nBindings as wasmInstallSettingsI18nBindings,
  settingsLayoutRenderTabs as wasmRenderTabs,
  settingsLayoutRevealField as wasmRevealField,
  settingsLayoutSetFieldState as wasmSetFieldState,
} from "../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export const SETTING_HELP_I18N_KEYS = Object.freeze(wasmHelpKeys());
export const GLOBAL_SETTING_HELP_IDS = Object.freeze(Array.from(wasmGlobalHelpIds()));

export function settingFieldKind(field) {
  return wasmFieldKind(field);
}

export function renderSettingsTabs(scope, net, groups) {
  return wasmRenderTabs(scope, net, groups);
}

export function decorateSettingsFields(root) {
  return wasmDecorateFields(root);
}

export function setSettingFieldState(field, message = "") {
  return wasmSetFieldState(field, String(message || ""));
}

export function revealSettingsField(field) {
  return wasmRevealField(field);
}

export function installSettingsLayout(root) {
  return wasmInstall(root);
}

export function decorateGlobalSettings(root) {
  return wasmDecorateGlobal(root);
}

export function installGlobalSettingsLayout(root) {
  return wasmInstallGlobal(root);
}

export function installManageAddressesCleanLayout() {
  return wasmInstallManageAddressesClean();
}

export function installSettingsI18nBindings() {
  return wasmInstallSettingsI18nBindings();
}
"#
    .to_owned()
}

fn shell_logger_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns frontend log buffering, fatal rendering, global error capture, and Tauri forwarding.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  shellLoggerClearBufferedLogs as wasmClearBufferedLogs,
  shellLoggerFatal as wasmKgwFatal,
  shellLoggerGetBufferedLogs as wasmGetBufferedLogs,
  shellLoggerInstall as wasmInstallShellLogger,
  shellLoggerLog as wasmKgwLog,
} from "../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function kgwLog(level, message, details = "", source = "frontend") {
  return wasmKgwLog(level, message, details, source);
}

export function createLogger(source) {
  return {
    log: (message, details = "") => kgwLog("log", message, details, source),
    warn: (message, details = "") => kgwLog("warn", message, details, source),
    error: (message, details = "") => kgwLog("error", message, details, source),
  };
}

export function kgwFatal(error, source = "shell") {
  return wasmKgwFatal(error, source);
}

export function getBufferedLogs() {
  return wasmGetBufferedLogs();
}

export function clearBufferedLogs() {
  return wasmClearBufferedLogs();
}

if (!window.__KGW_LOGGER_INSTALLED) {
  window.kgwLog = kgwLog;
  window.kgwFatal = kgwFatal;
  window.kgwCreateLogger = createLogger;
  window.kgwGetBufferedLogs = getBufferedLogs;
  window.kgwClearBufferedLogs = clearBufferedLogs;
  wasmInstallShellLogger();
}
"#
    .to_owned()
}

fn header_live_metrics_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns header clocks, live metrics lifecycle/rendering, selected-currency price behavior,
// English tooltips, DOM/event orchestration, and Tauri command usage.
// This module is deterministic browser/WASM ABI + dynamic-import interop glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  headerLiveMetricsInit as wasmInitHeaderLiveMetrics,
  headerLiveMetricsInstallModule as wasmInstallModule,
  headerLiveMetricsRefreshSelectedCurrencyPrice as wasmRefreshSelectedCurrencyPrice,
} from "../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

async function resolveTauriInvokeForRust() {
  if (window.__TAURI__?.core?.invoke) {
    return window.__TAURI__.core.invoke;
  }
  if (window.__TAURI__?.tauri?.invoke) {
    return window.__TAURI__.tauri.invoke;
  }
  try {
    const core = await import("@tauri-apps/api/core");
    if (core?.invoke) return core.invoke;
  } catch (_) {
    // Continue to the legacy Tauri API fallback.
  }
  try {
    const tauri = await import("@tauri-apps/api/tauri");
    if (tauri?.invoke) return tauri.invoke;
  } catch (_) {
    // Rust will report the missing invoke API through the existing metric error path.
  }
  throw new Error("Tauri invoke API is not available");
}

globalThis.__kgwHeaderRustResolveInvoke = resolveTauriInvokeForRust;
wasmInstallModule();
globalThis.kgwHeaderRefreshSelectedCurrencyPriceR81C = reason =>
  wasmRefreshSelectedCurrencyPrice(reason);

export function initHeaderLiveMetrics() {
  return wasmInitHeaderLiveMetrics();
}
"#
    .to_owned()
}

fn analysis_binding_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Analysis binding state, DOM/Tauri orchestration, report transformation, and event behavior.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  analysisCalendarInstall as wasmAnalysisCalendarInstall,
  analysisCalendarResetToToday as wasmAnalysisCalendarResetToToday,
  analysisClear as wasmAnalysisClear,
  analysisInstallBinding as wasmAnalysisInstallBinding,
  analysisLoadSavedAddresses as wasmAnalysisLoadSavedAddresses,
  analysisNormalizeTimeRange as wasmAnalysisNormalizeTimeRange,
  analysisRun as wasmAnalysisRun,
  analysisViewApplyFilter as wasmAnalysisViewApplyFilter,
  analysisViewFilteredRows as wasmAnalysisViewFilteredRows,
  analysisViewRenderRows as wasmAnalysisViewRenderRows,
  analysisViewResetExpansion as wasmAnalysisViewResetExpansion,
  analysisViewSetData as wasmAnalysisViewSetData,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

async function runRustAnalysis() {
  return await wasmAnalysisRun();
}

async function loadSavedAddresses() {
  return await wasmAnalysisLoadSavedAddresses();
}

function clearAnalysisView() {
  return wasmAnalysisClear();
}

export function kgwNormalizeAnalysisTimeRange(value) {
  return wasmAnalysisNormalizeTimeRange(value);
}

export function analysisViewSetData(payload) {
  return wasmAnalysisViewSetData(payload);
}

export function analysisViewApplyFilter() {
  return wasmAnalysisViewApplyFilter();
}

export function analysisViewFilteredRows() {
  return wasmAnalysisViewFilteredRows();
}

export function analysisViewRenderRows() {
  return wasmAnalysisViewRenderRows();
}

export function analysisViewResetExpansion() {
  return wasmAnalysisViewResetExpansion();
}

export function analysisCalendarInstall() {
  return wasmAnalysisCalendarInstall();
}

export function analysisCalendarResetToToday() {
  return wasmAnalysisCalendarResetToToday();
}

export function installRustAnalysisBinding() {
  window.kgwRunRustAnalysis = runRustAnalysis;
  window.kgwRefreshAnalysisAddresses = loadSavedAddresses;
  window.kgwClearRustAnalysis = clearAnalysisView;
  return wasmAnalysisInstallBinding();
}
"#
    .to_owned()
}

fn analysis_tab_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the Analysis tab filter/init/hook/calendar/export implementation.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  analysisInitTab as wasmAnalysisInitTab,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export async function initAnalysisTab() {
  return wasmAnalysisInitTab();
}
"#
    .to_owned()
}

fn top_addresses_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Top Addresses state, filtering/sorting/rendering, export, status/prompt,
// DOM/event orchestration, UI tracing, and Tauri command usage.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  topAddressesInitTab as wasmInitTopAddressesTab,
  topAddressesRefresh as wasmRefreshTopAddresses,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function initTopAddressesTab() {
  return wasmInitTopAddressesTab();
}

export function refreshTopAddresses() {
  return wasmRefreshTopAddresses();
}

window.initTopAddressesTab = initTopAddressesTab;
window.refreshTopAddresses = refreshTopAddresses;
"#
    .to_owned()
}

fn log_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Log tab state, rendering, polling, clipboard fallback, and trace behavior.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  kgwLogCopyTextToClipboard as wasmKgwCopyTextToClipboard,
  kgwLogInitTab as wasmInitLogTab,
  kgwLogParseLevel as wasmKgwParseLogLevel,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function kgwParseLogLevel(line) {
  return wasmKgwParseLogLevel(line);
}

export async function kgwCopyTextToClipboard(text, env = {}) {
  return await wasmKgwCopyTextToClipboard(text, env);
}

export function initLogTab() {
  return wasmInitLogTab();
}

window.initLogTab = initLogTab;
"#
    .to_owned()
}
fn explorer_export_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Explorer export DOM/Tauri orchestration, tracing, save/open flow, and export routing.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  explorerExportCsv as wasmExportCsv,
  explorerExportHtml as wasmExportHtml,
  explorerExportInstall as wasmInstall,
  explorerExportPdf as wasmExportPdf,
  explorerOpenBlockExplorer as wasmOpenBlockExplorer,
  explorerRawExportAddressUrlV2 as wasmRawExportAddressUrlV2,
  explorerRawExportJoinAddressesV2 as wasmRawExportJoinAddressesV2,
  explorerRawExportNormalizeRawTxV2 as wasmRawExportNormalizeRawTxV2,
  explorerRawExportNumberV2 as wasmRawExportNumberV2,
  explorerRawExportStringV2 as wasmRawExportStringV2,
  explorerRawExportTxUrlV2 as wasmRawExportTxUrlV2,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();
wasmInstall();

export function kgwExplorerExportStringV2(value) {
  return wasmRawExportStringV2(value);
}

export function kgwExplorerExportNumberV2(value, digits = 8) {
  return wasmRawExportNumberV2(value, digits);
}

export function kgwExplorerExportTxUrlV2(txid) {
  return wasmRawExportTxUrlV2(txid);
}

export function kgwExplorerExportAddressUrlV2(address) {
  return wasmRawExportAddressUrlV2(address);
}

export function kgwExplorerExportJoinAddressesV2(...values) {
  return wasmRawExportJoinAddressesV2(values);
}

export function kgwExplorerExportNormalizeRawTxV2(row) {
  return wasmRawExportNormalizeRawTxV2(row);
}

export function openBlockExplorer(section) {
  return wasmOpenBlockExplorer(section);
}

export function exportCsv(section = document) {
  return wasmExportCsv(section);
}

export function exportHtml(section = document) {
  return wasmExportHtml(section);
}

export function exportPdf(section = document) {
  return wasmExportPdf(section);
}
"#
    .to_owned()
}

fn settings_tab_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Settings UI behavior, persistence, profiles, paths, diagnostics, database, addresses, and layout.
// This module is deterministic ABI/bootstrap glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  settingsAddressesInstallAll as wasmAddressesInstallAll,
  settingsAddressesOpenExplorer as wasmAddressesOpenExplorer,
  settingsAddressesRefresh as wasmAddressesRefresh,
  settingsDatabaseInstall as wasmDatabaseInstall,
  settingsDatabaseInstallMaintenance as wasmDatabaseInstallMaintenance,
  settingsDatabaseRefresh as wasmDatabaseRefresh,
  settingsLayoutInstallGlobal as wasmLayoutInstallGlobal,
  settingsLayoutInstallManageAddressesClean as wasmLayoutInstallManageAddressesClean,
  settingsLayoutInstallSettingsI18nBindings as wasmLayoutInstallSettingsI18nBindings,
  settingsUiInitTab as wasmSettingsUiInitTab,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export async function initSettingsTab() {
  return wasmSettingsUiInitTab();
}

async function kgwRefreshSettingsDatabaseStatus() {
  return await wasmDatabaseRefresh();
}

function kgwInstallSettingsDatabaseStatus() {
  return wasmDatabaseInstall();
}

async function kgwRefreshSettingsAddresses() {
  return await wasmAddressesRefresh();
}

function kgwOpenKaspaAddressInBrowser(address) {
  return wasmAddressesOpenExplorer(address);
}

function kgwInstallSettingsManageAddressesCleanLayout() {
  return wasmLayoutInstallManageAddressesClean();
}

function kgwInstallSettingsDbMaintenanceActions() {
  return wasmDatabaseInstallMaintenance();
}

window.kgwRefreshSettingsDatabaseStatus = kgwRefreshSettingsDatabaseStatus;
window.kgwInstallSettingsDatabaseStatus = kgwInstallSettingsDatabaseStatus;
window.kgwRefreshSettingsAddresses = kgwRefreshSettingsAddresses;
window.kgwOpenKaspaAddressInBrowser = kgwOpenKaspaAddressInBrowser;
window.kgwInstallSettingsManageAddressesCleanLayout = kgwInstallSettingsManageAddressesCleanLayout;
window.kgwInstallSettingsDbMaintenanceActions = kgwInstallSettingsDbMaintenanceActions;

kgwInstallSettingsDatabaseStatus();
wasmAddressesInstallAll();
kgwInstallSettingsManageAddressesCleanLayout();
wasmLayoutInstallSettingsI18nBindings();
kgwInstallSettingsDbMaintenanceActions();

const settingsRoot = document.getElementById("settings");
if (settingsRoot) {
  wasmLayoutInstallGlobal(settingsRoot);
} else {
  document.addEventListener("DOMContentLoaded", () => {
    const root = document.getElementById("settings");
    if (root) wasmLayoutInstallGlobal(root);
  }, { once: true });
}
"#
    .to_owned()
}

fn kaspa_node_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Kaspa Node tab rendering, settings, runtime, logs, tracing, and action orchestration.
// This module is deterministic browser/WASM ABI and compatibility glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  nodeEffectiveNodeSettings,
  nodeFinalIsolatedAdapterStartV1,
  nodeFinalIsolatedAdapterStatusV1,
  nodeFinalIsolatedAdapterStopV1,
  nodeInitKaspaNodeTab,
  nodeSuperMegaIsolatedAdapterStatusPreviewV1,
  nodeV66IsolatedAdapterStartV1,
  nodeV66IsolatedAdapterStatusV1,
  nodeV66IsolatedAdapterStopV1,
  nodeV66RuntimeFeaturePolicyV1,
  nodeV67RuntimeFeaturePolicy,
  nodeV67StartRuntime,
  nodeV67StatusRuntime,
  nodeV67StopRuntime,
  nodeValidateForm,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export async function initKaspaNodeTab(root) { return nodeInitKaspaNodeTab(root); }
export { nodeEffectiveNodeSettings as kgwNodeEffectiveNodeSettings };
export { nodeValidateForm as kgwNodeValidateForm };
export default initKaspaNodeTab;

window.initKaspaNodeTab = initKaspaNodeTab;
window.kgwSuperMegaIsolatedAdapterStatusPreviewV1 = nodeSuperMegaIsolatedAdapterStatusPreviewV1;
window.kgwFinalIsolatedAdapterStartV1 = nodeFinalIsolatedAdapterStartV1;
window.kgwFinalIsolatedAdapterStatusV1 = nodeFinalIsolatedAdapterStatusV1;
window.kgwFinalIsolatedAdapterStopV1 = nodeFinalIsolatedAdapterStopV1;
window.kgwV66RuntimeFeaturePolicyV1 = nodeV66RuntimeFeaturePolicyV1;
window.kgwV66IsolatedAdapterStartV1 = nodeV66IsolatedAdapterStartV1;
window.kgwV66IsolatedAdapterStatusV1 = nodeV66IsolatedAdapterStatusV1;
window.kgwV66IsolatedAdapterStopV1 = nodeV66IsolatedAdapterStopV1;
window.kgwV67StartRuntime = nodeV67StartRuntime;
window.kgwV67StatusRuntime = nodeV67StatusRuntime;
window.kgwV67StopRuntime = nodeV67StopRuntime;
window.kgwV67RuntimeFeaturePolicy = nodeV67RuntimeFeaturePolicy;
"#
    .to_owned()
}

fn main_adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns shell/runtime/i18n implementation. This file is deterministic bootstrap glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import { KGW_TABS } from "./src/tabs/tab-registry.js";
import initShellWasm, {
  shellAuxInstall as wasmShellAuxInstall,
  shellDisplayInstall as wasmShellDisplayInstall,
  shellI18nInstall as wasmShellI18nInstall,
  shellRuntimeActivateTab as wasmShellActivateTab,
  shellRuntimeApplyTheme as wasmShellApplyTheme,
  shellRuntimeInstall as wasmShellInstall,
  shellRuntimeOpenTab as wasmShellOpenTab,
} from "./generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await initShellWasm();
wasmShellInstall(KGW_TABS);
wasmShellAuxInstall();
wasmShellDisplayInstall();
wasmShellI18nInstall();

export async function openTab(tabId, options = {}) {
  return await wasmShellOpenTab(String(tabId || ""), options || {});
}
export function activateTab(tabId) {
  return wasmShellActivateTab(String(tabId || ""));
}
export function applyTheme(theme) {
  return wasmShellApplyTheme(String(theme || ""));
}
window.kgwOpenTab = openTab;
window.kgwActivateTab = activateTab;
window.kgwApplyTheme = applyTheme;
import("./src/core/header-live-metrics.js");
"#
    .to_owned()
}

fn adapters() -> [AdapterGenerator; 17] {
    [
        (MAIN_ADAPTER_RELATIVE, main_adapter_source),
        (UTILS_ADAPTER_RELATIVE, utils_adapter_source),
        (DATE_ADAPTER_RELATIVE, date_adapter_source),
        (FORMATTING_ADAPTER_RELATIVE, formatting_adapter_source),
        (HEADER_ADAPTER_RELATIVE, header_adapter_source),
        (STATUS_ADAPTER_RELATIVE, status_adapter_source),
        (
            SETTINGS_CONTRACT_ADAPTER_RELATIVE,
            settings_contract_adapter_source,
        ),
        (
            SETTINGS_LAYOUT_ADAPTER_RELATIVE,
            settings_layout_adapter_source,
        ),
        (SETTINGS_TAB_ADAPTER_RELATIVE, settings_tab_adapter_source),
        (KASPA_NODE_ADAPTER_RELATIVE, kaspa_node_adapter_source),
        (LOG_ADAPTER_RELATIVE, log_adapter_source),
        (SHELL_LOGGER_ADAPTER_RELATIVE, shell_logger_adapter_source),
        (
            HEADER_LIVE_METRICS_ADAPTER_RELATIVE,
            header_live_metrics_adapter_source,
        ),
        (
            ANALYSIS_BINDING_ADAPTER_RELATIVE,
            analysis_binding_adapter_source,
        ),
        (ANALYSIS_TAB_ADAPTER_RELATIVE, analysis_tab_adapter_source),
        (TOP_ADDRESSES_ADAPTER_RELATIVE, top_addresses_adapter_source),
        (
            EXPLORER_EXPORT_ADAPTER_RELATIVE,
            explorer_export_adapter_source,
        ),
    ]
}

fn temp_output(root: &Path) -> PathBuf {
    root.join("target").join("kgw-frontend-wasm-codegen")
}

fn verify_wasm_pack() -> Result<(), String> {
    let output = Command::new("wasm-pack")
        .arg("--version")
        .output()
        .map_err(|error| format!("wasm-pack is required but could not start: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "wasm-pack --version failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let actual = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    if actual != WASM_PACK_VERSION {
        return Err(format!(
            "frontend WASM codegen requires {WASM_PACK_VERSION}; found {actual}"
        ));
    }
    Ok(())
}

fn build_temp(root: &Path) -> Result<PathBuf, String> {
    verify_wasm_pack()?;
    let output_dir = temp_output(root);
    if output_dir.exists() {
        fs::remove_dir_all(&output_dir)
            .map_err(|error| format!("failed to clear {}: {error}", output_dir.display()))?;
    }

    let output = Command::new("wasm-pack")
        .current_dir(root)
        .env("RUSTUP_TOOLCHAIN", "1.98.1")
        .args([
            "build",
            CRATE_RELATIVE,
            "--target",
            "web",
            "--release",
            "--out-dir",
        ])
        .arg(&output_dir)
        .args([
            "--out-name",
            "kgw_frontend_wasm",
            "--no-typescript",
            "--no-pack",
            "--no-opt",
        ])
        .output()
        .map_err(|error| format!("failed to start wasm-pack build: {error}"))?;

    if !output.status.success() {
        return Err(format!(
            "frontend WASM build failed\nstdout={}\nstderr={}",
            String::from_utf8_lossy(&output.stdout).trim(),
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }

    for name in [JS_NAME, WASM_NAME] {
        if !output_dir.join(name).is_file() {
            return Err(format!(
                "wasm-pack did not produce required artifact: {}",
                output_dir.join(name).display()
            ));
        }
    }
    Ok(output_dir)
}

fn same_bytes(left: &Path, right: &Path) -> Result<bool, String> {
    let left_bytes =
        fs::read(left).map_err(|error| format!("failed to read {}: {error}", left.display()))?;
    let right_bytes =
        fs::read(right).map_err(|error| format!("failed to read {}: {error}", right.display()))?;
    Ok(left_bytes == right_bytes)
}

fn check(root: &Path) -> Result<String, String> {
    let built = build_temp(root)?;
    let tracked = root.join(GENERATED_RELATIVE);
    let mut drift = Vec::new();
    for name in [JS_NAME, WASM_NAME] {
        let tracked_file = tracked.join(name);
        if !tracked_file.is_file() || !same_bytes(&built.join(name), &tracked_file)? {
            drift.push(tracked_file.to_string_lossy().into_owned());
        }
    }

    let mut tracked_names = if tracked.is_dir() {
        fs::read_dir(&tracked)
            .map_err(|error| format!("failed to list {}: {error}", tracked.display()))?
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };
    tracked_names.sort();
    let expected_names = vec![JS_NAME.to_owned(), WASM_NAME.to_owned()];
    if tracked_names != expected_names {
        drift.push(format!(
            "{}:unexpected-generated-file-set={}",
            tracked.display(),
            tracked_names.join(",")
        ));
    }

    for (relative, source) in adapters() {
        let adapter = root.join(relative);
        let expected = source();
        let actual = fs::read_to_string(&adapter).unwrap_or_default();
        if actual != expected {
            drift.push(adapter.to_string_lossy().into_owned());
        }
    }

    if drift.is_empty() {
        Ok(format!(
            "FRONTEND_WASM_CODEGEN=PASS\nWASM_PACK_VERSION={}\nARTIFACT_COUNT=18",
            WASM_PACK_VERSION.trim_start_matches("wasm-pack ")
        ))
    } else {
        Err(format!(
            "FRONTEND_WASM_CODEGEN=FAIL\nDRIFT={}",
            drift.join(",")
        ))
    }
}

fn write(root: &Path) -> Result<String, String> {
    let built = build_temp(root)?;
    let tracked = root.join(GENERATED_RELATIVE);
    fs::create_dir_all(&tracked)
        .map_err(|error| format!("failed to create {}: {error}", tracked.display()))?;

    let mut changed = 0_usize;
    for name in [JS_NAME, WASM_NAME] {
        let source = built.join(name);
        let destination = tracked.join(name);
        let differs = !destination.is_file() || !same_bytes(&source, &destination)?;
        if differs {
            fs::copy(&source, &destination).map_err(|error| {
                format!(
                    "failed to copy {} to {}: {error}",
                    source.display(),
                    destination.display()
                )
            })?;
            changed += 1;
        }
    }

    for (relative, source) in adapters() {
        let adapter = root.join(relative);
        let expected = source();
        let actual = fs::read_to_string(&adapter).unwrap_or_default();
        if actual != expected {
            fs::write(&adapter, expected.as_bytes())
                .map_err(|error| format!("failed to write {}: {error}", adapter.display()))?;
            changed += 1;
        }
    }

    Ok(format!(
        "FRONTEND_WASM_CODEGEN=WRITE_PASS\nWASM_PACK_VERSION={}\nARTIFACT_COUNT=18\nCHANGED={changed}",
        WASM_PACK_VERSION.trim_start_matches("wasm-pack ")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adapter_is_generated_and_uses_rust_exports_only() {
        let adapter = utils_adapter_source();
        assert!(adapter.contains("@generated"));
        assert!(adapter.contains("await init();"));
        assert!(adapter.contains("wasmToEnglishDigits(value)"));
        assert!(adapter.contains("wasmPick(values)"));
        assert!(adapter.contains("wasmToNumber(value, fallback)"));
        assert!(adapter.contains("wasmKgwClean2SafeText(value)"));
        assert!(adapter.contains("wasmExplorerSummaryCurrentUsdPrice()"));
        assert!(adapter.contains("wasmExplorerSummaryUsdForKas(valueKas)"));
        assert!(adapter.contains("wasmExplorerNormalizeDaySummaries(result)"));
        assert!(adapter.contains("wasmExplorerSummaryUsdForSummary(summary)"));
        assert!(adapter.contains("wasmExplorerLiveCoreAddress()"));
        assert!(adapter.contains("wasmExplorerLiveCoreReset(address)"));
        assert!(adapter.contains("wasmExplorerLiveCoreSeedRows(address, rows)"));
        assert!(adapter.contains("wasmExplorerLiveCoreMergeRecords(records)"));
        assert!(adapter.contains("wasmExplorerLiveCoreMergeDays(days)"));
        assert!(adapter.contains("wasmExplorerLiveCoreRows()"));
        assert!(adapter.contains("wasmExplorerLiveCoreShouldRender(payload)"));
        assert!(adapter.contains("wasmExplorerNormalizeUnifiedResult(result)"));
        assert!(adapter.contains("wasmExplorerDaySummaryRowsFromResult(result)"));
        assert!(
            adapter.contains("wasmExplorerMicroscopeLog(String(stage ?? \"\"), details ?? {})")
        );
        assert!(
            adapter.contains("wasmExplorerMicroscopeWarn(String(stage ?? \"\"), details ?? {})")
        );
        assert!(
            adapter.contains(
                "wasmExplorerMicroscopeError(String(stage ?? \"\"), error, details ?? {})"
            )
        );
        assert!(adapter.contains("return wasmExplorerMicroscopeElementReport(section)"));
        assert!(adapter.contains("wasmExplorerMicroscopeLayoutReport(section)"));
        assert!(adapter.contains(
            "wasmExplorerMicroscopeStateReport(String(label ?? \"STATE REPORT\"), snapshot ?? {})"
        ));
        assert!(adapter.contains("wasmExplorerMicroscopeApiShape(String(label ?? \"\"), value)"));
        assert!(adapter.contains("await wasmExplorerInvokeUnifiedFetch(request)"));
        assert!(adapter.contains("await wasmExplorerInvokeCancelTransactions(requestId)"));
        assert!(adapter.contains("await wasmExplorerInvokeGroupedTransactions(request)"));
        assert!(adapter.contains("await wasmExplorerInvokeDaySummaries(request)"));
        assert!(adapter.contains("wasmExplorerSetStatus(section, message, state)"));
        assert!(adapter.contains("wasmExplorerEnsureState()"));
        assert!(adapter.contains(
            "wasmExplorerSyncActionState(section, Boolean(busy), rowsCount, filteredRowsCount)"
        ));
        assert!(adapter.contains("wasmExplorerSyncCurrentActionState(section)"));
        assert!(adapter.contains("wasmExplorerInstallPriceRerender()"));
        assert!(adapter.contains("wasmExplorerExtractRowsFromUnifiedResult(result)"));
        assert!(adapter.contains("wasmExplorerUiTrace(action, phase, details)"));
        assert!(adapter.contains("wasmExplorerFilterTrace(label, payload)"));
        assert!(
            adapter.contains("wasmExplorerLegacyListRequest(section, address, startTs, endTs)")
        );
        assert!(adapter.contains(
            "await wasmExplorerLoadTransactionDaySummariesFromDb(section, address, startTs, endTs)"
        ));
        assert!(adapter.contains(
            "await wasmExplorerLoadTransactionsForSingleDayFromDb(section, address, day)"
        ));
        assert!(
            adapter.contains("await wasmExplorerLoadTransactionsForDay(section, address, day)")
        );
        assert!(adapter.contains("wasmExplorerClean2Log(String(label ?? \"\"), payload ?? {})"));
        assert!(adapter.contains("wasmExplorerClean2Section(section)"));
        assert!(adapter.contains("wasmExplorerClean2Body(section)"));
        assert!(
            adapter.contains(
                "await wasmExplorerClean2LoadSummaries(section, address, startTs, endTs)"
            )
        );
        assert!(
            adapter.contains("await wasmExplorerClean2LoadDayTransactions(section, address, day)")
        );
        assert!(!adapter.contains("Number.isFinite"));
        assert!(!adapter.contains("Math.abs"));
        assert!(!adapter.contains("new Map"));
        assert!(adapter.contains("wasmExplorerSetTableFontSize(section)"));
        assert!(adapter.contains("wasmExplorerApplyFontSize(section, rawValue)"));
        assert!(adapter.contains("wasmExplorerBindFontSpinbox(section)"));
        assert!(adapter.contains("wasmExplorerDefaultDates(section)"));
        assert!(adapter.contains("wasmExplorerApplyLocalBusyControls(section, busy)"));
        assert!(
            adapter.contains("wasmExplorerForceSetTableMessage(section, String(message ?? \"\"))")
        );
        assert!(adapter.contains("wasmExplorerForceResetDisplayFiltersToAll(section)"));
        assert!(adapter.contains(
            "wasmExplorerForceSetControlsBusy(section, Boolean(busy), String(mode ?? \"normal\"))"
        ));
        assert!(adapter.contains("wasmExplorerInstallForceBusyBlocker()"));
        assert!(adapter.contains("wasmExplorerEnsureFilterOptions(section)"));
        assert!(adapter.contains("wasmExplorerReadFilterState(section)"));
        assert!(
            adapter
                .contains("wasmExplorerBuildListRequest(section, address, startTs, endTs, limit)")
        );
        assert!(adapter.contains("wasmExplorerFilterValue(selector, section, fallback)"));
        assert!(
            adapter.contains(
                "wasmExplorerFilterBuildRequest(section, address, startTs, endTs, limit)"
            )
        );
        assert!(adapter.contains("wasmExplorerInstallFilterSelectRepair();"));
        assert!(adapter.contains("wasmExplorerNormalizeTxTypeFilterValue(value)"));
        assert!(adapter.contains("wasmExplorerNormalizeDirectionFilterValue(value)"));
        assert!(adapter.contains("wasmExplorerRepairFilterSelects(section)"));
        assert!(
            adapter.contains("wasmExplorerClean2Request(section, address, startTs, endTs, limit)")
        );
        assert!(adapter.contains("wasmExplorerNormalizeAddress(value)"));
        assert!(adapter.contains("wasmExplorerIsKaspaAddress(value)"));
        assert!(adapter.contains("wasmExplorerAddressLookupKeys(value)"));
        assert!(adapter.contains("await wasmExplorerCanonicalKaspaAddress(value)"));
        assert!(adapter.contains("await wasmExplorerLoadKnownAddressNames()"));
        assert!(adapter.contains("await wasmExplorerSaveAddressToDatabase(address, name)"));
        assert!(adapter.contains("await wasmExplorerRefreshAddressName(section, address)"));
        assert!(adapter.contains("await wasmExplorerLoadSavedAddresses(section)"));
        assert!(adapter.contains("await wasmExplorerFetchBalance(section, address)"));
        assert!(adapter.contains("wasmExplorerAddressDiagnosticsSnapshot(address)"));
        assert!(!adapter.contains("replaceAll("));
        assert!(!adapter.contains("Number.isFinite"));
        let date = date_adapter_source();
        assert!(date.contains("wasmNormalizeDateInputValue(value)"));
        assert!(date.contains("wasmKgwTransactionDateKey(row)"));
        let formatting = formatting_adapter_source();
        assert!(formatting.contains("wasmFormatKas(value)"));
        assert!(formatting.contains("wasmKgwClean2Usd(value)"));
        let header = header_adapter_source();
        assert!(header.contains("@generated"));
        assert!(header.contains("wasmParseHeaderUsdPrice()"));
        assert!(!header.contains("__kgwKaspaUsdPrice"));
        assert!(!header.contains("getElementById"));
        let status = status_adapter_source();
        assert!(status.contains("@generated"));
        assert!(status.contains("wasmStatusTone(state)"));
        assert!(status.contains("wasmApplyStatusTone(element, state)"));
        assert!(status.contains("wasmRenderStatusSummary(element, text)"));
        assert!(status.contains("wasmRuntimePresentation(state)"));
        assert!(status.contains("wasmRuntimeObservationSummary(fields, running, cpuOnly)"));
        assert!(!status.contains("observation_state"));
        assert!(!status.contains("cpu_hashrate_hs"));
        assert!(!status.contains("const GROUPS"));
        assert!(!status.contains("document.createElement"));
        let settings = settings_contract_adapter_source();
        assert!(settings.contains("@generated"));
        assert!(settings.contains("wasmValidateNodeForm(values, options, network)"));
        assert!(settings.contains("wasmValidateBridgeForm(values, options, network)"));
        assert!(settings.contains("wasmRenderFieldErrors(root, prefix, errors)"));
        assert!(settings.contains("await wasmConfirmUserAction(message)"));
        assert!(settings.contains("wasmToWesternDigits(value)"));
        assert!(settings.contains("wasmDisplayChecksWithDefaults(checks, knownEntries)"));
        assert!(settings.contains("wasmDisplayStateMissingContract(checks)"));
        assert!(settings.contains("wasmDisplayPreferences(checks)"));
        assert!(settings.contains("wasmAddressShort(value)"));
        assert!(settings.contains("wasmIsKaspaAddress(value)"));
        assert!(settings.contains("wasmAddressNormalize(record)"));
        assert!(settings.contains("wasmAddressesInstallIo()"));
        assert!(settings.contains("wasmDbKindFromFileName(value)"));
        assert!(settings.contains("wasmDatabaseRenderRows(rows)"));
        assert!(settings.contains("await wasmDatabaseRefresh()"));
        assert!(settings.contains("wasmDatabaseInstall()"));
        assert!(settings.contains("wasmDatabaseInstallMaintenance()"));
        assert!(settings.contains("wasmDiagnosticsInstall()"));
        assert!(settings.contains("wasmStateCollect()"));
        assert!(settings.contains("wasmStateApply(state)"));
        assert!(settings.contains("wasmDisplayEnsureDefaults(reason)"));
        assert!(settings.contains("wasmDisplayValidateForSave()"));
        assert!(settings.contains("wasmDisplayBindMinimumGuards()"));
        assert!(settings.contains("wasmDisplayBuildCanonicalDefaultState(reason, persist)"));
        assert!(settings.contains("wasmDisplayReapplyState(state, reason)"));
        assert!(settings.contains("wasmDisplayApplyShellFromState(state, reason)"));
        assert!(settings.contains("wasmPathsApply(paths, force)"));
        assert!(settings.contains("await wasmPathsBrowse(targetId)"));
        assert!(settings.contains("await wasmPathsLoadDefaults(reason)"));
        assert!(settings.contains("await wasmPathsRepairBeforeSave()"));
        assert!(settings.contains("await wasmPersistenceSave()"));
        assert!(settings.contains("await wasmPersistenceResetDefaults(options)"));
        assert!(settings.contains("wasmPersistenceLoadSaved()"));
        assert!(settings.contains("wasmProfilesInstall()"));
        assert!(settings.contains("await wasmProfilesRefresh()"));
        assert!(settings.contains("wasmProfilesSelectEndpoint(row)"));
        assert!(settings.contains("wasmExplorerAddress(value)"));
        assert!(settings.contains("wasmExplorerUrl(value)"));
        assert!(settings.contains("new Set(wasmNodeOptional())"));
        assert!(settings.contains("new Set(wasmBridgeRequired())"));
        for forbidden in [
            "Number.MAX_SAFE_INTEGER",
            "Enter a valid IP address",
            "querySelectorAll(",
            "plugin:dialog|message",
            "internalCpuMinerThreads: [",
        ] {
            assert!(
                !settings.contains(forbidden),
                "settings implementation must remain in Rust: {forbidden}"
            );
        }
        let layout = settings_layout_adapter_source();
        assert!(layout.contains("@generated"));
        assert!(layout.contains("wasmHelpKeys()"));
        assert!(layout.contains("wasmGlobalHelpIds()"));
        assert!(layout.contains("wasmFieldKind(field)"));
        assert!(layout.contains("wasmRenderTabs(scope, net, groups)"));
        assert!(layout.contains("wasmDecorateFields(root)"));
        assert!(layout.contains("wasmSetFieldState(field, String(message || \"\"))"));
        assert!(layout.contains("wasmRevealField(field)"));
        assert!(layout.contains("wasmInstall(root)"));
        assert!(layout.contains("wasmDecorateGlobal(root)"));
        assert!(layout.contains("wasmInstallGlobal(root)"));
        assert!(layout.contains("wasmInstallManageAddressesClean()"));
        assert!(layout.contains("wasmInstallSettingsI18nBindings()"));
        for forbidden in [
            "querySelector(",
            "addEventListener(",
            "createElement(",
            "HELP_FALLBACKS",
            "recommendedSpan",
            "genericHelp(",
        ] {
            assert!(
                !layout.contains(forbidden),
                "Settings layout implementation must remain in Rust: {forbidden}"
            );
        }
        let log = log_adapter_source();
        assert!(log.contains("@generated"));
        assert!(log.contains("wasmKgwParseLogLevel(line)"));
        assert!(log.contains("await wasmKgwCopyTextToClipboard(text, env)"));
        assert!(log.contains("wasmInitLogTab()"));
        assert!(log.contains("window.initLogTab = initLogTab"));
        for forbidden in [
            "document.",
            "localStorage",
            "setInterval",
            "clipboard.writeText",
            "kgw_log_read",
        ] {
            assert!(
                !log.contains(forbidden),
                "Log implementation must remain in Rust: {forbidden}"
            );
        }
        let shell = shell_logger_adapter_source();
        assert!(shell.contains("@generated"));
        assert!(shell.contains("wasmKgwLog(level, message, details, source)"));
        assert!(shell.contains("wasmKgwFatal(error, source)"));
        assert!(shell.contains("wasmInstallShellLogger()"));
        for forbidden in [
            "localStorage",
            "document.createElement",
            "kgw_log_append",
            "MAX_BUFFER",
        ] {
            assert!(
                !shell.contains(forbidden),
                "Shell logger implementation must remain in Rust: {forbidden}"
            );
        }
        let header_live = header_live_metrics_adapter_source();
        assert!(header_live.contains("@generated"));
        assert!(header_live.contains("wasmInstallModule();"));
        assert!(header_live.contains("wasmInitHeaderLiveMetrics()"));
        assert!(header_live.contains("__kgwHeaderRustResolveInvoke"));
        assert!(header_live.contains("wasmRefreshSelectedCurrencyPrice(reason)"));
        assert!(header_live.contains("import(\"@tauri-apps/api/core\")"));
        for forbidden in [
            "setInterval(",
            "querySelector(",
            "Intl.NumberFormat",
            "kgw_live_metrics_snapshot",
            "kgw_get_kaspa_prices",
        ] {
            assert!(
                !header_live.contains(forbidden),
                "Header live metrics implementation must remain in Rust: {forbidden}"
            );
        }
        let analysis = analysis_binding_adapter_source();
        assert!(analysis.contains("@generated"));
        assert!(analysis.contains("wasmAnalysisRun()"));
        assert!(analysis.contains("wasmAnalysisLoadSavedAddresses()"));
        assert!(analysis.contains("wasmAnalysisClear()"));
        assert!(analysis.contains("wasmAnalysisNormalizeTimeRange(value)"));
        assert!(analysis.contains("wasmAnalysisInstallBinding()"));
        for forbidden in [
            "analysis_report",
            "get_all_addresses",
            "document.",
            "addEventListener",
            "counterparties.map",
            "raw_sompi",
        ] {
            assert!(
                !analysis.contains(forbidden),
                "Analysis implementation must remain in Rust: {forbidden}"
            );
        }

        let top = top_addresses_adapter_source();
        assert!(top.contains("@generated"));
        assert!(top.contains("wasmInitTopAddressesTab()"));
        assert!(top.contains("wasmRefreshTopAddresses()"));
        assert!(top.contains("window.initTopAddressesTab = initTopAddressesTab"));
        assert!(top.contains("window.refreshTopAddresses = refreshTopAddresses"));
        for forbidden in [
            "fetch_top_addresses_rust",
            "export_report",
            "export_default_path",
            "kgw_open_exported_file_v1",
            "kgw_frontend_button_trace_v1",
            "querySelector(",
            "addEventListener(",
            "LOADING â€”",
            "SUCCESS â€”",
        ] {
            assert!(
                !top.contains(forbidden),
                "Top Addresses implementation must remain in Rust: {forbidden}"
            );
        }

        let explorer_export = explorer_export_adapter_source();
        assert!(explorer_export.contains("@generated"));
        assert!(explorer_export.contains("wasmInstall();"));
        assert!(explorer_export.contains("wasmOpenBlockExplorer(section)"));
        assert!(explorer_export.contains("wasmExportCsv(section)"));
        assert!(explorer_export.contains("wasmExportHtml(section)"));
        assert!(explorer_export.contains("wasmExportPdf(section)"));
        assert!(explorer_export.contains("wasmRawExportStringV2(value)"));
        assert!(explorer_export.contains("wasmRawExportNumberV2(value, digits)"));
        assert!(explorer_export.contains("wasmRawExportTxUrlV2(txid)"));
        assert!(explorer_export.contains("wasmRawExportAddressUrlV2(address)"));
        assert!(explorer_export.contains("wasmRawExportJoinAddressesV2(values)"));
        assert!(explorer_export.contains("wasmRawExportNormalizeRawTxV2(row)"));
        for forbidden in [
            "export_default_path",
            "export_report",
            "kgw_open_exported_file_v1",
            "kgw_frontend_button_trace_v1",
            "navigator.clipboard",
            "querySelector(",
            "addEventListener(",
            "createElement(",
        ] {
            assert!(
                !explorer_export.contains(forbidden),
                "Explorer export implementation must remain in Rust: {forbidden}"
            );
        }
    }

    #[test]
    fn settings_tab_adapter_is_generated_bootstrap_only() {
        let settings = settings_tab_adapter_source();
        assert!(settings.contains("@generated"));
        assert!(settings.contains("wasmSettingsUiInitTab()"));
        assert!(settings.contains("wasmDatabaseInstall()"));
        assert!(settings.contains("wasmAddressesInstallAll()"));
        assert!(settings.contains("wasmLayoutInstallGlobal(settingsRoot)"));
        for forbidden in [
            "settings_validate_custom_path",
            "settings_profile_add",
            "localStorage",
            "[data-settings-tab]",
            "settingsSaveSettings",
            "kgw-settings-python-exact-state",
        ] {
            assert!(
                !settings.contains(forbidden),
                "Settings implementation must remain in Rust: {forbidden}"
            );
        }
    }

    #[test]
    fn kaspa_node_adapter_is_generated_bootstrap_only() {
        let node = kaspa_node_adapter_source();
        assert!(node.contains("@generated"));
        assert!(node.contains("nodeInitKaspaNodeTab"));
        assert!(node.contains("nodeEffectiveNodeSettings as kgwNodeEffectiveNodeSettings"));
        assert!(node.contains("nodeValidateForm as kgwNodeValidateForm"));
        assert!(node.contains("window.initKaspaNodeTab = initKaspaNodeTab"));
        assert!(
            node.contains("window.kgwFinalIsolatedAdapterStopV1 = nodeFinalIsolatedAdapterStopV1")
        );
        assert!(!node.contains("noeFinalIsolatedAdapterStopV1"));
        for forbidden in [
            "querySelector(",
            "addEventListener(",
            "localStorage",
            "kgw_runtime_owner_status_v1",
            "kgw_kgw_runtime_logs_v1",
            "kgw_copy_text_to_clipboard_v1",
            "function renderNetworkPanel",
        ] {
            assert!(
                !node.contains(forbidden),
                "Kaspa Node implementation must remain in Rust: {forbidden}"
            );
        }
    }

    #[test]
    fn generated_paths_are_inside_frontend_or_target() {
        assert!(GENERATED_RELATIVE.starts_with("apps/kaspa-gateway-desktop/frontend/"));
        assert!(MAIN_ADAPTER_RELATIVE.ends_with("frontend/main.js"));
        assert!(UTILS_ADAPTER_RELATIVE.ends_with("explorer.utils.js"));
        assert!(DATE_ADAPTER_RELATIVE.ends_with("explorer.date.js"));
        assert!(FORMATTING_ADAPTER_RELATIVE.ends_with("explorer.formatting.js"));
        assert!(HEADER_ADAPTER_RELATIVE.ends_with("explorer.header.js"));
        assert!(STATUS_ADAPTER_RELATIVE.ends_with("src/status.js"));
        assert!(SETTINGS_CONTRACT_ADAPTER_RELATIVE.ends_with("src/settings-contract.js"));
        assert!(SETTINGS_LAYOUT_ADAPTER_RELATIVE.ends_with("src/settings-layout.js"));
        assert!(LOG_ADAPTER_RELATIVE.ends_with("src/tabs/log/log.js"));
        assert!(SHELL_LOGGER_ADAPTER_RELATIVE.ends_with("src/core/shell-logger.js"));
        assert!(HEADER_LIVE_METRICS_ADAPTER_RELATIVE.ends_with("src/core/header-live-metrics.js"));
        assert!(
            ANALYSIS_BINDING_ADAPTER_RELATIVE
                .ends_with("src/tabs/analysis/analysis-rust-binding.js")
        );
        assert!(
            TOP_ADDRESSES_ADAPTER_RELATIVE.ends_with("src/tabs/top-addresses/top-addresses.js")
        );
        assert!(EXPLORER_EXPORT_ADAPTER_RELATIVE.ends_with("src/tabs/explorer/explorer.export.js"));
        assert!(SETTINGS_TAB_ADAPTER_RELATIVE.ends_with("src/tabs/settings/settings.js"));
        assert!(KASPA_NODE_ADAPTER_RELATIVE.ends_with("src/tabs/kaspa-node/kaspa-node.js"));
        let root = Path::new("repo");
        assert!(temp_output(root).starts_with(root.join("target")));
    }
}
