use std::fs;
use std::path::Path;

const REGISTRY_JSON_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/tab-registry.json";
const REGISTRY_JS_RELATIVE: &str = "apps/kaspa-gateway-desktop/frontend/src/tabs/tab-registry.js";

const TEMPLATES: [(&str, &str); 7] = [
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/analysis/analysis.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/analysis/analysis.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-bridge/kaspa-bridge.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-bridge/kaspa-bridge.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-node/kaspa-node.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/kaspa-node/kaspa-node.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/log/log.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/log/log.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/settings/settings.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/settings/settings.template.js",
    ),
    (
        "apps/kaspa-gateway-desktop/frontend/src/tabs/top-addresses/top-addresses.template.html",
        "apps/kaspa-gateway-desktop/frontend/src/tabs/top-addresses/top-addresses.template.js",
    ),
];

pub fn run_cli(args: &mut impl Iterator<Item = String>, root: &Path) -> Result<String, String> {
    let action = args.next().unwrap_or_else(|| "check".to_owned());
    if args.next().is_some() {
        return Err(
            "frontend-template-codegen accepts exactly one action: check or write".to_owned(),
        );
    }
    match action.as_str() {
        "check" => check(root),
        "write" => write(root),
        _ => Err(format!(
            "unknown frontend-template-codegen action: {action}; expected check or write"
        )),
    }
}

fn render_module(source_relative: &str, html: &str) -> Result<String, String> {
    let encoded = serde_json::to_string(html)
        .map_err(|error| format!("template JSON encoding failed for {source_relative}: {error}"))?;
    Ok(format!(
        "// @generated by cargo run --locked -p xtask -- frontend-template-codegen write\n\
// Source: {source_relative}\n\
// DO NOT EDIT THIS FILE DIRECTLY. Edit the declarative HTML source instead.\n\
const html = {encoded};\n\nexport default html;\n"
    ))
}

fn expected(root: &Path, html_relative: &str) -> Result<String, String> {
    let html_path = root.join(html_relative);
    let html = fs::read_to_string(&html_path)
        .map_err(|error| format!("failed to read {}: {error}", html_path.display()))?;
    render_module(html_relative, &html)
}

fn registry_field<'a>(
    tab: &'a serde_json::Value,
    key: &str,
    index: usize,
) -> Result<&'a str, String> {
    tab.get(key)
        .and_then(serde_json::Value::as_str)
        .filter(|value| !value.is_empty())
        .ok_or_else(|| format!("tab-registry entry {index} missing/invalid {key}"))
}

fn expected_registry(root: &Path) -> Result<String, String> {
    let source = root.join(REGISTRY_JSON_RELATIVE);
    let bytes = fs::read(&source)
        .map_err(|error| format!("failed to read {}: {error}", source.display()))?;
    let value: serde_json::Value = serde_json::from_slice(&bytes)
        .map_err(|error| format!("invalid registry JSON {}: {error}", source.display()))?;
    let tabs = value
        .get("tabs")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| "tab-registry.json must contain tabs array".to_owned())?;
    if tabs.len() != 7 {
        return Err(format!(
            "tab-registry.json must contain exactly 7 tabs; found {}",
            tabs.len()
        ));
    }

    let mut ids = std::collections::BTreeSet::new();
    let mut bindings = std::collections::BTreeSet::new();
    let mut rendered = String::new();
    let mut parsed = Vec::new();

    for (index, tab) in tabs.iter().enumerate() {
        let id = registry_field(tab, "id", index)?;
        let binding = registry_field(tab, "templateBinding", index)?;
        let template = registry_field(tab, "template", index)?;
        let css = registry_field(tab, "css", index)?;
        let module = registry_field(tab, "module", index)?;
        let init = registry_field(tab, "init", index)?;

        if !ids.insert(id.to_owned()) {
            return Err(format!("duplicate tab id in tab-registry.json: {id}"));
        }
        if !bindings.insert(binding.to_owned()) {
            return Err(format!(
                "duplicate template binding in tab-registry.json: {binding}"
            ));
        }
        if !template.starts_with("./") || !module.starts_with("./") || !css.starts_with("./src/") {
            return Err(format!(
                "tab-registry entry {index} has non-relative template/module/css path"
            ));
        }

        rendered.push_str(&format!("import {binding} from \"{template}\";\n"));
        parsed.push((id, binding, css, module, init));
    }

    rendered.push('\n');
    rendered.push_str("export const KGW_TABS = [\n");
    for (index, (id, binding, css, module, init)) in parsed.iter().enumerate() {
        rendered.push_str("  {\n");
        rendered.push_str(&format!("    id: \"{id}\",\n"));
        rendered.push_str(&format!("    css: \"{css}\",\n"));
        rendered.push_str(&format!("    html: {binding},\n"));
        rendered.push_str(&format!("    module: () => import(\"{module}\"),\n"));
        rendered.push_str(&format!("    init: \"{init}\"\n"));
        if index + 1 == parsed.len() {
            rendered.push_str("  }\n");
        } else {
            rendered.push_str("  },\n");
        }
    }
    rendered.push_str("];\n");
    Ok(rendered)
}

fn check(root: &Path) -> Result<String, String> {
    let mut drift = Vec::new();
    for (html_relative, js_relative) in TEMPLATES {
        let expected = expected(root, html_relative)?;
        let js_path = root.join(js_relative);
        let actual = fs::read_to_string(&js_path).map_err(|error| {
            format!(
                "failed to read generated wrapper {}: {error}",
                js_path.display()
            )
        })?;
        if actual != expected {
            drift.push(js_relative);
        }
    }

    let expected_registry = expected_registry(root)?;
    let registry_path = root.join(REGISTRY_JS_RELATIVE);
    let actual_registry = fs::read_to_string(&registry_path).map_err(|error| {
        format!(
            "failed to read generated registry {}: {error}",
            registry_path.display()
        )
    })?;
    if actual_registry.replace("\r\n", "\n") != expected_registry {
        drift.push(REGISTRY_JS_RELATIVE);
    }

    if drift.is_empty() {
        Ok(format!(
            "FRONTEND_TEMPLATE_CODEGEN=PASS\nTEMPLATE_COUNT={}",
            TEMPLATES.len()
        ))
    } else {
        Err(format!(
            "FRONTEND_TEMPLATE_CODEGEN=FAIL\nDRIFT={}",
            drift.join(",")
        ))
    }
}

fn write(root: &Path) -> Result<String, String> {
    let mut changed = Vec::new();
    for (html_relative, js_relative) in TEMPLATES {
        let expected = expected(root, html_relative)?;
        let js_path = root.join(js_relative);
        let current = fs::read_to_string(&js_path).unwrap_or_default();
        if current != expected {
            fs::write(&js_path, expected.as_bytes())
                .map_err(|error| format!("failed to write {}: {error}", js_path.display()))?;
            changed.push(js_relative);
        }
    }

    let expected_registry = expected_registry(root)?;
    let registry_path = root.join(REGISTRY_JS_RELATIVE);
    let current_registry = fs::read_to_string(&registry_path).unwrap_or_default();
    if current_registry.replace("\r\n", "\n") != expected_registry {
        fs::write(&registry_path, expected_registry.as_bytes())
            .map_err(|error| format!("failed to write {}: {error}", registry_path.display()))?;
        changed.push(REGISTRY_JS_RELATIVE);
    }

    Ok(format!(
        "FRONTEND_TEMPLATE_CODEGEN=WRITE_PASS\nTEMPLATE_COUNT={}\nCHANGED={}",
        TEMPLATES.len(),
        changed.len()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renderer_escapes_html_for_es_module_safely() {
        let html = "<div data-value=\"x\">line 1\nline \\ 2 \\u{2028}</div>";
        let rendered = render_module("fixture.template.html", html).unwrap();
        assert!(rendered.contains("@generated"));
        assert!(rendered.contains("const html = "));
        assert!(rendered.contains("\\n"));
        assert!(rendered.contains("\\\\"));
        assert!(rendered.ends_with("\nexport default html;\n"));
    }

    #[test]
    fn template_mapping_is_unique_and_html_backed() {
        let mut html = std::collections::BTreeSet::new();
        let mut js = std::collections::BTreeSet::new();
        for (html_path, js_path) in TEMPLATES {
            assert!(html.insert(html_path));
            assert!(js.insert(js_path));
            assert!(html_path.ends_with(".template.html"));
            assert!(js_path.ends_with(".template.js"));
        }
        assert_eq!(html.len(), 7);
        assert_eq!(js.len(), 7);
    }

    #[test]
    fn registry_json_renders_existing_normalized_source() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let expected = expected_registry(root).unwrap();
        let actual = fs::read_to_string(root.join(REGISTRY_JS_RELATIVE))
            .unwrap()
            .replace("\r\n", "\n");
        assert_eq!(expected, actual);
    }

    #[test]
    fn registry_paths_are_declarative_and_stable() {
        assert!(REGISTRY_JSON_RELATIVE.ends_with("tab-registry.json"));
        assert!(REGISTRY_JS_RELATIVE.ends_with("tab-registry.js"));
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
        let rendered = expected_registry(root).unwrap();
        assert_eq!(rendered.matches("    id: ").count(), 7);
        assert_eq!(rendered.matches("    module: () => import(").count(), 7);
    }
}
