use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const WASM_PACK_VERSION: &str = "wasm-pack 0.15.0";
const CRATE_RELATIVE: &str = "crates/kaspa-gateway-frontend-wasm";
const GENERATED_RELATIVE: &str = "apps/kaspa-gateway-desktop/frontend/generated/kgw_frontend_wasm";
const ADAPTER_RELATIVE: &str =
    "apps/kaspa-gateway-desktop/frontend/src/tabs/explorer/explorer.utils.js";
const JS_NAME: &str = "kgw_frontend_wasm.js";
const WASM_NAME: &str = "kgw_frontend_wasm_bg.wasm";

pub fn run_cli(args: &mut impl Iterator<Item = String>, root: &Path) -> Result<String, String> {
    let action = args.next().unwrap_or_else(|| "check".to_owned());
    if args.next().is_some() {
        return Err("frontend-wasm-codegen accepts exactly one action: check or write".to_owned());
    }
    match action.as_str() {
        "check" => check(root),
        "write" => write(root),
        _ => Err(format!(
            "unknown frontend-wasm-codegen action: {action}; expected check or write"
        )),
    }
}

fn adapter_source() -> String {
    r#"// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns the implementation. This module is deterministic ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  kgwClean2SafeText as wasmKgwClean2SafeText,
  pick as wasmPick,
  toEnglishDigits as wasmToEnglishDigits,
  toNumber as wasmToNumber,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function toEnglishDigits(value) {
  return wasmToEnglishDigits(value);
}

export function pick(...values) {
  return wasmPick(values);
}

export function toNumber(value, fallback = 0) {
  return wasmToNumber(value, fallback);
}

export function kgwClean2SafeText(value) {
  return wasmKgwClean2SafeText(value);
}
"#
    .to_owned()
}

fn temp_output(root: &Path) -> PathBuf {
    root.join("target").join("kgw-frontend-wasm-codegen")
}

fn verify_wasm_pack() -> Result<(), String> {
    let output = Command::new("wasm-pack")
        .arg("--version")
        .output()
        .map_err(|error| format!("wasm-pack is required but could not start: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "wasm-pack --version failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let actual = String::from_utf8_lossy(&output.stdout).trim().to_owned();
    if actual != WASM_PACK_VERSION {
        return Err(format!(
            "frontend WASM codegen requires {WASM_PACK_VERSION}; found {actual}"
        ));
    }
    Ok(())
}

fn build_temp(root: &Path) -> Result<PathBuf, String> {
    verify_wasm_pack()?;
    let output_dir = temp_output(root);
    if output_dir.exists() {
        fs::remove_dir_all(&output_dir)
            .map_err(|error| format!("failed to clear {}: {error}", output_dir.display()))?;
    }

    let output = Command::new("wasm-pack")
        .current_dir(root)
        .env("RUSTUP_TOOLCHAIN", "1.98.1")
        .args([
            "build",
            CRATE_RELATIVE,
            "--target",
            "web",
            "--release",
            "--out-dir",
        ])
        .arg(&output_dir)
        .args([
            "--out-name",
            "kgw_frontend_wasm",
            "--no-typescript",
            "--no-pack",
            "--no-opt",
        ])
        .output()
        .map_err(|error| format!("failed to start wasm-pack build: {error}"))?;

    if !output.status.success() {
        return Err(format!(
            "frontend WASM build failed\nstdout={}\nstderr={}",
            String::from_utf8_lossy(&output.stdout).trim(),
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }

    for name in [JS_NAME, WASM_NAME] {
        if !output_dir.join(name).is_file() {
            return Err(format!(
                "wasm-pack did not produce required artifact: {}",
                output_dir.join(name).display()
            ));
        }
    }
    Ok(output_dir)
}

fn same_bytes(left: &Path, right: &Path) -> Result<bool, String> {
    let left_bytes =
        fs::read(left).map_err(|error| format!("failed to read {}: {error}", left.display()))?;
    let right_bytes =
        fs::read(right).map_err(|error| format!("failed to read {}: {error}", right.display()))?;
    Ok(left_bytes == right_bytes)
}

fn check(root: &Path) -> Result<String, String> {
    let built = build_temp(root)?;
    let tracked = root.join(GENERATED_RELATIVE);
    let adapter = root.join(ADAPTER_RELATIVE);

    let mut drift = Vec::new();
    for name in [JS_NAME, WASM_NAME] {
        let tracked_file = tracked.join(name);
        if !tracked_file.is_file() || !same_bytes(&built.join(name), &tracked_file)? {
            drift.push(tracked_file.to_string_lossy().into_owned());
        }
    }

    let mut tracked_names = if tracked.is_dir() {
        fs::read_dir(&tracked)
            .map_err(|error| format!("failed to list {}: {error}", tracked.display()))?
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
    } else {
        Vec::new()
    };
    tracked_names.sort();
    let expected_names = vec![JS_NAME.to_owned(), WASM_NAME.to_owned()];
    if tracked_names != expected_names {
        drift.push(format!(
            "{}:unexpected-generated-file-set={}",
            tracked.display(),
            tracked_names.join(",")
        ));
    }

    let expected_adapter = adapter_source();
    let actual_adapter = fs::read_to_string(&adapter).unwrap_or_default();
    if actual_adapter != expected_adapter {
        drift.push(adapter.to_string_lossy().into_owned());
    }

    if drift.is_empty() {
        Ok(format!(
            "FRONTEND_WASM_CODEGEN=PASS\nWASM_PACK_VERSION={}\nARTIFACT_COUNT=3",
            WASM_PACK_VERSION.trim_start_matches("wasm-pack ")
        ))
    } else {
        Err(format!(
            "FRONTEND_WASM_CODEGEN=FAIL\nDRIFT={}",
            drift.join(",")
        ))
    }
}

fn write(root: &Path) -> Result<String, String> {
    let built = build_temp(root)?;
    let tracked = root.join(GENERATED_RELATIVE);
    fs::create_dir_all(&tracked)
        .map_err(|error| format!("failed to create {}: {error}", tracked.display()))?;

    let mut changed = 0_usize;
    for name in [JS_NAME, WASM_NAME] {
        let source = built.join(name);
        let destination = tracked.join(name);
        let differs = !destination.is_file() || !same_bytes(&source, &destination)?;
        if differs {
            fs::copy(&source, &destination).map_err(|error| {
                format!(
                    "failed to copy {} to {}: {error}",
                    source.display(),
                    destination.display()
                )
            })?;
            changed += 1;
        }
    }

    let adapter = root.join(ADAPTER_RELATIVE);
    let expected_adapter = adapter_source();
    let actual_adapter = fs::read_to_string(&adapter).unwrap_or_default();
    if actual_adapter != expected_adapter {
        fs::write(&adapter, expected_adapter.as_bytes())
            .map_err(|error| format!("failed to write {}: {error}", adapter.display()))?;
        changed += 1;
    }

    Ok(format!(
        "FRONTEND_WASM_CODEGEN=WRITE_PASS\nWASM_PACK_VERSION={}\nARTIFACT_COUNT=3\nCHANGED={changed}",
        WASM_PACK_VERSION.trim_start_matches("wasm-pack ")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adapter_is_generated_and_uses_rust_exports_only() {
        let adapter = adapter_source();
        assert!(adapter.contains("@generated"));
        assert!(adapter.contains("await init();"));
        assert!(adapter.contains("wasmToEnglishDigits(value)"));
        assert!(adapter.contains("wasmPick(values)"));
        assert!(adapter.contains("wasmToNumber(value, fallback)"));
        assert!(adapter.contains("wasmKgwClean2SafeText(value)"));
        assert!(!adapter.contains("replaceAll("));
        assert!(!adapter.contains("Number.isFinite"));
    }

    #[test]
    fn generated_paths_are_inside_frontend_or_target() {
        assert!(GENERATED_RELATIVE.starts_with("apps/kaspa-gateway-desktop/frontend/"));
        assert!(ADAPTER_RELATIVE.ends_with("explorer.utils.js"));
        let root = Path::new("repo");
        assert!(temp_output(root).starts_with(root.join("target")));
    }
}
