// @generated by cargo run --locked -p xtask -- frontend-wasm-codegen write
// Rust owns Log tab state, rendering, polling, clipboard fallback, and trace behavior.
// This module is deterministic browser/WASM ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import init, {
  kgwLogCopyTextToClipboard as wasmKgwCopyTextToClipboard,
  kgwLogInitTab as wasmInitLogTab,
  kgwLogParseLevel as wasmKgwParseLogLevel,
} from "../../../generated/kgw_frontend_wasm/kgw_frontend_wasm.js";

await init();

export function kgwParseLogLevel(line) {
  return wasmKgwParseLogLevel(line);
}

export async function kgwCopyTextToClipboard(text, env = {}) {
  return await wasmKgwCopyTextToClipboard(text, env);
}

export function initLogTab() {
  return wasmInitLogTab();
}

window.initLogTab = initLogTab;
