// ============================================================================
// KGW_FINAL_EXPLORER_FACADE_ONLY
// Compatibility facade only.
// This file may preserve stable frontend command names.
// It must delegate transaction sync/list work to kaspa_gateway_runtime.
// It must not implement pagination, DB write loops, forced-fetch deletion,
// API fetch orchestration, or transaction ownership.
// ============================================================================

// ============================================================================
// KGW_OWNERSHIP_EXPLORER_UNIFIED_FACADE_ONLY
// Compatibility facade only.
// It may preserve stable frontend command names, but transaction sync/list work
// must delegate to kaspa_gateway_runtime::transaction_sync.
// It must not become a second fetch implementation.
// ============================================================================

// ============================================================================
// KGW PHASE 3A ROUTING FREEZE
// Marker: KGW_OFFICIAL_RUNTIME_ROUTE_VIA_EXPLORER_UNIFIED
//
// This file is the currently registered Tauri fetch/sync route.
// It must remain a thin facade over kaspa_gateway_runtime::transaction_sync.
// It may call sync_transactions and list_transactions_grouped_by_day.
// It must not grow a second pagination, API, or DB orchestration loop.
// Future cleanup may move this command into transaction_commands.rs, but only
// after command names, frontend invokes, and capabilities are stable.
// ============================================================================
// ============================================================================
// KGW ARCHITECTURE OWNER MAP
// Generated by automated light cleanup script.
// Role: Explorer compatibility/facade layer
// Owner status: FACADE_NOT_FETCH_OWNER
//
// Rules:
// - crates/kaspa-gateway-runtime/src/transaction_sync.rs is the official owner
//   of transaction fetch/sync orchestration.
// - Tauri command files must only validate/translate IPC inputs and call the
//   runtime service. They must not duplicate pagination, DB write, or API fetch
//   loops.
// - Explorer facade files may preserve compatibility, but they must not become
//   a second fetch implementation.
// - Do not delete legacy code in this phase. Mark, route, document, then remove
//   only after parity tests pass.
// ============================================================================
use crate::{app_logger, db_state};
use kaspa_gateway_core::KaspaAddress;
use kaspa_gateway_runtime::transaction_sync::{
    TransactionDayGroup, TransactionListRequest, TransactionSyncRequest, TransactionSyncSummary,
    list_transactions_grouped_by_day, request_transaction_sync_cancel,
    set_transaction_sync_progress_callback, sync_transactions,
};
use serde::Serialize;
use std::sync::Arc;
use std::time::Instant;
use tauri::{AppHandle, Emitter};

#[derive(Debug, Clone, Serialize)]
pub struct ExplorerUnifiedTransactionsReport {
    pub summary: TransactionSyncSummary,
    pub groups: Vec<TransactionDayGroup>,
    pub rows: usize,
    pub db_rows_before: usize,
    pub db_rows_after: usize,
    pub source: String,
}

fn count_rows(groups: &[TransactionDayGroup]) -> usize {
    groups.iter().map(|group| group.transactions.len()).sum()
}

#[tauri::command]
pub async fn explorer_cancel_transactions(request_id: String) -> Result<bool, String> {
    let trimmed = request_id.trim();

    if trimmed.is_empty() {
        return Ok(false);
    }

    let accepted = request_transaction_sync_cancel(trimmed);

    app_logger::log_info(
        "transactions",
        &format!(
            "explorer transaction cancel requested request_id={} accepted={}",
            trimmed, accepted
        ),
    );

    Ok(accepted)
}

#[tauri::command]
pub async fn explorer_transactions(
    app: AppHandle,
    request: TransactionSyncRequest,
) -> Result<ExplorerUnifiedTransactionsReport, String> {
    let started = Instant::now();

    let parsed = KaspaAddress::parse(&request.address).map_err(|error| error.to_string())?;
    let canonical_address = parsed.as_str().to_string();

    let mut request_for_worker = request.clone();
    request_for_worker.address = canonical_address.clone();

    app_logger::log_info(
        "transactions",
        &format!(
            "FETCH LOOP STARTED. StartTS: {:?}, EndTS: {:?}, Force: {}, MaxPages: {:?}",
            request_for_worker.start_ts,
            request_for_worker.end_ts,
            request_for_worker.force,
            request_for_worker.max_pages
        ),
    );

    tauri::async_runtime::spawn_blocking(move || -> Result<ExplorerUnifiedTransactionsReport, String> {
        let worker_started = Instant::now();

        app_logger::log_info(
            "transactions",
            &format!(
                "unified write phase start address={} force={} start_ts={:?} end_ts={:?}",
                request_for_worker.address,
                request_for_worker.force,
                request_for_worker.start_ts,
                request_for_worker.end_ts
            ),
        );

        let summary = db_state::with_database_manager(
            "explorer.transactions.unified.write",
            |manager| {
                let repo = manager
                    .transactions_repository()
                    .map_err(|error| error.to_string())?;

                set_transaction_sync_progress_callback(Some(Arc::new({
                    let app = app.clone();

                    move |progress| {
                        let _ = app.emit("kgw://transactions/page-stored", progress);
                    }
                })));

                let result = tauri::async_runtime::block_on(sync_transactions(
                    &repo,
                    request_for_worker.clone(),
                ));

                set_transaction_sync_progress_callback(None);

                result
            },
        )?;

        app_logger::log_info(
            "transactions",
            &format!(
                "unified write phase done address={} mode={} stored={} fetched={} accepted={} pages={} deleted={} stop_reason={} elapsed_ms={}",
                summary.address,
                summary.mode,
                summary.stored,
                summary.fetched_from_api,
                summary.accepted_for_range,
                summary.pages,
                summary.deleted_before_fetch,
                summary.stop_reason,
                worker_started.elapsed().as_millis()
            ),
        );

        app_logger::log_info(
            "transactions",
            &format!(
                "unified read phase start address={} start_ts={:?} end_ts={:?} tx_type={:?} direction={:?} search={:?}",
                summary.address,
                request_for_worker.start_ts,
                request_for_worker.end_ts,
                request_for_worker.tx_type,
                request_for_worker.direction,
                request_for_worker.search_query
            ),
        );

        let groups = db_state::with_database_manager(
            "explorer.transactions.unified.read_after_write",
            |manager| {
                let repo = manager
                    .transactions_repository()
                    .map_err(|error| error.to_string())?;

                let list_request = TransactionListRequest {
                    address: summary.address.clone(),
                    start_ts: request_for_worker.start_ts,
                    end_ts: request_for_worker.end_ts,
                    tx_type: request_for_worker.tx_type.clone(),
                    direction: request_for_worker.direction.clone(),
                    search_query: request_for_worker.search_query.clone(),
                    limit: Some(1_000_000),
                };

                list_transactions_grouped_by_day(&repo, list_request)
            },
        )?;

        let rows = count_rows(&groups);

        app_logger::log_info(
            "transactions",
            &format!(
                "Fetch done ({} ms), stored={}, fetched={}, accepted={}, pages={}, local={}, deleted={}, stopped_existing={}, stopped_start={}, stop={}, groups={}, rows={}",
                started.elapsed().as_millis(),
                summary.stored,
                summary.fetched_from_api,
                summary.accepted_for_range,
                summary.pages,
                summary.local_loaded,
                summary.deleted_before_fetch,
                summary.stopped_by_existing_txid,
                summary.stopped_by_start_date,
                summary.stop_reason,
                groups.len(),
                rows
            ),
        );

        Ok(ExplorerUnifiedTransactionsReport {
            summary,
            groups,
            rows,
            db_rows_before: 0,
            db_rows_after: rows,
            source: "transactions_db_after_sync_split_connection".to_string(),
        })
    })
    .await
    .map_err(|error| format!("unified transaction worker join failed: {error}"))?
}

#[tauri::command]
pub async fn explorer_delete_transactions_for_address(address: String) -> Result<i64, String> {
    let parsed = KaspaAddress::parse(&address).map_err(|error| error.to_string())?;
    let canonical_address = parsed.as_str().to_string();

    app_logger::log_info(
        "transactions",
        &format!(
            "delete transactions for saved address requested address={}",
            canonical_address
        ),
    );

    tauri::async_runtime::spawn_blocking(move || {
        db_state::with_database_manager("transactions.delete_for_address", |manager| {
            let repo = manager
                .transactions_repository()
                .map_err(|error| error.to_string())?;

            let deleted = repo
                .delete_for_address(&canonical_address)
                .map_err(|error| error.to_string())?;

            app_logger::log_info(
                "transactions",
                &format!(
                    "delete transactions for saved address ok address={} deleted={}",
                    canonical_address, deleted
                ),
            );

            Ok(deleted)
        })
    })
    .await
    .map_err(|error| format!("delete transactions worker join failed: {error}"))?
}
