// ============================================================================
// KGW_FINAL_TAURI_TRANSACTION_ADAPTER
// Tauri IPC adapter only.
// This file may validate/translate request/response shapes.
// It must delegate transaction sync/list ownership to kaspa_gateway_runtime.
// It must not become a second transaction runtime.
// ============================================================================

// ============================================================================
// KGW_OWNERSHIP_TAURI_TRANSACTION_ADAPTER_ONLY
// This file is a Tauri IPC adapter only.
// Allowed: validate IPC input, map DTOs, call runtime services, convert errors.
// Forbidden: direct API clients, pagination loops, DB write orchestration,
// and duplicate transaction fetch/sync logic.
// ============================================================================

// ============================================================================
// KGW PHASE 7A OWNERSHIP CLEANUP GATE
// Marker: KGW_PHASE7A_TAURI_TRANSACTION_ADAPTER_ONLY
//
// This file must remain a Tauri IPC adapter.
// Allowed: validate IPC input, translate DTOs, call runtime services, return DTOs.
// Forbidden: duplicate pagination loops, API fetch loops, DB write orchestration.
// The official transaction fetch/sync owner is:
// crates/kaspa-gateway-runtime/src/transaction_sync.rs
// ============================================================================
// ============================================================================
// KGW PHASE 3A TAURI ADAPTER STATUS
// Marker: KGW_TRANSACTION_COMMANDS_ADAPTER_LAYER
//
// This file is the target adapter layer for transaction commands.
// Current list/group commands already delegate to transaction_sync.rs.
// Fetch/sync routing is currently frozen through transaction_routes.rs to avoid
// changing frontend command names before parity checks are complete.
// ============================================================================
// ============================================================================
// KGW ARCHITECTURE OWNER MAP
// Generated by automated light cleanup script.
// Role: Tauri IPC command adapter for transaction operations
// Owner status: ADAPTER_ONLY
//
// Rules:
// - crates/kaspa-gateway-runtime/src/transaction_sync.rs is the official owner
//   of transaction fetch/sync orchestration.
// - Tauri command files must only validate/translate IPC inputs and call the
//   runtime service. They must not duplicate pagination, DB write, or API fetch
//   loops.
// - Explorer facade files may preserve compatibility, but they must not become
//   a second fetch implementation.
// - Do not delete legacy code in this phase. Mark, route, document, then remove
//   only after parity tests pass.
// ============================================================================
use crate::app_logger;
use kaspa_gateway_runtime::transaction_sync::{
    TransactionDayGroup, TransactionListRequest, list_transactions_grouped_by_day,
};
use serde::Serialize;
use std::time::Instant;

#[derive(Debug, Clone, Serialize)]
pub struct ExplorerTransactionDaySummary {
    pub day: String,
    pub count: usize,
    pub incoming_kas: f64,
    pub outgoing_kas: f64,
    pub net_kas: f64,
}

fn sompi_to_kas(value: i64) -> f64 {
    value as f64 / 100_000_000.0
}
#[tauri::command]
pub async fn explorer_list_transactions_grouped_rust(
    request: TransactionListRequest,
) -> Result<Vec<TransactionDayGroup>, String> {
    app_logger::log_info(
        "transactions",
        &format!(
            "live grouped list queued address={} start_ts={:?} end_ts={:?} tx_type={:?} direction={:?} limit={:?}",
            request.address,
            request.start_ts,
            request.end_ts,
            request.tx_type,
            request.direction,
            request.limit
        ),
    );

    tauri::async_runtime::spawn_blocking(move || {
        let started = Instant::now();

        let repo = crate::db_state::transactions_repository_unlocked().map_err(|error| {
            app_logger::log_error(
                "transactions",
                &format!("live sqlite transactions repository failed: {error}"),
            );
            error
        })?;

        match list_transactions_grouped_by_day(&repo, request) {
            Ok(groups) => {
                let rows: usize = groups.iter().map(|group| group.transactions.len()).sum();

                app_logger::log_info(
                    "transactions",
                    &format!(
                        "live grouped list ok groups={} rows={} elapsed_ms={}",
                        groups.len(),
                        rows,
                        started.elapsed().as_millis()
                    ),
                );

                Ok(groups)
            }
            Err(error) => {
                app_logger::log_error(
                    "transactions",
                    &format!(
                        "live grouped list failed elapsed_ms={} error={}",
                        started.elapsed().as_millis(),
                        error
                    ),
                );

                Err(error)
            }
        }
    })
    .await
    .map_err(|error| format!("transaction live grouped list worker join failed: {error}"))?
}

#[tauri::command]
pub async fn explorer_transaction_day_summaries_rust(
    request: TransactionListRequest,
) -> Result<Vec<ExplorerTransactionDaySummary>, String> {
    let started = Instant::now();

    app_logger::log_info(
        "transactions",
        &format!(
            "day summaries command queued address={} start_ts={:?} end_ts={:?} tx_type={:?} direction={:?} search={:?}",
            request.address,
            request.start_ts,
            request.end_ts,
            request.tx_type,
            request.direction,
            request.search_query
        ),
    );

    tauri::async_runtime::spawn_blocking(move || {
        crate::db_state::with_database_manager("transactions.day_summaries", |manager| {
            let repo = manager
                .transactions_repository()
                .map_err(|error| error.to_string())?;

            let parsed = kaspa_gateway_core::KaspaAddress::parse(&request.address)
                .map_err(|error| error.to_string())?;
            let address = parsed.as_str().to_ascii_lowercase();

            let summaries = repo
                .day_summaries_for_address(kaspa_gateway_db::TransactionFilter {
                    address: &address,
                    start_ms: request.start_ts.map(|value| value.saturating_mul(1000)),
                    end_ms: request.end_ts.map(|value| value.saturating_mul(1000)),
                    tx_type: request.tx_type.as_deref(),
                    direction: request.direction.as_deref(),
                    search: request.search_query.as_deref(),
                    limit: request.limit.or(Some(10_000)),
                })
                .map_err(|error| error.to_string())?;

            let result = summaries
                .into_iter()
                .map(|summary| {
                    let incoming_kas = sompi_to_kas(summary.incoming_sompi);
                    let outgoing_kas = sompi_to_kas(summary.outgoing_sompi);

                    ExplorerTransactionDaySummary {
                        day: summary.day,
                        count: summary.count,
                        incoming_kas,
                        outgoing_kas,
                        net_kas: incoming_kas - outgoing_kas,
                    }
                })
                .collect::<Vec<_>>();

            app_logger::log_info(
                "transactions",
                &format!(
                    "day summaries ok days={} elapsed_ms={}",
                    result.len(),
                    started.elapsed().as_millis()
                ),
            );

            Ok(result)
        })
    })
    .await
    .map_err(|error| format!("transaction day summaries worker join failed: {error}"))?
}
