// @generated by cargo run --locked -p xtask -- e2e-wasm-codegen write
// Rust owns the implementation. This module is deterministic Node ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const wasm = require("../generated/kgw_e2e_wasm/kgw_e2e_wasm.js");

export const rawLogRejectionMarkers = Object.freeze([...wasm.rawLogRejectionMarkers()]);

export function sha256Hex(text) {
  return wasm.sha256Hex(text);
}

export function normalizeClipboardText(text) {
  return wasm.normalizeClipboardText(text);
}

export function lineCount(text) {
  return wasm.lineCount(text);
}

export function containsTransportWrapper(text) {
  return wasm.containsTransportWrapper(text);
}

export function parseKeyValueLine(text) {
  return wasm.parseKeyValueLine(text);
}

export function pidFromStatus(statusText) {
  return wasm.pidFromStatus(statusText);
}

export function isStoppedOwnerStatus(statusText) {
  return wasm.isStoppedOwnerStatus(statusText);
}

export function assertNoTransportWrappers(text, label) {
  return wasm.assertNoTransportWrappers(text, label);
}

export function assertDirectRawPayload(options) {
  return wasm.assertDirectRawPayload(options);
}

export function assertRuntimeLogReport(report, options) {
  return wasm.assertRuntimeLogReport(report, options);
}
