// @generated by cargo run --locked -p xtask -- e2e-wasm-codegen write
// Rust owns the implementation. This module is deterministic Node ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const wasm = require("../generated/kgw_e2e_wasm/kgw_e2e_wasm.js");
const context = wasm.artifactPathContext(import.meta.url, process.env);

export const e2eDir = context.e2eDir;
export const repository = context.repository;
export const artifactRoot = context.artifactRoot;

export function ensureDir(directory) {
  return wasm.artifactEnsureDir(directory);
}

export function caseDir(slug) {
  return wasm.artifactCaseDir(artifactRoot, slug);
}

export function writeJson(file, value) {
  return wasm.artifactWriteJson(file, value);
}

export function writeText(file, value) {
  return wasm.artifactWriteText(file, value);
}

export function helperScript(name) {
  return wasm.artifactHelperScript(e2eDir, name);
}
