// @generated by cargo run --locked -p xtask -- e2e-wasm-codegen write
// Rust owns the implementation. This module is deterministic Node ABI glue only.
// DO NOT EDIT THIS FILE DIRECTLY.
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const wasm = require("../generated/kgw_e2e_wasm/kgw_e2e_wasm.js");

export function runtimePortProfile(env = process.env) {
  return wasm.runtimePortProfile(env);
}
